# Common Labels
labels:
  app: "mukta-contracts"
  group: "mukta"

namespace: mukta

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "mukta-contract"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "contracts_schema"
    image:
      repository: "mukta-contracts-db"

# Container Configs
image:
  repository: "mukta-contracts"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/mukta-contract/health"
  readinessProbePath: "/mukta-contract/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
memory_limits: 512Mi
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  - name: SMS_ISADDTIONALFIELDREQUIRED
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: sms-isAdditonalFieldRequired
  {{- end }}
  - name: SERVER_CONTEXT_PATH
    value: /mukta-contract
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /mukta-contract
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: WORKS_ESTIMATE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: estimate-service
  - name: EGOV_HRMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-hrms
  - name: EGOV_ATTENDANCE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: attendance-service
  - name: EGOV_ORG_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: organisation
  - name: EGOV_URL_SHORTNER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-url-shortening
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_MDMS_V2_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service-v2
  - name: WORKS_PROJECT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: project-management-system
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: WORKS_MUSTER_ROLL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: muster-roll-service      
  - name: CONTRACT_KAFKA_CREATE_TOPIC
    value: "mukta-save-contract"
  - name: CONTRACT_KAFKA_UPDATE_TOPIC
    value: "mukta-update-contract"
  - name: KAFKA_TOPICS_NOTIFICATION_SMS
    value: "mukta.egov.core.notification.sms"
  - name: KAFKA_TOPICS_WORKS_NOTIFICATION_SMS
    value: "mukta.works.notification.sms"
  {{- if index .Values "contracts-revision-topic" }}
  - name: CONTRACTS_REVISION_TOPIC
    value: {{ index .Values "contracts-revision-topic" | quote }} 
  {{- end }}  
  {{- if index .Values "contract-default-offset" }}
  - name: CONTRACT_DEFAULT_OFFSET
    value: {{ index .Values "contract-default-offset" | quote }}
  {{- end }}
  {{- if index .Values "contract-default-limit" }}
  - name: CONTRACT_DEFAULT_LIMIT
    value: {{ index .Values "contract-default-limit" | quote }}
  {{- end }}
  {{- if index .Values "contract-search-max-limit" }}
  - name: CONTRACT_SEARCH_MAX_LIMIT
    value: {{ index .Values "contract-search-max-limit" | quote }}
  {{- end }}
  {{- if index .Values "works-contract-service-code" }}
  - name: WORKS_CONTRACT_SERVICE_CODE
    value: {{ index .Values "works-contract-service-code" | quote }}
  {{- end }}
  {{- if index .Values "contract-workflow-business-service" }}
  - name: CONTRACT_WORKFLOW_BUSINESS_SERVICE
    value: {{ index .Values "contract-workflow-business-service" | quote }}
  {{- end }}
  {{- if index .Values "contract-workflow-module-name" }}
  - name: CONTRACT_WORKFLOW_MODULE_NAME
    value: {{ index .Values "contract-workflow-module-name" | quote }}
  {{- end }}
  {{- if index .Values "contract-cbo-url-host" }}
  - name: CONTRACT_CBO_URL_HOST
    value: {{ index .Values "contract-cbo-url-host" | quote }}
  {{- end }}
  {{- if index .Values "contract-cbo-url-endpoint" }}
  - name: CONTRACT_CBO_URL_ENDPOINT
    value: {{ index .Values "contract-cbo-url-endpoint" | quote }}
  {{- end }}
  {{- if index .Values "contract-workflow-revision-business-service" }}
  - name: CONTRACT_WORKFLOW_REVISION_BUSINESS_SERVICE
    value: {{ index .Values "contract-workflow-revision-business-service" | quote }}
  {{- end }}
  {{- if index .Values "egov.contract.service.search.endpoint" }}
  - name: EGOV_CONTRACT_SERVICE_SEARCH_ENDPOINT
    value: {{ index .Values "/mukta-contract/v1/_search" | quote }}
  {{- end }}
  - name: EGOV_HRMS_SEARCH_ENDPOINT
    value: "mukta-egov-hrms/employees/_search"
  - name: WORKS_ESTIMATE_SEARCH_ENDPOINT
    value: "/mukta-estimate/v1/_search"
