# Common Labels
labels:
  app: "fiscal-event-aggregator"
  group: "ifix"

cron:
  schedule: "0 0 * * *"  
# Container Configs
image:
  repository: "fiscal-event-aggregator"

cron_appType: "java-spring"
dbMigration:
  schemaTable: "fiscal_event_aggregator_schema"
fiscal-event-datasource: "fiscal-event"


# Additional Container Envs
env: |
  - name: DRUID_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: druid-host
  - name: FISCAL_EVENT_DATASOURCE
    value: {{ index .Values "fiscal-event-datasource" | quote }}
  - name: DRUID_CONNECT_PROTOCOL
    value: "HTTP"
  - name: DRUID_CONNECT_PORT
    value: "8082"
