# Common Labels
labels:
  app: "employee-mcs"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "employee-mcs"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "employee-mcs"
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/employee-mcs/"
  readinessProbePath: "/employee-mcs/"
dashboard-url: ""

# Additional Container Envs
env: |
  - name: REACT_APP_WS_FINANCIALINDICATORS
    value: {{ index .Values "dashboard-url" | quote }}

extraVolumes: |
  - name: js-injection
    configMap:
      name: employee-mcs-js-injection

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
    
namespace: upyog
