# Common Labels
labels:
  app: "tenant-management"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "tenant-management"

initContainers:
  dbMigration:
    enabled: true
    schemaTable: "tenant_management_schema"
    image:
      repository: "tenant-management-db"

# Container Configs
image:
  repository: "tenant-management"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/tenant-management/health"
  readinessProbePath: "/tenant-management/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"
kafka-topics-create-tenant: "create-tenant"
kafka-topics-update-tenant: "update-tenant"
# Resource configuration for Go service
resources: |
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "200m"
    memory: "512Mi"

# Additional Container Envs
env: |
  - name: SERVER_CONTEXT_PATH
    value: /tenant-management
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: tenant-management
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  {{- if index .Values "global" "serializers-timezone-in-ist" }}
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
  {{- end }}
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_USER_OTP_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: user-otp        
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  - name: KAFKA_TOPICS_CREATE_TENANT
    value: {{ index .Values "kafka-topics-create-tenant" | quote }}
  - name: KAFKA_TOPICS_UPDATE_TENANT
    value: {{ index .Values "kafka-topics-update-tenant" | quote }}
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: mdms-service-v2    
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-otel-url
  - name: OTEL_TRACES_EXPORTER
    value: "none"
  - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
    value: "org.postgresql.Driver"