version: v1.0
modules:
    - name: backbone
      services:
        - zookeeper-v2
        - kafka-v2
        - kafka-connect
        - kafka-connect-restart-tasks
        - elasticsearch-data-v1
        - elasticsearch-master-v1
        - kibana-v1
        - egovio/postgres:11
    - name: authn-authz
      services:
        - redis
        - nginx-ingress
        - cert-manager
        - zuul:v1.3.1-96b24b0d72-39     
    - name: m_core
      dependencies:
        - "backbone"
        - "authn-authz"    
      services:
        - egovio/egov-mdms-service:v1.3.2-72f8a8f87b-12
        - egovio/egov-enc-service:v1.1.2-72f8a8f87b-9
        - egovio/egov-user-db:develop-fcc6127bb6-60
        - egovio/egov-location:v1.1.4-72f8a8f87b-6
        - egovio/playground:1.3
