# Common Labels
labels:
  app: "pgr-ui"
  group: "web"

namespace: health    

# Ingress Configs
ingress:
  enabled: true
  context: "pgr-ui"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "pgr-ui"
replicas: "1"
appType: "java-spring"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/pgr-ui/"
  readinessProbePath: "/pgr-ui/"
tracing-enabled: true
memory_limits: "256Mi"
cpu_limits: '100m'

extraVolumes: |
  - name: js-injection
    configMap:
      name: pgr-ui-js-injection

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
