apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: egov-pgrrest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: egov-pgrrest
        tier: backend
    spec:
      containers:
        - name: egov-pgrrest
          image: egovio/pgrrest:latest
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
          env:
          - name: REDIS_HOST
            value: redis-master
          - name: DB_HOST
            value: "ap1-qa-psql-monolith.ctm6jbmr5mnj.ap-south-1.rds.amazonaws.com"
          - name: DB_USER
            value: egov
          - name: DB_NAME
            value: egov_qa
          - name: DB_PASSWORD
            value: "I<3ChanaMasala!"
          - name: MASTER_SERVER
            value: "false"
          - name: CORS_ENABLED
            value: "true"
          ports:
          - containerPort: 8080

