# Common Labels
labels:
  app: "egov-telemetry-kafka-streams"
  group: "core"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "egov-telemetry-kafka-streams"
#replicas: "1"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"

memory_requests: "256Mi"
memory_limits: "256Mi"
cpu_limits: "20m"
cpu_requests: "10m"

# Additional Container Envs
env: |
  - name: BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers  
  - name: TELEMETRY_RAW_INPUT
    value: "telemetry-raw-input"
  - name: TELEMETRY_VALIDATED_MESSAGES
    value: "telemetry-validated-messages"
  - name: TELEMETRY_DEDUPED_MESSAGES
    value: "telemetry-deduped-messages"
  - name: TELEMETRY_FINAL_MESSAGES
    value: "telemetry-final-messages"
  - name: STREAM_NAME_TELEMETRY_VALIDATOR
    value: "stream-name-telemetry-validator"
  - name: STREAM_NAME_TELEMETRY_DEDUPLICATOR
    value: "stream-name-telemetry-deduplicator"
  - name: STREAM_NAME_TELEMETRY_UNBUNDLING
    value: "stream-name-telemetry-unbundling"
  - name: STREAM_NAME_TELEMETRY_ENRICHMENT
    value: "stream-name-telemetry-enrichment"
  - name: STREAM_NAME_TELEMETRY_SECOR_FINAL_PUSH
    value: "stream-name-telemetry-secor-final-push"
  - name: STREAM_NAME_TELEMETRY_ELASTICSEARCH_FINAL_PUSH
    value: "stream-name-telemetry-es-final-push"
  - name: DEDUP_STORAGE_TIME
    value: "60"
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
