# Common Labels
labels:
  app: "estimates"
  group: "works"

namespace: staging

hpa:
  enabled: true

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "estimate"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "estimates_schema"
    image:
      repository: "estimates-db"
    env: |
      {{- if index .Values "estimates-ismultischema-enabled" }}        
      - name: SCHEMA_NAME
        value: {{ index .Values "estimates-schemas" | quote }}
      {{- end }}
      - name: "DB_URL"
        valueFrom: 
          configMapKeyRef: 
            name: egov-config
            key: db-url-works
      - name: "SCHEMA_TABLE"
        value: {{ .Values.initContainers.dbMigration.schemaTable | quote }}              
      - name: "FLYWAY_USER"
        valueFrom: 
          secretKeyRef: 
            name: db
            key: flyway-username
      - name: "FLYWAY_PASSWORD"
        valueFrom:
          secretKeyRef: 
            name: db
            key: flyway-password
      - name: "FLYWAY_LOCATIONS"
        valueFrom: 
          configMapKeyRef: 
            name: egov-config
            key: flyway-locations  
      {{- if index .Values.global "is-environment-central-instance" }}        
      - name: IS_ENVIRONMENT_CENTRAL_INSTANCE
        valueFrom:
          configMapKeyRef:
            name: egov-config
            key: is-environment-central-instance
      - name: STATE_LEVEL_TENANTID_LENGTH
        valueFrom:
          configMapKeyRef:
            name: egov-config
            key: state-level-tenantid-length
      {{- end }}

# Container Configs
image:
  repository: "estimates"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/estimate/health"
  readinessProbePath: "/estimate/health"
appType: "java-spring"
tracing-enabled: true
memory_limits: 512Mi
heap: "-Xmx512m -Xms512m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: SPRING_DATA_REDIS_HOST
    value: redis.backbone
  - name: SPRING_DATA_REDIS_PORT
    value: "6379"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: SERVER_CONTEXT_PATH
    value: /estimate
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /estimate
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/egov-mdms-service/v1/_search"
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_HRMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-hrms
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: EGOV_CONTRACT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: contract-service
  - name: EGOV_MEASUREMENTSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: measurement-service      
  - name: EGOV_MDMS_HOST_V2
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service-v2
  - name: EGOV_MDMS_SEARCH_ENDPOINT_V2
    value: "/mdms-v2/v1/_search"
  - name: EGOV_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  - name: ESTIMATE_KAFKA_CREATE_TOPIC
    value: "save-estimate"
  - name: ESTIMATE_KAFKA_UPDATE_TOPIC
    value: "update-estimate"
  - name: KAFKA_TOPICS_NOTIFICATION_SMS
    value: "egov.core.notification.sms"
  {{- if index .Values "estimate-default-limit" }}
  - name: ESTIMATE_DEFAULT_LIMIT
    value: {{ index .Values "estimate-default-limit" | quote }} 
  {{- end }}
  {{- if index .Values "estimate-search-max-limit" }}
  - name: ESTIMATE_SEARCH_MAX_LIMIT
    value: {{ index .Values "estimate-search-max-limit" | quote }} 
  {{- end }}
  {{- if index .Values "estimate-workflow-business-service" }}
  - name: ESTIMATE_WORKFLOW_BUSINESS_SERVICE
    value: {{ index .Values "estimate-workflow-business-service" | quote }} 
  {{- end }}
  {{- if index .Values "estimate-workflow-module-name" }}
  - name: ESTIMATE_WORKFLOW_MODULE_NAME
    value: {{ index .Values "estimate-workflow-module-name" | quote }} 
  {{- end }}
  {{- if index .Values "estimate-revision-workflow-business-service" }}
  - name: ESTIMATE_REVISION_WORKFLOW_BUSINESS_SERVICE
    value: {{ index .Values "estimate-revision-workflow-business-service" | quote }} 
  {{- end }}
  {{- if index .Values "estimate-revision-measurement-validation" }}
  - name: ESTIMATE_REVISION_MEASUREMENT_VALIDATION
    value: {{ index .Values "estimate-revision-measurement-validation" | quote }} 
  {{- end }}
  {{- if index .Values "estimate-revision-max-limit" }}
  - name: ESTIMATE_REVISION_MAX_LIMIT
    value: {{ index .Values "estimate-revision-max-limit" | quote }} 
  {{- end }}
  - name: WORKS_PROJECT_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: project-management-system
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: "estimate-service"
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
