apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
data: 
  egov-erp-override.properties: |
     scheduler.enabled={{ .Values.scheduler }}
     finance.esk.dashboard.event.enabled={{ .Values.finance }}
     filestore.base.dir={{ .Values.filestore }}
     filestoreservice.beanname={{ .Values.filestore_beanname }}
     dev.mode={{ .Values.dev_mode }}
     secure.cookie={{ .Values.secure_cookie }}

     finance-rollout-dashboard-cron-expression={{ .Values.rollout_dashboard_cron_expression }}

     sms.enabled={{ .Values.sms }}
     mail.enabled={{ .Values.mail }}
     captcha.strength={{ .Values.captcha }}

     #Overridable Properties
     #redis.enable.embedded=true
     redis.host.name={{ .Values.redis_host }}
     redis.host.port={{ .Values.redis_port }}
      
     {{- if .Values.mail_config }}
     #Email Configuration
     {{- tpl  .Values.mail_config . | nindent 5 }}
     {{- end }}

     {{- if .Values.smc_config }}
     #SMS Configuration
     {{- tpl  .Values.smc_config . | nindent 5 }}
     {{- end }}

     {{- if .Values.elastic_config }}
     #Elastic Search Configuration
     {{- tpl  .Values.elastic_config . | nindent 5 }}
     {{- end }}

     {{- if .Values.elastic_search_config }}
     #Elastic Search Configuration
     {{- tpl  .Values.elastic_search_config . | nindent 5 }}
     {{- end }}

     db.flyway.validateon.migrate={{ .Values.db_flyway }}
     # Flyway run Statewide
     statewide.migration.required={{ .Values.statewide_migration }}
     
     {{- if .Values.financeTenants }}
     #Enable or Disable Multitenancy
     multitenancy.enabled={{ .Values.multitenancy }}
     {{- tpl  .Values.financeTenants .  | nindent 5 }}
     {{- else }}
     #Enable or Disable Multitenancy
     multitenancy.enabled={{ .Values.multitenancy }}
     {{- tpl  .Values.tenants . | nindent 5 }}
     {{- end }}

     {{- if .Values.payment_gatway_credential }}
     #Axis Payment Gateway Credentials
     {{- tpl  .Values.payment_gatway_credential . | nindent 5 }}
     {{- end }}
     
     #Do not show Report issues URL
     issue.report.url=

     
     {{- if .Values.microservice }}
     #---------MicroService New Coniguration Start-------------------#

     {{- tpl  .Values.microservice . | nindent 5 }}
     {{- end }}
     
     {{- if .Values.systemintegration }}
     #--------------------------------------SystemIntegration User Details ----------------------------------------#
     {{- tpl  .Values.systemintegration . | nindent 5 }}
     {{- end }}
     #---------End------------------------------------#
