# Common Labels
labels:
  app: "mukta-user-otp"
  group: "user"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "mukta-user-otp"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "mukta-user-otp"
healthChecks:
  enabled: true
  livenessProbePath: "/mukta-user-otp/health"
  readinessProbePath: "/mukta-user-otp/health"
replicas: "1"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_CONTEXTPATH
    value: "/mukta-user-otp"
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: "/mukta-user-otp"
  - name: SERVER_PORT
    value: "8080"
  - name: OTP_HOST
    value: http://egov-otp:8080/otp
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false" 
  - name: USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_LOCALISATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization      
  - name: SMS_TOPIC
    value: mukta.egov.core.notification.sms
  - name: EMAIL_TOPIC
    value: mukta.egov.core.notification.email
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"     
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
