# Common Labels
labels:
  app: "egov-custom-consumer"
  group: "core"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "egovio/egov-custom-consumer"
replicas: "1"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
erp-host: "https://jalandhar-dev.egovernments.org/"

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-api-gateway
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name:  EGOV_COEXISTENCE_HOSTNAME
    value: {{ index .Values "erp-host" | quote }}

