configmaps:
  egov-config:
    name: egov-config
    namespace: egov
    data:
      db-host: "postgresql-lts.egov:5432" ## Add db-host name eg: egov-demo.database.azure.com
      db-name: "postgres" ## Add db-name
      db-url: "jdbc:postgresql://postgresql-lts.egov:5432/postgres" ## example: jdbc:postgresql://egov-demo.postgres.database.azure.com:5432/egov_demo
      domain: "digit-lts.digit.org" ## Add your Domain Name    
      egov-services-fqdn-name: "https://digit-lts.digit.org/" ## Add your Domain Name
      egov-state-level-tenant-id: "pg" 
      s3-assets-bucket: "(pg-egov-assets|egov-playground-assets)"
      es-host: "elasticsearch-data-v1.es-cluster"
      es-indexer-host: "http://elasticsearch-data-v1.es-cluster:9200/"
      flyway-locations: "filesystem:/flyway/sql,filesystem:/flyway/seed,filesystem:/flyway/qa"
      kafka-brokers: "release-name-kafka-controller-headless.kafka-kraft:9092"
      kafka-infra-brokers: kafka-v2-infra.kafka-cluster:9092
      logging-level-jdbc: "DEBUG"
      mobile-validation-workaround: "true"
      serializers-timezone-in-ist: "true"
      server-tomcat-max-connections: "500"
      server-tomcat-max-threads: "10"
      sms-enabled: "true"
      spring-datasource-tomcat-initialSize: "1"
      spring-datasource-tomcat-max-active: "2"
      spring-jpa-show-sql: "true"
      timezone: Asia/Kolkata
      tracer-errors-provideexceptionindetails: "true"
      egov-bnd-freedownload-tenants: "pg.testing"
      egov-bnd-live-citizen-tenants: "pg.testing"
  egov-service-host:
    name: egov-service-host
    namespace: egov
    data:
      asset-services: "http://asset-services:8080/"
      asset-services-maha: "http://asset-services-maha:8080/"
      billing-service: "http://billing-service.egov:8080/"
      collection-services: "http://collection-services.egov:8080/"
      collection-masters: "http://collection-masters:8080/"
      collection-search-indexer: "http://collection-search-indexer:8080/"
      citizen-indexer: "http://citizen-indexer:8080/"
      citizen-services: "http://citizen-services:8080/"
      dashboard-analytics: http://dashboard-analytics.egov:8080/
      dashboard-ingest: http://dashboard-ingest.egov:8080/
      demand-services: "http://demand-services:8080/"
      data-sync-employee: "http://data-sync-employee:8080/"
      egov-common-masters: "http://egov-common-masters:8080/"
      egf-masters: "http://egf-masters:8080/"
      egf-master: "http://egf-master.egov:8080/"
      egf-instrument: "http://egf-instrument.egov:8080/"
      egf-voucher: "http://egf-voucher:8080/"
      egf-bill: "http://egf-bill:8080/"
      egov-enc-service: "http://egov-enc-service.egov:8080/"
      egf-voucher-workflow: "http://egf-voucher-workflow:8080/"
      egov-accesscontrol: "http://egov-accesscontrol.egov:8080/"
      egov-user: "http://egov-user.egov:8080/"
      egov-user-egov: "http://egov-user.egov:8080/"
      egov-location: "http://egov-location.egov:8080/"
      egov-filestore: "http://egov-filestore.egov:8080/"
      egov-localization: "http://egov-localization.egov:8080/"
      egov-idgen: "http://egov-idgen.egov:8080/"
      egov-otp: "http://egov-otp.egov:8080/"
      egov-common-workflows: "http://egov-common-workflows:8080/"
      egov-mdms-service: "http://egov-mdms-service.egov:8080/"
      egov-mdms-service-test: "http://egov-mdms-service-test:8080/"
      egov-mdms-create: "http://egov-mdms-create:8080/"
      egov-eis: "http://egov-eis:8080/"
      egov-workflow: "http://egov-workflow.egov:8080/"
      egov-workflow-v2: "http://egov-workflow-v2.egov:8080/"
      egov-searcher: "http://egov-searcher.egov:8080/"
      egov-data-uploader: "http://egov-data-uploader.egov:8080/"
      egov-indexer: "http://egov-indexer.egov:8080/"
      egov-hrms: "http://egov-hrms.egov:8080/"
      es-client: "http://elasticsearch-data-v1.es-cluster:9200"
      hr-masters: "http://hr-masters:8080/"
      hr-employee: "http://hr-employee:8080/"
      hr-masters-v2: "http://hr-masters-v2:8080/"
      hr-employee-v2: "http://hr-employee-v2:8080/"
      hr-attendance: "http://hr-attendance:8080/"
      hr-leave: "http://hr-leave:8080/"
      hr-employee-movement: "http://hr-employee-movement:8080/"
      inventory-services: "http://inventory-services:8080/"
      lams-services: "http://lams-services:8080/"
      lcms-workflow: "http://lcms-workflow:8080/"
      lcms-services: "http://lcms-services:8080/"
      location: "http://location:8080/"
      performance-assessment: "http://performance-assessment:8080/"
      pt-property: "http://pt-property:8080/"
      pt-workflow: "http://pt-workflow:8080/"
      pt-tax-enrichment: "http://pt-tax-enrichment:8080/"
      pt-calculator: "http://pt-calculator:8080/"
      pt-calculator-v2: "http://pt-calculator-v2:8080/"
      pt-services-v2: "http://pt-services-v2:8080/"
      property-services: "http://property-services.egov:8080/"
      pgr-master: "http://pgr-master:8080/"
      pgr-rest: "http://pgr-rest:8080/"
      pdf-service: "http://pdf-service.egov:8080/"
      report: "http://report.egov:8080/"
      swm-services: "http://swm-services:8080/"
      tenant: "http://tenant:8080/"
      tl-masters: "http://tl-masters:8080/"
      tl-services: "http://tl-services:8080/"
      tl-workflow: "http://tl-workflow:8080/"
      tl-indexer: "http://tl-indexer:8080/"
      tl-calculator: "http://tl-calculator:8080/"
      user-otp: "http://user-otp.egov:8080/"
      firenoc-services: "http://firenoc-services:8080/"
      firenoc-calculator: "http://firenoc-calculator:8080/"
      egov-apportion-service: "http://egov-apportion-service:8080/"
      bpa-services: "http://bpa-services.egov:8080/"
      bpa-calculator: "http://bpa-calculator.egov:8080/"
      rainmaker-pgr: "http://rainmaker-pgr:8080/"
      ws-calculator: "http://ws-calculator.egov:8080/"
      ws-services: "http://ws-services.egov:8080/"
      sw-services: "http://sw-services.egov:8080/"
      sw-calculator: "http://sw-calculator.egov:8080/"
      land-services: "http://land-services.egov:8080/"
      noc-services: "http://noc-services.egov:8080/"
      minio-url: "https://minio-uat.digit.org/"
      egov-user-chatbot: "http://egov-user-chatbot:8080/"
      zuul: "http://zuul:8080/"
      egov-url-shortening: "http://eus:8080/"
      fsm-calculator: "http://fsm-calculator.sanitation:8080/"
      fsm: "http://fsm.sanitation:8080/"
      vehicle: "http://vehicle.sanitation:8080"
      trackingservice: "http://trackingservice.sanitation:8080"
      vendor: "http://vendor.sanitation:8080"
      project: "http://project.egov:8080/"
      individual: "http://individual.egov:8080/"
      household: "http://household.health:8080/"
      product: "http://product.health:8080/"
      facility: "http://facility.health:8080/"
      egov-edcr: "http://egov-edcr.egov:8080/"
      echallan-calculator: http://echallan-calculator.egov:8080/
      echallan-services: http://echallan-services.egov:8080/
      inbox: "http://inbox.egov:8080/"
      turn-io-adapter: "http://turn-io-adapter.egov:8080/"
      pgr-services: "http://pgr-services.egov:8080/"
      birth-death-services: "http://birth-death-services.egov:8080/"
      egov-pdf: "http://egov-pdf.egov:8080/"
      egov-user-event: "http://egov-user-event.egov:8080/"
      mdms-service-v2: "http://mdms-v2.egov:8080/"
      health-project: 'http://health-project.health:8080/'
      health-individual: 'http://health-individual.health:8080/'

secrets:
  db:
    name: db
    namespace: egov
  git-sync:
    name: git-creds
    namespace: egov
  egov-filestore:
    name: egov-filestore
    namespace: egov
  egov-location:
    name: egov-location
    namespace: egov
  egov-enc-service:
    name: egov-enc-service
    namespace: egov
  egov-notification-sms:
    name: egov-notification-sms
    namespace: egov
  egov-notification-mail:
    name: egov-notification-mail
    namespace: egov
  oauth2-proxy:
    name: oauth2-proxy
    namespace: egov