repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: ingress-nginx
  namespace: helmfile # Replace with your desired namespace
  chart: ./ingress-nginx
  version: 1.0.0 # Replace with the version of your chart, if needed
  values:
    - ./ingress-nginx/values.yaml