# Common Labels
labels:
  app: "egov-url-shortening"
  group: "egov"

# Ingress Configs
ingress:
  enabled: true
  zuul: false
  context: "egov-url-shortening"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov-url-shortening_schema"
    image:
      repository: "egov-url-shortening-db"

# Container Configs
image:
  repository: "egov-url-shortening"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/egov-url-shortening/health"
  readinessProbePath: "/egov-url-shortening/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: "-Dspring.profiles.active=monitoring"
server-context: "/egov-url-shortening"

# Additional Container Envs
env: |
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  - name: SPRING_REDIS_HOST
    value: redis.backbone
  - name: SPRING_REDIS_PORT
    value: "6379"
  - name: SERVER_CONTEXT_PATH
    value: {{ index .Values "server-context" | quote }}
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: {{ index .Values "server-context" | quote }}
  - name: SERVER_CONTEXTPATH
    value: {{ index .Values "server-context" | quote }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  {{- if index .Values "hashids-salt" }}
  - name: HASHIDS_SALT
    value: {{ index .Values "hashids-salt" | quote}}
  - name: HASHIDS_MIN_LENGTH
    value: {{ index .Values "hashids-min-length" | quote}}
  {{- end }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: EGOV_UI_APP_HOST_MAP
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: host-map
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: state-level-tenant-id
  {{- if index .Values "cluster-configs" "configmaps" "egov-config" "data" "is-environment-central-instance" }}        
  - name: IS_ENVIRONMENT_CENTRAL_INSTANCE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: is-environment-central-instance
  - name: STATE_LEVEL_TENANTID_LENGTH
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: state-level-tenantid-length
  - name: EGOV_STATE_LIST
    value: {{ index .Values "global" "schema" | quote }}
  {{- end }}        