# Common Labels
labels:
  app: "boundary-service"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "boundary-service"

initContainers:
  dbMigration:
    enabled: true
    schemaTable: "boundary_service_schema"
    image:
      repository: "boundary-service-db"

# Container Configs
image:
  repository: "boundary-service"
#replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/boundary-service/health"
  readinessProbePath: "/boundary-service/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx512m -Xms512m"
java-args: "-Dspring.profiles.active=monitoring"
kafka-topics-create-boundary: "create-boundary-entity"
kafka-topics-update-boundary: "update-boundary-entity"
kafka-topics-create-boundary-hierarchy: "save-boundary-hierarchy-definition"
kafka-topics-update-boundary-hierarchy: "update-boundary-hierarchy-definition"
kafka-topics-create-boundary-relationship: "save-boundary-relationship"
kafka-topics-update-boundary-relationship: "update-boundary-relationship"

memory_requests: "256Mi"
memory_limits: "512Mi"
cpu_limits: "20m"
cpu_requests: "10m"

# Additional Container Envs
env: |
  - name: SERVER_CONTEXT_PATH
    value: /boundary-service
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: boundary-service
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  {{- if index .Values "global" "serializers-timezone-in-ist" }}
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
  {{- end }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  - name: KAFKA_TOPICS_CREATE_BOUNDARY
    value: {{ index .Values "kafka-topics-create-boundary" | quote }}
  - name: KAFKA_TOPICS_CREATE_BOUNDARY_HIERARCHY
    value: {{ index .Values "kafka-topics-create-boundary-hierarchy" | quote }}
  - name: KAFKA_TOPICS_CREATE_BOUNDARY_RELATIONSHIP
    value: {{ index .Values "kafka-topics-create-boundary-relationship" | quote }}
  - name: KAFKA_TOPICS_UPDATE_BOUNDARY_RELATIONSHIP
    value: {{ index .Values "kafka-topics-update-boundary-relationship" | quote }}
  - name: KAFKA_TOPICS_UPDATE_BOUNDARY
    value: {{ index .Values "kafka-topics-update-boundary" | quote }}
  - name: KAFKA_TOPICS_UPDATE_BOUNDARY_HIERARCHY
    value: {{ index .Values "kafka-topics-update-boundary-hierarchy" | quote }}
