{{- if index .Values "punjab-analysis-infra" "enabled" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ index .Values "punjab-analysis-infra" "serviceAccount" "name" }}
  namespace: {{ index .Values "punjab-analysis-infra" "namespace" }}
  labels:
    app: punjab-analysis
    component: airflow-worker
{{- end }}
