# Common Labels
labels:
  app: "ifix-master-data-service"
  group: "ifix"

namespace: ifix

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "ifix-master-data"

# Init container configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "ifix_master_data_service_schema"
    image:
      repository: "ifix-master-data-service-db"

# Container Configs
image:
  repository: "ifix-master-data-service"
replicas: "1"

appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

server-context-path: "/ifix-master-data"

# Additional Container Envs
env: |  
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: {{ index .Values "server-context-path" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SPRING_DATA_MONGODB_URI
    valueFrom:
      secretKeyRef:
        name: db
        key: mongo-db-authenticated-uri
  - name: SPRING_DATA_MONGODB_DATABASE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: mongo-db-name
  - name: IFIX_MASTER_GOVERNMENT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: ifix-master-data-service
  - name: MDMS_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: IFIX_MASTER_EXPENDITURE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: ifix-master-data-service
  - name: IFIX_DEPARTMENT_ENTITY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: ifix-department-entity-service
  - name: IFIX_MASTER_DEPARTMENT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: ifix-master-data-service           
