# Common Labels
labels:
  app: "expense-cronjob"
  group: "expense-cronjob"

cron:
  schedule: "0 */1 * * *"

# Container Configs
image:
  repository: "egovio/expense-cronjob"
  tag: "latest"

command: 
  - "python3"
  - "cronJobAPIConfig.py"
args: 
  - "daily"

# Additional Container Envs
env: |
  - name: JOB_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name                    
resources: |
  requests: {}
  
    