# Common Labels
labels:
  app: "egov-otp"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "otp"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_otp_schema"
    image:
      repository: "egov-otp-db"

# Container Configs
image:
  repository: "egov-otp"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/otp/health"
  readinessProbePath: "/otp/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"    
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: state-level-tenant-id
  {{- if index .Values "cluster-configs" "configmaps" "egov-config" "data" "is-environment-central-instance" }}        
  - name: IS_ENVIRONMENT_CENTRAL_INSTANCE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: is-environment-central-instance
  - name: STATE_LEVEL_TENANTID_LENGTH
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: state-level-tenantid-length
  - name: EGOV_STATE_LIST
    value: {{ index .Values "global" "schema" | quote }}
  {{- end }}        