labels:
  app: "postgres"
  group: "db"
namespace: mgramseva

image:
  repository: "docker.io/postgres"
  tag: "9.6"
replicas: "1"
httpPort: 5432

resources: |
  requests:
    cpu: 100m
    memory: 256Mi

tracing-enabled: false

env: |
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name:  POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: POSTGRES_DB
    value: {{ default "" .Values.postgresDatabase | quote }}
extraVolumeMounts: |
  - name: postgres-volume
    mountPath: /var/lib/postgresql/data
extraVolumes: |
  - name: postgres-volume
  {{- if eq .Values.global.setup "quickstart" }} 
    persistentVolumeClaim:
      claimName: pvc-postgres
  {{- end}}    


postgresDatabase: egov_ms      
