{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: "v1"
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-data
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
{{- else }}
  namespace: {{ .Values.namespace }}
{{- end }}
  labels:
    app: {{ .Values.labels.app }}
    group: {{ .Values.labels.group }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.dataDirSize | quote }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  volumeMode: {{ .Values.persistence.volumeMode | quote }}
  volumeName: {{ .Chart.Name }}-data
  {{- end }}
