# Common Labels
labels:
  app: "project"
  group: "core"

namespace: staging

hpa:
  enabled: true

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "project"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "project_schema"
    image:
      repository: "project-db"
    env: |
      {{- if index .Values "project-ismultischema-enabled" }}        
      - name: SCHEMA_NAME
        value: {{ index .Values "project-schemas" | quote }}
      {{- end }}
      - name: "DB_URL"
        valueFrom: 
          configMapKeyRef: 
            name: egov-config
            key: db-url-works
      - name: "SCHEMA_TABLE"
        value: {{ .Values.initContainers.dbMigration.schemaTable | quote }}              
      - name: "FLYWAY_USER"
        valueFrom: 
          secretKeyRef: 
            name: db
            key: flyway-username
      - name: "FLYWAY_PASSWORD"
        valueFrom:
          secretKeyRef: 
            name: db
            key: flyway-password
      - name: "FLYWAY_LOCATIONS"
        valueFrom: 
          configMapKeyRef: 
            name: egov-config
            key: flyway-locations  
      {{- if index .Values.global "is-environment-central-instance" }}        
      - name: IS_ENVIRONMENT_CENTRAL_INSTANCE
        valueFrom:
          configMapKeyRef:
            name: egov-config
            key: is-environment-central-instance
      - name: STATE_LEVEL_TENANTID_LENGTH
        valueFrom:
          configMapKeyRef:
            name: egov-config
            key: state-level-tenantid-length
      {{- end }}  



# Container Configs
image:
  repository: "project"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/project/health"
  readinessProbePath: "/project/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: SERVER_CONTEXT_PATH
    value: /project
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /project 
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_BOUNDARY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-boundary
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: EGOV_LOCATION_CONTEXT_PATH
    value: "/egov-location/location/v11"
  - name: EGOV_LOCATION_ENDPOINT
    value: "/boundarys/_search"      
  - name: SPRING_REDIS_HOST
    value: redis.backbone
  - name: SPRING_REDIS_PORT
    value: "6379"
  - name: SPRING_CACHE_TYPE
    value: "redis"
  - name: SPRING_CACHE_REDIS_TIME-TO-LIVE
    value: "60"
  - name: SPRING_CACHE_AUTOEXPIRY
    value: "true"
  - name: PROJECT_ATTENDANCE_FEATURE_ENABLED
    value: "false"
  - name: PROJECT.MANAGEMENT.SYSTEM.KAFKA.CREATE.TOPIC
    value: "save-project"
  - name: PROJECT.MANAGEMENT.SYSTEM.KAFKA.UPDATE.TOPIC
    value: "update-project"
  {{- if index .Values "project-default-offset" }}
  - name: PROJECT.DEFAULT.OFFSET
    value: {{ index .Values "project-default-offset" | quote }} 
  {{- end }}
  {{- if index .Values "project-default-limit" }}
  - name: PROJECT.DEFAULT.LIMIT
    value: {{ index .Values "project-default-limit" | quote }} 
  {{- end }}
  {{- if index .Values "project-search-max-limit" }}
  - name: PROJECT.SEARCH.MAX.LIMIT
    value: {{ index .Values "project-search-max-limit" | quote }} 
  {{- end }}
  {{- if index .Values "project-mdms-module" }}
  - name: PROJECT_MDMS_MODULE
    value: {{ index .Values "project-mdms-module" | quote }} 
  {{- end }}
  {{- if index .Values "egov-location-hierarchy-type" }}
  - name: EGOV_LOCATION_HIERARCHY_TYPE
    value: {{ index .Values "egov-location-hierarchy-type" | quote }} 
  {{- end }}
