apiVersion: v2
name: digit-user-preferences-service
description: User preferences service for storing notification consent and language settings
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: common
  version: 0.0.5
  repository: file://../../common
