# Common Labels
labels:
  app: "egov-notification-sms"
  group: "core"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "egovio/egov-notification-sms"
replicas: "1"
appType: "java-spring"
tracing-enabled: true
sms-provider-url: "https://msdgweb.mgov.gov.in/esms/sendsmsrequest"
sms-sender: "egov"
sms-sender-requesttype: "POST"
sms-extra-req-params: "smsservicetype=unicodemsg"
heap: "-Xmx192m -Xms192m"
java-args: ""
secure-key: true

# Additional Container Envs
env: |
  - name: KAFKA_TOPICS_NOTIFICATION_SMS_NAME
    value: egov.core.notification.sms
  - name: KAFKA_TOPICS_NOTIFICATION_SMS_ID
    value: egov.core.notification.sms
  - name: KAFKA_TOPICS_NOTIFICATION_SMS_GROUP
    value: egov.core.notification.sms
  - name: SMS_PROVIDER_URL
    value: {{ index .Values "sms-provider-url" | quote }}
  - name: SMS_SENDER_USERNAME
    valueFrom:
      secretKeyRef:
        name: egov-notification-sms
        key: username
  - name: SMS_SENDER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: egov-notification-sms
        key: password
  {{- if index .Values "secure-key" }}
  - name: SMS_SENDER_SECURE_KEY
    valueFrom:
      secretKeyRef:
        name: egov-notification-sms
        key: secure-key        
  {{- end }}
  - name: SMS_ENABLED
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: sms-enabled
  - name: SMS_SENDER
    value: {{ index .Values "sms-sender" | quote }}
  - name: SMS_SENDER_REQUESTTYPE
    value: {{ index .Values "sms-sender-requesttype" | quote }}
  {{- if index .Values "sms-custom-config" }}
  - name: SMS_SENDER_REQ_PARAM_NAME
    value: "senderid"
  - name: SMS_SENDER_USERNAME_REQ_PARAM_NAME
    value: "username"
  - name: SMS_SENDER_PASSWORD_REQ_PARAM_NAME
    value: "password"
  - name: SMS_DESTINATION_MOBILE_REQ_PARAM_NAME
    value: "mobileno"
  - name: SMS_TYPE_REQ_PARAM_NAME  
    value: "smsservicetype"       
  - name: SMS_MESSAGE_REQ_PARAM_NAME
    value: "content"
  - name: "SMS_EXTRA_REQ_PARAMS"
    value: {{ index .Values "sms-extra-req-params" | quote }}
  - name: SMS_VERIFY_RESPONSE
    value: "true"
  - name: SMS_VERIFY_RESPONSECONTAINS
    value: "Message submitted successfully"
  - name: SMS_VERIFY_SSL
    value: "false"
  - name: SMS_URL_DONT_ENCODE_URL
    value: "true"
  - name: SMS_ERROR_CODES
    value: "401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418"  
  {{- end }}
  - name: SMS_SPICEDIGITAL_PROVIDER_URL
    value: {{ index .Values "sms-provider-url" | quote }}
  - name: SMS_SPICEDIGITAL_SENDER_USERNAME
    valueFrom:
      secretKeyRef:
        name: egov-notification-sms
        key: username
  - name: SMS_SPICEDIGITAL_SENDER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: egov-notification-sms
        key: password
  - name: LOGGING_LEVEL_org.egov.tracer.kafka    
    value: "DEBUG"              
  - name: SMS_SPICEDIGITAL_SENDER    
    value: {{ index .Values "sms-sender" | quote }}
  - name: SMS_GATEWAY_TO_USE
    value: "MSDG"          
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
