# Common Labels
labels:
  app: "egov-workflow"
  group: "core"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_workflow_schema"
    image:
      repository: "egov-workflow-db"

# Container Configs
image:
  repository: "egov-workflow"
replicas: "1"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx128m -Xms128m"

# Additional Container Envs
env: |
  - name: EGOV_SERVICES_BOUNDARY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: EGOV_SERVICES_PGRREST_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: pgr-rest
  - name: EGOV_SERVICES_HRMASTERS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: hr-masters
  - name: EGOV_SERVICES_HREMPLOYEE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: hr-employee
  - name: EGOV_SERVICES_COMMONMASTERS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-common-masters
  - name: SERVER_PORT
    value: "8080"
  - name: USER_SERVICE_URL
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user-egov
  - name: EGOV_SERVICES_PGRMASTER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: pgr-master
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
