# Common Labels
labels:
  app: "turn-io-adapter"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  namespace: "upyog"
  context: "turn-io-adapter"

# Init Containers Configs


# Container Configs
image:
  repository: "turn-io-adapter"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/turn-io-adapter/health"
  readinessProbePath: "/turn-io-adapter/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx384m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"

# Additional Container Envs
env: |
  - name: EGOV_PGR_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: rainmaker-pgr
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_URL_SHORTNER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-url-shortening
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true"
  {{- end }}
