{{- with index .Values "cluster-configs" "configmaps" "egov-service-host" }}
{{- if .data }}
---
{{- range $ns := .namespace }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ index $.Values "cluster-configs" "configmaps" "egov-service-host" "name" }}
  namespace: {{ $ns }}
data:
{{- range $key, $value := index $.Values "cluster-configs" "configmaps" "egov-service-host" "data" }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
