# Common Labels
labels:
  app: "program-service"
  group: "ifix"

namespace: ifix

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "program-service"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "program_service_schema"
    image:
      repository: "program-service-db"

# Container Configs
image:
  repository: "program-service"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/program-service/health"
  readinessProbePath: "/program-service/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /program-service
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: "program"
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
  {{- if index .Values "config-domain" }}
  - name: CONFIG_DOMAIN
    value: {{ index .Values "config-domain" | quote }} 
  {{- end }}
  - name: CONFIG_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  {{- if index .Values "config-idgen-idname" }}
  - name: CONFIG_IDGEN_IDNAME
    value: {{ index .Values "config-idgen-idname" | quote }} 
  {{- end }}

