cluster-configs:
    secrets:
        #ENC[AES256_GCM,data:ljLA+yCaUNbJk4cSYvujtsTxXEC4GpFvjN+q/Tk2am97W8A=,iv:2LLCps9Q6q3/l2Gdp0G9DWb2N0Afa+jKAj9PjkT0JGA=,tag:H2QKAYzLbQquGrqPzPCXyg==,type:comment]
        db:
            username: ENC[AES256_GCM,data:bbuQi9QbzcwBB40tJmnB,iv:HA+D8vcg4ydnvVyITsHXW/8PdWrcQXHu996IX3n3xWU=,tag:9P1c8eV1q1AvwFzTjUWGwQ==,type:str]
            #ENC[AES256_GCM,data:RH04ykDfRCbiBDFqH9+ZJQlBO5VAfpuzCUIKC+DVSA==,iv:6b6W379rVgqfxylA2h60D6/pzgl8ayxyrjVBRSKs6ww=,tag:n4ufPMZAgHp/wPX5WMCX5Q==,type:comment]
            password: ENC[AES256_GCM,data:TJFzdP9Bylo6CHvvJjtq/7ahU3FV,iv:CE9yB7m1sEQGLUf+3C3uXkEzjWPi9Nk/7E06BdRCcuA=,tag:wki7NSWklWL3M3GYuC5FHQ==,type:str]
            flywayUsername: ENC[AES256_GCM,data:fVRd8LKEz6X2O17QIStv,iv:O9EqPIgXpCD9iBVlgdrPuXSqalxLnfoQI5qB1iLFRXM=,tag:xA6TEms42zl18a5ECc2Svg==,type:str]
            #ENC[AES256_GCM,data:RH04ykDfRCbiBDFqH9+ZJQlBO5VAfpuzCUIKC+DVSA==,iv:6b6W379rVgqfxylA2h60D6/pzgl8ayxyrjVBRSKs6ww=,tag:n4ufPMZAgHp/wPX5WMCX5Q==,type:comment]
            flywayPassword: ENC[AES256_GCM,data:B60OUBc1p92be3MGatyZn4nQEN+G,iv:fKZgtvbh9Sp0FEsSPIcucJ6+SRytI9CkEm8f+5zMz/g=,tag:OKZaHIor2Dsp18iBoL8VIQ==,type:str]
        #ENC[AES256_GCM,data:QQ5jj0VufT1ZBVUIpoYmpS4jJfsh7bhnihlfBBRzRMnU+lKltsNhttEUfROmx0dDzmOaua4YTt39o3cTV78=,iv:V7FyQOnAvKyBd10PO+4pKhLR9R7W0wpOSVaNWeHhGjw=,tag:3frpIZMbQO0hCYTEBSRuqw==,type:comment]
        egov-notification-sms:
            username: ENC[AES256_GCM,data:GfB0bg==,iv:ekQiGD3W4nCOIYhnnky9kcK7zN12Zj3/bYTsZmI7oBU=,tag:ottPJGm7SAPSCKKYgftN4w==,type:str]
            password: ENC[AES256_GCM,data:8jflzA==,iv:SLsSurdH0xWFDrb6mGO9e1Ca/kvg4AxgFEh2VH4jn/g=,tag:U4RzoPoA0QGmlFO27D3c4g==,type:str]
        #ENC[AES256_GCM,data:1ALJKuvRGEi+uUwIp8RqMgAxj3vKzf8snGQ9qPc33PHExzt1ORI5d0sOfxZUkxXL+YP2IA==,iv:7bB3hrYvll+amc+BCGJIElnP3IqseV4ck0EGTPHuqgM=,tag:ZnX8c0+HIngMV69isgsm/Q==,type:comment]
        egov-pg-service:
            axis-merchant-id: ENC[AES256_GCM,data:Le3VQg==,iv:V3Y0mwvNjjTrcNcC82uTS3nJeQTRtbSEGmd6/lPk3Ws=,tag:3dE9rd1bQR/tdqs/WCYK4A==,type:str]
            axis-merchant-secret-key: ENC[AES256_GCM,data:jv3P+g==,iv:brxgqr70361ZCV6OMrUepfE9UquKZ1eIDugWE1mcRM4=,tag:AMiEyPrqX0WJ0P14HmvFTg==,type:str]
            axis-merchant-user: ENC[AES256_GCM,data:7rgqRQ==,iv:kdMMri4duxTZ3Zmoz6uZYhf0e9WtgEiAHve7ZJAcm3s=,tag:G3ekuRCFJAl7I49DgR0/1A==,type:str]
            axis-merchant-pwd: ENC[AES256_GCM,data:g9T9nQ==,iv:MgnHPrXVm3vilmhqfzeLxhjUCCtHwfDIYvVZG2jJ8Aw=,tag:YidYbH2+t+uz4Ps50FxKQA==,type:str]
            axis-merchant-access-code: ENC[AES256_GCM,data:Rf+ZOw==,iv:kg2H+HXKtJ7L1aKTnGIKhMlpXcniwj9NPFarTpbesjI=,tag:noXDro1te9xm93Csw3f5kg==,type:str]
            payu-merchant-key: ENC[AES256_GCM,data:ZviS5g==,iv:UuI5LP/6Y3Gl7tb8Ew9NxHvtOCsues9GTIFeXJktQ7E=,tag:E2EcjDU6rpelZPxriVOmIA==,type:str]
            payu-merchant-salt: ENC[AES256_GCM,data:6jOerA==,iv:PbPp+8QOaGVyeYf0KbtWUEBLFn4vOOr3Yw4ffmIi2nY=,tag:9WiyldAE68GGkr7Y5lkatQ==,type:str]
        #ENC[AES256_GCM,data:pkFeKQBkCfrrvR1AELtqoB4S7fVYfrT+886wdC7hmfRFQl7b/bs/JJ/sR/2b3hGHca2ZAokk43YZbua4ncM=,iv:NMs3uuVMvzzLIWsJqz0sXR3nBEVYq/cWBN7x5ArkR5Y=,tag:XKnEEkZkOmCadLPQAduA/w==,type:comment]
        egov-notification-mail:
            mailsenderusername: ENC[AES256_GCM,data:MkzgmfnbG/r8,iv:ERl9L1iSLjF4R+wXtnB+8CyTCKgxtu9V0dQKVNMmtf4=,tag:c9Cm+eI+Wo64amADjJI5xg==,type:str]
            mailsenderpassword: ENC[AES256_GCM,data:nJ06xg==,iv:voQ6GGhuqI2AVg9JhnCE+/LeknszUSUng2LtsuRSGX8=,tag:tVVyeaADMVgRf/oPumhnWQ==,type:str]
        #ENC[AES256_GCM,data:qYFi9W5/ZDEuCjAdQenGfAPIJgt/zb/HXikS7A==,iv:sU7ev+RLwQbiyARhBjg08DsfoGW9Kf7isnUPI7+XAAM=,tag:t/zXj/oh7TIb2q7YTvlFHA==,type:comment]
        egov-si-microservice:
            si-microservice-user: ENC[AES256_GCM,data:0/41+A==,iv:U1jwCrkd/M0wUishUyJOTFWjlSqiRXhodBAcleO/G/k=,tag:ljiPIn0ZFsyYLwvuGPGE2g==,type:str]
            si-microservice-password: ENC[AES256_GCM,data:CM3e8g==,iv:VBWkpFTxpfkQZqJ7PkFf45rOnq5YzO+eshYXe0kOGyE=,tag:7Q5Y2Ip3/V3AA2YH8kfN7w==,type:str]
            mail-sender-password: ENC[AES256_GCM,data:bgYsFA==,iv:pi5YcGs+0ni6eyCmyGOKwRO6VOasS75jfIkJkJboLog=,tag:hg75zHhIFjDhqdRh/LpW3g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2
          created_at: "2026-02-06T10:18:29Z"
          enc: AQICAHjEvQaNWs0Zj/laHQzVyaV/OAacQ3AJGQojIvVJeuwcQgEMvKvFPi5GcN15sMCH4xi7AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5OOaoElqDzO8o0siAgEQgDv3aNq9WwTCs9LNxKpmZLui2ncoZQ4wBmNh58M6W/IS/ezr/zqd32ugkIBTljymyDFMYEhgHZjD0QBNXA==
          aws_profile: ""
    lastmodified: "2026-02-12T05:49:19Z"
    mac: ENC[AES256_GCM,data:a/ZUI6UHJC9Hk76Lg9qWVLVjtt0BD+Q6Iej39EjM/K/KfOepP3nW3wY8jDI6soQb/Ww44MeJYOb5fjwet74zwfrytljlD9X8NTjFUaUufb4tQwck6eUoaMA9AlNCECKL/oJlmro1CxwOkj4ycXiu92lop0/Zk0ItU+o0ly+TcuY=,iv:V78kFQqks+Qd0Ym8tuvwxiFboO5bSqlALELjfoEcSWo=,tag:7yOuUbQ2H/c7GQJPZ0kyWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
