cluster-configs:
    secrets:
        #ENC[AES256_GCM,data:qkalBUWpro+eZBbhImzcWR4HLbTGKBC2i6cTYCgk1TAYcds=,iv:oUS0O5XU4kAPYceT8OaI23a4wLYParNd9xQIYgo0reM=,tag:2OopacwvXof2CxgPiD7spQ==,type:comment]
        db:
            username: ENC[AES256_GCM,data:8eRrcY3/hMtEplI=,iv:NTJLWvqb74AiC3GHJ41U04wcSkkTmV4lkwCEJIR6MqE=,tag:7QrZVloX2tx+hTw6T0P0FQ==,type:str]
            #ENC[AES256_GCM,data:O7RrwZdodh1UgyIEkyAtIri17njqPdPmua50AuQTiw==,iv:3LeWpTLZ2txGoRioQIE6ftNVawQIdkbhIuZfKawQcgM=,tag:oFz2Zt+XGnlmxQGD5SIjvA==,type:comment]
            password: ENC[AES256_GCM,data:uWC4zEBDiR0J63ZPEdrNPA==,iv:HV2J3UA7J6q6x6Amt17yUnnLwBSS0oU9f0wU8AFreII=,tag:3huQZkpESzF8+XozHI2lIw==,type:str]
            flywayUsername: ENC[AES256_GCM,data:CzmSGdOMkaEZYck=,iv:WRHgeEYMd3F8cYjrS+QR1klMx9MkydQ3oBFcqiPbVLs=,tag:obqhGIMuuLSyArGaTHEHhg==,type:str]
            #ENC[AES256_GCM,data:O7RrwZdodh1UgyIEkyAtIri17njqPdPmua50AuQTiw==,iv:3LeWpTLZ2txGoRioQIE6ftNVawQIdkbhIuZfKawQcgM=,tag:oFz2Zt+XGnlmxQGD5SIjvA==,type:comment]
            flywayPassword: ENC[AES256_GCM,data:QhGX4zSzsmpS8aHkPRU0ow==,iv:dzHK1QNMKrAuZh6fkbsDfjYdXXEPYSAXmE6KIsfHsRw=,tag:DogDKCTL7RkVkAt4JXUzrA==,type:str]
        #ENC[AES256_GCM,data:e4vQQYH47rx0vCk/GRUN+ddcNFGswqEf1G2re1HRni8m6H2GveFfOdanFoXQV1HtFiiwVySALwLxfwrmRYM=,iv:KaNx9JlScTyP8SnFU4vGc5V0/vzEanaVz2mMQdr3KrA=,tag:lHtjUc5ySzhiMk6imouoUg==,type:comment]
        egov-notification-sms:
            username: ENC[AES256_GCM,data:5b7R4Q==,iv:JRH+CjUqRaZcovGArKI/Oq6RT6wVSQfjYNhi+qMJmZE=,tag:p4I1xuIT6LB0/ZrhF2qLkQ==,type:str]
            password: ENC[AES256_GCM,data:+PC6ew==,iv:2JzpGz3Wacu91CrIBHgRnFzrfWDeDAnu3ZUbDVHzV1M=,tag:Bx7bAAo5N66ZJRFv79yxiQ==,type:str]
        #ENC[AES256_GCM,data:UCvJD+bE/nzq+v+GqlJTDPmwBORPaiIFmEqdVY8FLWEi1N8FPr/WXnThgoEi2kCnqipdHg==,iv:IIetfn/MN5N8/MHNlfYloDJFCvkUFDZbUagb5bLZwTY=,tag:1dCrLn3WPFznGLGBmbsxqA==,type:comment]
        egov-pg-service:
            axis-merchant-id: ENC[AES256_GCM,data:m7TdfA==,iv:iuuhKOTb1gtgAfjrHLkfL7myMnTS1d9WHEtgSfA1Bk8=,tag:PZ7mzAJjsbaFpsy13pu8Lw==,type:str]
            axis-merchant-secret-key: ENC[AES256_GCM,data:vCos3Q==,iv:/j7eSxeWrw4HDGtnQjd9G7BreOHbpj/GFFlZ3EHyGD0=,tag:h93yWn6YYi1T1EMsgvcXxA==,type:str]
            axis-merchant-user: ENC[AES256_GCM,data:W4ZP+A==,iv:KnfCo1Zg2fH8MC7TU+zHc+fO5oPx4OxOjDfX33YGqgw=,tag:QkENhoaUo6UFzrjAAeaysw==,type:str]
            axis-merchant-pwd: ENC[AES256_GCM,data:JfxFIw==,iv:cg/xO0ifQuB5yP4eJWP09VQ3siTGudpzA2AE0HGU3Fc=,tag:9sUzv9itO0gJJpuMSr5GRg==,type:str]
            axis-merchant-access-code: ENC[AES256_GCM,data:Y3FTiA==,iv:mN+zsNQCYBQKPSZBZ/Kg08appxFT4tHpFOaLpu50lZ4=,tag:yxCjD5APVxXY+494FDS+/A==,type:str]
            payu-merchant-key: ENC[AES256_GCM,data:Jr6KCA==,iv:Flxnuv2pzzr+oFyjacDdbqeonSFhJsEzGfZyB6jSpik=,tag:0s22cNX0G6nFVoxW60o1Cw==,type:str]
            payu-merchant-salt: ENC[AES256_GCM,data:viJr5w==,iv:4jIyqSrci5ZzenlqaJT63b3drkRXZXUlm7wRb7GG2Ts=,tag:AuPHhgBK9pFzAE+v12d75A==,type:str]
        #ENC[AES256_GCM,data:zSOYEm5sWoHTWsJaytpZJpIxhtPweUPjcKoiYtqGRkrh67Tts+kwmsqgrcd9rb8jmMa4J1XkU/4jR0Bnsug=,iv:s7c9GmarMK/zvCmF89FlxxqjoGVO6S7bwvQqdDT9izM=,tag:xry7IR/zV577h31BpTYuQg==,type:comment]
        egov-notification-mail:
            mailsenderusername: ENC[AES256_GCM,data:1mGTYZ36cOFU,iv:CLV1FgkWfvJz4acGs8xGJzLcCIXgPt+8LCsxnRxA/GY=,tag:W8Zmh8BswktCOLaAQrxzaQ==,type:str]
            mailsenderpassword: ENC[AES256_GCM,data:gx0gUw==,iv:GOZTdiiMnNnb9JqFaHxSut/XU/n5j89qLKDbKxwDnBg=,tag:gQ9hLiEWo/+ersScz7wOwA==,type:str]
        #ENC[AES256_GCM,data:0jwwbW0X6SRbbit+uHZ7t5LkPs76LCbMKyDUjw==,iv:SWISI5lvAli8oSwTfonwBuJPC68h8nUKbbcoSOiO+lo=,tag:KZ16VGSlWZqA6saqL/Glmg==,type:comment]
        egov-si-microservice:
            si-microservice-user: ENC[AES256_GCM,data:631FMQ==,iv:HZXxCmtPHT6W+GX42WpE+K2+WracwuN0bsE/R2Ny66Q=,tag:fqHzTzB7qtknnNfPe/l4hg==,type:str]
            si-microservice-password: ENC[AES256_GCM,data:CbJ1GA==,iv:nGx7ELEKV6mnPE4KYFB5T4KZoa2G9p8sDTZBUdIft2s=,tag:m9QTD9IXB9zX4nkxAwj1dg==,type:str]
            mail-sender-password: ENC[AES256_GCM,data:Y3iCtA==,iv:P3hbA88z7KqD1M7UjFWJ092A7XzeCdGtMwskYW+gC8c=,tag:NARXC/IuOtyMPCWpzHbilA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2
          created_at: "2026-02-06T10:18:21Z"
          enc: AQICAHjEvQaNWs0Zj/laHQzVyaV/OAacQ3AJGQojIvVJeuwcQgGM0zw+FwOxyrF6i1CiaMdEAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFaMz7LkaCqGprpBOAgEQgDuMUvRUs53HlqEJOofWoCjG6mb4d6MIyBIE2A0oilb37KLHpXMwUmwo4kq3Ap/4GKnVHwbJe7xuZxVATA==
          aws_profile: ""
    lastmodified: "2026-02-17T06:25:02Z"
    mac: ENC[AES256_GCM,data:lB41naI8O1JfiPikLPYriZYLJ30YGnNExHuTWM+FuZNSDcNm+w4ZgMvVqfWGJaRTLKpe129Kx8hi5WPalQ5de5qZax9+qyX0TXupIwU1HIBupLLsH/HooXJ1dnSuT41ZioSTk468sVofHGDUNPIeg81WpM39LRYRoJTmiMxyo9Q=,iv:UMm0q79PW4pmOiyDB6CKMsKvXkm8nWb9bONhgkkGTHk=,tag:SEgBfJze9GYeiiok4LCW7g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
