cluster-configs:
    secrets:
        db:
            username: ENC[AES256_GCM,data:ej6rw0sY0IbsrA==,iv:JTPS7Y8hf1QD5TVHb2xFok3vI+pdT2dBQDxY/U7FmmU=,tag:9Qq1Qh2PFWfWcEKFXp4nBg==,type:str]
            password: ENC[AES256_GCM,data:ofy7mdAYN9/WYvWbuKT1NA==,iv:hzLGwom4+abebRWCHi6HFoUIKe4TXKYWupsUfC1kXzw=,tag:TE8yzhdpSYu1Rydf/3CQ0w==,type:str]
            flywayUsername: ENC[AES256_GCM,data:/kHSwbPJmYoqmg==,iv:M6T0SP0yzW/aUHUUp7lC+XwmOai3xscihuTUUOuCHxw=,tag:Ifxy7ZY7taXcyNAj2O48PA==,type:str]
            flywayPassword: ENC[AES256_GCM,data:NpOu/JClmmV2fWGbLdkOYg==,iv:kqgiVZ2EkpVpOryuWqcChzFktUfLcobxqFKFe6JDsWc=,tag:007e1E/Eiba+fEnv0d/vlg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2
          created_at: "2023-10-09T10:33:39Z"
          enc: AQICAHjEvQaNWs0Zj/laHQzVyaV/OAacQ3AJGQojIvVJeuwcQgEfIJkrwmm8m0wk/ND2O3LIAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMCK6ZOZGq9fjKSIF2AgEQgDv/xh0ZCHo2mT4A++2zNgW/DMjbjWy5MpFXW1lggnX6ZFKRpzd+pVhH08OIAXCDW4gOXVLuRcXK6ROmEA==
          aws_profile: ""
    lastmodified: "2026-02-06T12:23:21Z"
    mac: ENC[AES256_GCM,data:z6uwhN/umijIbEeyPePd6AGK1IS2ZmBW9V77pkSIlswxhN7FJNJkumOb5NIgOpHxjIEu+nRXQsRj+w2SFiw5qWf7iGgr6DWm7Mn0YHBe2Qd7sssRNZSyVVWHJjrK0fQdRpWbDxVlY/48ofg9mtUBD+PvS8gcWgo+yOF/kU7OyKA=,iv:j9Kv/D8FNvQ9cQDQDWehC+2tAvzyY05oUBRfTd4heb8=,tag:S6yDYOSWmlzNsEAXQ+/xbw==,type:str]
    pgp:
        - created_at: "2023-10-09T10:33:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+gtFIQvidpKAQf/bebufq+I7lxP3wIQssZ5Lyb7cS505VhmHGFClSbHTEgB
            ktMBmyNi6z2/rc0tG/l/yYc0ZE5VzrS07LA4HgN4wroy/T9DEZYuRB0TS9NORi2W
            Cja3n6IxvFZXQKSrunVX+hPHXBBATzvgWZDs7I3BB1BXlJVv8STED+pk8KxFWAH5
            3Xt4qD//yT6nDfAoFaKAJW3RpwlFCYU/Dh/OZDrHRRUHPES0WWn9QoSCnLghGDrj
            W1Tna50PAUZAgK8j5uvgZNb5ykfRSfvP0noRwdPq65OyZ82TIW7JN/pOgu4rWhle
            ho+RbM0RozQjLDd9nhxQBBPAbScAhe6TvtJCCH2EJNJeAbDt2i8giyyUYyJaq4N0
            MVUyoyH/UOGcSUhxcv+By/dunFTuxvOChPP1IusKQB4CFUBSNrl1cnMkOEAED1gL
            nJTJMa6Wvh9KpvP17gO+UbTlhMmjQAd0N/ZF4FM3Lw==
            =gDUX
            -----END PGP MESSAGE-----
          fp: B9FF61E01273EDF7DE298B52F4D6BD77E5C66196
    unencrypted_suffix: _unencrypted
    version: 3.10.2
