global:
  domain:
    unified-demo-new.digit.org ## Add your Domain Name "Eg: site.mydomain.com" Do not use the dummy domain
  setup: fullsetup
  tracing-enabled: true
  namespace: studio
  nodepool:
    nodeAffinity: false
    selector: studio-ng
    toleration: studio-ng

cluster-configs:
  secrets:
    egov-si-microservice:
      namespace: studio
      name: egov-si-microservice
    egov-pg-service:
      namespace: studio
      name: egov-pg-service
    egov-notification-mail:
      namespace: studio
      name: egov-notification-mail
    egov-notification-sms:
      namespace: studio
      name: egov-notification-sms
    db: 
      namespace: studio
  namespaces:
    create: false
    values: [ studio ]
  networkpolicy:
    namespaces:
      [ studio ]

  rbac:
    - role: user
      namespaces: [ studio ]
    - role: admin
      namespaces: [ studio ]
      
  configmaps:
    egov-config:
      namespace: [ studio ]
      data:
        db-host: "unified-demo-db.czvokiourya9.ap-south-1.rds.amazonaws.com"
        db-name: "unifieddemodb"
        db-url: "jdbc:postgresql://unified-demo-db.czvokiourya9.ap-south-1.rds.amazonaws.com:5432/unifieddemodb?currentSchema=pg"
        db-url-works: "jdbc:postgresql://unified-demo-db.czvokiourya9.ap-south-1.rds.amazonaws.com:5432/unifieddemodb"
        bpa-db-url: "jdbc:postgresql://unified-demo-db.czvokiourya9.ap-south-1.rds.amazonaws.com:5432/centralinstanceedcr"
        erp-db-url: "jdbc:postgresql://unified-demo-db.czvokiourya9.ap-south-1.rds.amazonaws.com:5432/centralinstancefinance"
        domain: "unified-demo.digit.org"
        egov-services-fqdn-name: "https://unified-demo.digit.org/"
        state-level-tenantid-length: "1"
        state-schema-index-position-tenantid: "0"
        is-environment-central-instance: "true"
        egov-state-level-tenant-id: "pg"
        state-level-tenant-id: "pg"
        es-host: "elasticsearch-data.backbone"
        es-indexer-host: "http://elasticsearch-data.backbone:9200/"
        flyway-locations: "filesystem:/flyway/sql,filesystem:/flyway/seed,filesystem:/flyway/qa"
        kafka-brokers: "release-name-kafka-controller-headless.backbone:9092"
        kafka-infra-brokers: "release-name-kafka-controller-headless.backbone:9092"
        logging-level-jdbc: "debug"
        mobile-validation-workaround: "true"
        s3-assets-bucket: "(in-central-instance-assets|egov-central-instance-assets)"
        serializers-timezone-in-ist: "true"
        server-tomcat-max-threads: "50"
        server-tomcat-max-connections: "500"
        sms-enabled: "true"
        spring-datasource-tomcat-initialSize: "2"
        spring-datasource-tomcat-max-active: "6"
        spring-datasource-tomcat-min-idle: "2"
        spring-jpa-show-sql: "true"
        tracer-errors-provideexceptionindetails: "true"
        timezone: "Asia/Kolkata"
        es-infra-host: elasticsearch-data-v1.es-cluster
        care-db-name: "care_db"
        care-db-port: "5432"
        central-level-tenant: "pg"
        egov-bnd-freedownload-tenants: "pg.testing"
        egov-bnd-live-citizen-tenants: "pg.testing"
        egov-internal-microservice-user-uuid: "e1f57dfe-35a0-494a-911d-22cd3f786612"

    egov-service-host:
      namespace: [ studio ]
      data:
        internal-gateway-scg: "http://internal-gateway-scg.egov:8080/"
        billing-service: "http://billing-service.egov:8080/"
        collection-services: "http://collection-services.egov:8080/"
        dashboard-analytics: http://dashboard-analytics.staging:8080/
        dashboard-ingest: http://dashboard-ingest.staging:8080/
        egov-common-masters: "http://internal-gateway-scg.egov:8080/"
        egf-masters: "http://egf-masters.staging:8080/"
        egf-master: "http://egf-master.staging:8080/"
        egf-instrument: "http://egf-instrument.staging:8080/"
        egf-voucher: "http://egf-voucher.staging:8080/"
        egov-enc-service: "http://egov-enc-service.egov:8080/"
        egov-accesscontrol: "http://internal-gateway-scg.egov:8080/"
        egov-user: "http://egov-user.egov:8080/"
        egov-user-egov: "http://egov-user.egov:8080/"
        egov-location: "http://egov-location.egov:8080/"
        egov-filestore: "http://egov-filestore.egov:8080/"
        egov-localization: "http://egov-localization.egov:8080/"
        egov-idgen: "http://egov-idgen.egov:8080/"
        egov-otp: "http://internal-gateway-scg.egov:8080/"
        egov-mdms-service: "http://egov-mdms-service.egov:8080/"
        mdms-v2: "http://mdms-v2.egov:8080/"
        egov-workflow: "http://internal-gateway-scg.egov:8080/"
        egov-workflow-v2: "http://egov-workflow-v2.egov:8080/"
        egov-searcher: "http://egov-searcher.egov:8080/"
        egov-indexer: "http://internal-gateway-scg.egov:8080/"
        egov-hrms: "http://egov-hrms.egov:8080/"
        pt-calculator: "http://pt-calculator.staging:8080/"
        pt-calculator-v2: "http://pt-calculator-v2.staging:8080/"
        pt-services-v2: "http://pt-services-v2.egov:8080/"
        property-services: "http://property-services.egov:8080/"
        pdf-service: "http://pdf-service.staging:8080/"
        report: "http://internal-gateway-scg.egov:8080/"
        tl-services: "http://tl-services.egov:8080/"
        tl-calculator: "http://tl-calculator.staging:8080/"
        user-otp: "http://user-otp.staging:8080/"
        egov-apportion-service: "http://internal-gateway-scg.egov:8080/"
        minio-url: "https://minio-uat.digit.org/"
        gateway: "http://internal-gateway-scg.egov:8080/"
        egov-url-shortening: "http://egov-url-shortening.egov:8080/"
        inbox: "http://inbox.staging:8080/"
        egov-pdf: "http://egov-pdf.egov:8080/"
        bpa-services: "http://bpa-services.egov:8080/"
        bpa-calculator: "http://internal-gateway-scg.egov:8080/"
        ws-calculator: "http://ws-calculator.staging:8080/"
        ws-services: "http://ws-services.egov:8080/"
        sw-services: "http://sw-services.egov:8080/"
        sw-calculator: "http://sw-calculator.staging:8080/"
        land-services: "http://internal-gateway-scg.egov:8080/"
        noc-services: "http://internal-gateway-scg.egov:8080/"
        egov-edcr: "http://egov-edcr.egov:8080/"
        firenoc-services: "http://internal-gateway-scg.egov:8080/"
        firenoc-calculator: "http://firenoc-calculator.staging:8080/"
        vehicle: "http://vehicle.egov:8080/"
        fsm-calculator: "http://fsm-calculator.staging:8080/"
        mdms-service-v2: "http://mdms-v2.egov:8080/"
        fsm: "http://fsm.egov:8080/"
        egov-document-uploader: "http://internal-gateway-scg.egov:8080"
        egov-survey-services: "http://egov-survey-services.staging:8080"
        egov-user-event: "http://egov-user-event.staging:8080"
        pqm-service: "http://pqm-service.egov:8080"
        boundary-service: 'http://boundary-service.egov:8080/'
        household: "http://household.egov:8080/"

        egov-boundary: "http://boundary-service.egov:8080/"
        attendance-service: "http://attendance.staging:8080/"
        contract-service: "http://contracts.staging:8080/"
        muster-roll-service: "http://muster-roll.staging:8080/"
        project-management-system: "http://project.staging:8080/"
        estimate-service: "http://estimates.staging:8080/"
        organisation: "http://organisation.staging:8080/"
        bankaccounts: "http://bankaccounts.staging:8080/"
        expense-calculator: "http://expense-calculator.staging:8080/"
        expense: "http://expense.staging:8080/"
        works-management-service: "http://works-management-service.staging:8080/"
        individual: "http://individual.egov:8080/"
        works-pdf: "http://works-pdf.staging:8080/"
        ifms-jit: "https://uat.odishatreasury.gov.in"
        #ifms-jit: "https://www.odishatreasury.gov.in"
        ifms-adapter: "http://ifms-adapter.staging:8080/"
        sms-adapter: "http://sms-adapter.staging:8080/"

        audit-service: "http://audit-service.egov:8080/"
        data-sync-employee: "http://data-sync-employee:8080/"
        egov-common-workflows: "http://egov-common-workflows:8080/"
        location: "http://location:8080/"
        zuul: "http://zuul:8080/"
        measurement: "http://measurement-service.staging:8080/"
        es-client: https://elasticsearch-data-v8.es-upgrade:9200
        measurement-service: "http://measurement-service.staging:8080/"
        measurement-registry: "http://measurement-registry.staging:8080/"
        egov-mdms-service-v2: "http://mdms-v2.egov:8080/"
        bulk-upload: "http://bulk-upload.egov:8080/"
        mukta-services: "http://mukta-services.staging:8080/"
        program-service: "http://program-service-works.staging:8080/"
        digit-exchange: "http://digit-exchange-works.staging:8080/"
        mukta-ifix-adapter: "http://mukta-ifix-adapter.staging:8080/"
        ifix-program-service: "http://program-service.ifix:8080/"
        statements: "http://statements.staging:8080/"
        public-service: "http://public-service.studio:8080/"
        public-service-init: "http://public-service-init.studio:8080/"
        studio-individual: "http://studio-individual.studio:8080/"
        studio-service-request: "http://studio-service-request.studio:8080/"
        beneficiary-idgen: 'http://beneficiary-idgen.health:8080/'

        jmx-exporter-config:
          namespace: [ egov, studio ]



public-service:
  replicas: 1
  heap: '-Xmx256m -Xms256m'
  memory_limits: 512Mi
  mdms-search-enpoint: "mdms-v2/v1/_search"
  mdms-search-v2-endpoint: "mdms-v2/v2"
  mdms-v2-search-endpoint: "mdms-v2/v2/_search"
  mdms-v2-create-endpoint: "mdms-v2/v2/_create"
  mdms-service-host: "http://mdms-v2.egov:8080/"
  mdms-v2-update-endpoint: "mdms-v2/v2/_update"

public-service-init:
  replicas: 1
  heap: "-Xmx512m -Xms256m"
  memory_limits: 768Mi
  mdms-search-enpoint: "mdms-v2/v1/_search"
  mdms-search-v2-endpoint: "mdms-v2/v2"
  mdms-v2-search-endpoint: "mdms-v2/v2/_search"
  mdms-v2-create-endpoint: "mdms-v2/v2/_create"
  mdms-service-host: "http://mdms-v2.egov:8080/"
  mdms-v2-update-endpoint: "mdms-v2/v2/_update"

egov-pg-service:
  replicas: 0
  axis: true

inbox:
  replicas: 2
  service-map: '{"FSM":{"searchPath":"http://fsm.egov:8080/fsm/v1/_search","dataRoot":"fsm","applNosParam":"applicationNos","businessIdProperty":"applicationNo"},"FSM_POST_PAY_SERVICE":{"searchPath":"http://fsm.egov:8080/fsm/v1/_search","dataRoot":"fsm","applNosParam":"applicationNos","businessIdProperty":"applicationNo","applsStatusParam":"applicationStatus"},"FSM_VEHICLE_TRIP":{"searchPath":"http://vehicle.egov:8080/vehicle/trip/v1/_search","dataRoot":"vehicleTrip","applNosParam":"applicationNos","businessIdProperty":"applicationNo"},"PT.CREATE,PT.UPDATE,PT.MUTATION":{"searchPath":"http://property-services.egov:8080/property-services/property/_search","dataRoot":"Properties","applNosParam":"acknowldgementNumber","businessIdProperty":"acknowldgementNumber","applsStatusParam":"status"},"NewTL,DIRECTRENEWAL,EDITRENEWAL":{"searchPath":"http://tl-services.egov:8080/tl-services/v1/_search","dataRoot":"Licenses","applNosParam":"applicationNumber","businessIdProperty":"applicationNumber","applsStatusParam":"status"},"BPA_LOW,BPA,BPA_OC,BPA_HIGH":{"searchPath":"http://bpa-services.egov:8080/bpa-services/v1/bpa/_search","dataRoot":"BPA","applNosParam":"applicationNo","businessIdProperty":"applicationNo","applsStatusParam":"status"},"ARCHITECT,ENGINEER,STRUCTURALENGINEER,BUILDER,SUPERVISOR,TOWNPLANNER":{"searchPath":"http://tl-services.egov:8080/tl-services/v1/BPAREG/_search","dataRoot":"Licenses","applNosParam":"applicationNumber","businessIdProperty":"applicationNumber","applsStatusParam":"status"},"FIRE_NOC_SRV,FIRE_NOC_OFFLINE,AIRPORT_NOC_OFFLINE,AIRPORT_NOC_SRV":{"searchPath":"http://noc-services.egov:8080/noc-services/v1/noc/_search","dataRoot":"Noc","applNosParam":"applicationNo","businessIdProperty":"applicationNo","applsStatusParam":"status"},"NewWS1,ModifyWSConnection,DisconnectWSConnection":{"searchPath":"http://ws-services.egov:8080/ws-services/wc/_search","dataRoot":"WaterConnection","applNosParam":"applicationNumber","businessIdProperty":"applicationNo","applsStatusParam":"applicationStatus"},"NewSW1,ModifySWConnection,DisconnectSWConnection":{"searchPath":"http://sw-services.egov:8080/sw-services/swc/_search","dataRoot":"SewerageConnections","applNosParam":"applicationNumber","businessIdProperty":"applicationNo","applsStatusParam":"applicationStatus"},"WS.AMENDMENT,SW.AMENDMENT":{"searchPath":"http://billing-service.egov:8080/billing-service/amendment/_search","dataRoot":"Amendments","applNosParam":"consumerCode","businessIdProperty":"amendmentId","applsStatusParam":"status"}}'
  bs-service-map: '{"WS":{"searchPath":"http://ws-services.egov:8080/ws-services/wc/_search","dataRoot":"WaterConnection","consumerCodeParam":"connectionNumber"},"SW":{"searchPath":"http://sw-services.egov:8080/sw-services/swc/_search","dataRoot":"SewerageConnections","consumerCodeParam":"connectionNumber"}}'
  #W&S index names
  water-es-index: pg-water-services
  sewerage-es-index: pg-sewerage-services

egov-workflow-v2:
  logging-level: "DEBUG"
  java-args: -Dspring.profiles.active=monitoring
  heap: "-Xmx192m -Xms192m"
  workflow-statelevel: "true"
  wf-max-limit: "10000"

digit-studio:
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://egov-dev-assets.s3.ap-south-1.amazonaws.com/analytics/analytics.js type=text/javascript async></script>
      <script src=https://egov-demo-rainmaker.s3.ap-south-1.amazonaws.com/globalConfigsStudio.js type=text/javascript></script>';"