global:
   domain: unified-dev.digit.org ## Add your Domain Name "Eg: site.mydomain.com" Do not use the dummy domain
   setup: fullsetup
   namespace: fsm

cluster-configs:
  namespaces:  
    create: true
    values: [ fsm ]
      
  root-ingress:
    cert-issuer: letsencrypt-prod
  configmaps:
    egov-config:
      namespace: [ fsm ]
      data:
        db-host: unified-dev-db.czvokiourya9.ap-south-1.rds.amazonaws.com ## Add db-host name eg: egov-demo.database.azure.com
        db-name: unifieddevdb ## Add db-name
        db-schema: "fsm"
        db-url: jdbc:postgresql://unified-dev-db.czvokiourya9.ap-south-1.rds.amazonaws.com:5432/unifieddevdb?currentSchema=fsm ## example: jdbc:postgresql://egov-demo.postgres.database.azure.com:5432/egov_demo
        domain: "https://unified-dev.digit.org" ## Add your Domain Name    
        egov-services-fqdn-name: "https://unified-dev.digit.org/" ## Add your Domain Name
        
        egov-state-level-tenant-id: "pg" 
        s3-assets-bucket: "(pg-egov-assets|egov-playground-assets|egov-dev-assets)"
        flyway-locations: "filesystem:/flyway/sql,filesystem:/flyway/seed,filesystem:/flyway/qa"
        logging-level-jdbc: "DEBUG"
        mobile-validation-workaround: "true"
        serializers-timezone-in-ist: "true"
        server-tomcat-max-connections: "500"
        server-tomcat-max-threads: "10"
        sms-enabled: "true"
        spring-datasource-tomcat-initialSize: "1"
        spring-datasource-tomcat-max-active: "2"
        spring-jpa-show-sql: "true"
        timezone: Asia/Kolkata
        tracer-errors-provideexceptionindetails: "true"
        egov-bnd-freedownload-tenants: "pg.testing"
        egov-bnd-live-citizen-tenants: "pg.testing"

    egov-service-host:
      namespace: [ fsm ]
      data:
        impel-fsm-calculator: "http://impel-fsm-calculator.fsm:8080/"
        impel-fsm: "http://impel-fsm.fsm:8080/"
        vehicle: "http://vehicle.fsm:8080"
        vendor: "http://vendor.fsm:8080"
        inbox: "http://inbox.fsm:8080/"


impel-inbox:
  namespace: fsm
  memory_limits: 512Mi
  heap: "-Xmx512m -Xms256m"
  java-debug: true
  tracing-enabled: "true"  
  service-map : '{}'
  bs-service-map : '{}'  

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
egov-mdms-service:
  replicas: 1
  images:
    - egovio/egov-mdms-service
  mdms-path: "/work-dir/egov-mdms-data/data"
  initContainers:
    gitSync:
      repo: "git@github.com:egovernments/egov-mdms-data"   ##### Change repo url with Your fork Repo url
      branch: "UNIFIED-DEV"                                        ##### Change repo branch with Your fork Repo branch
  mdms-folder: "egov-mdms-data"
  masters-config-url: "file:///work-dir/egov-mdms-data/master-config.json"
  java-args: -Dspring.profiles.active=monitoring
  heap: "-Xmx256m -Xms256m"
  memory_limits: 512Mi

egov-indexer:
  heap: "-Xmx512m -Xms512m"
  memory_limits: "768Mi"
  initContainers:
    gitSync:
      repo: "git@github.com:egovernments/configs"        ##### Change repo url with Your fork Repo url
      branch: "UNIFIED-DEV"                                      ##### Change repo branch with Your fork Repo branch
  egov-indexer-yaml-repo-path: "file:///work-dir/configs/fsm/egov-indexer/egov-impel-vehicle.yaml,file:///work-dir/configs/fsm/egov-indexer/egov-impel-vendor.yaml,file:///work-dir/configs/fsm/egov-indexer/egov-impel-fsm.yml,file:///work-dir/configs/fsm/egov-indexer/impel-fsm-inbox-indexer.yml,file:///work-dir/configs/egov-indexer/privacy-audit.yaml,file:///work-dir/configs/egov-indexer/billingservices-indexer.yml,file:///work-dir/configs/egov-indexer/collection-indexer.yml,file:///work-dir/configs/egov-indexer/egov-telemetry-indexer.yml,file:///work-dir/configs/egov-indexer/egov-uploader-indexer.yml,file:///work-dir/configs/egov-indexer/error-queue.yml,file:///work-dir/configs/egov-indexer/finance-rolloutadotpion-indexer.yml,file:///work-dir/configs/egov-indexer/payment-indexer.yml,file:///work-dir/configs/egov-indexer/pgr-services.yml,file:///work-dir/configs/egov-indexer/rainmaker-pgr-indexer.yml,file:///work-dir/configs/egov-indexer/rainmaker-pt-indexer.yml,file:///work-dir/configs/egov-indexer/rainmaker-tl-indexer.yml,file:///work-dir/configs/egov-indexer/chatbot-telemetry.yaml,file:///work-dir/configs/egov-indexer/water-service.yml,file:///work-dir/configs/egov-indexer/water-services-meter.yml,file:///work-dir/configs/egov-indexer/sewerage-service.yml,file:///work-dir/configs/egov-indexer/property-services.yml,file:///work-dir/configs/egov-indexer/chatbot-telemetry-v2.yaml,file:///work-dir/configs/egov-indexer/egov-vehicle.yaml,file:///work-dir/configs/egov-indexer/egov-vendor.yaml,file:///work-dir/configs/egov-indexer/egov-url-shortening-indexer.yaml,file:///work-dir/configs/egov-indexer/fire-noc-service.yml,file:///work-dir/configs/egov-indexer/egov-echallan.yml,file:///work-dir/configs/egov-indexer/egov-bpa-indexer.yml,file:///work-dir/configs/egov-indexer/edcr-indexer.yml,file:///work-dir/configs/egov-indexer/rainmaker-birth-indexer.yml,file:///work-dir/configs/egov-indexer/rainmaker-death-indexer.yml,file:///work-dir/configs/egov-indexer/ws-event-indexer.yml,file:///work-dir/configs/egov-indexer/egov-error-queue-indexer.yml,file:///work-dir/configs/egov-indexer/citizen-feedback-indexer.yml,file:///work-dir/configs/egov-indexer/egov-fsm.yml,file:///work-dir/configs/egov-indexer/fsm-inbox-indexer.yml,file:///work-dir/configs/works/egov-indexer/contractservices-indexer.yml,file:///work-dir/configs/works/egov-indexer/estimateservices-indexer.yml,file:///work-dir/configs/works/egov-indexer/expensebill-indexer.yml,file:///work-dir/configs/works/egov-indexer/individual-indexer.yml,file:///work-dir/configs/works/egov-indexer/musterservices-indexer.yml,file:///work-dir/configs/works/egov-indexer/organisationservices-indexer.yml,file:///work-dir/configs/works/egov-indexer/project-indexer.yml,file:///work-dir/configs/egov-indexer/product-indexer.yml,file:///work-dir/configs/egov-indexer/individual-indexer.yml,file:///work-dir/configs/egov-indexer/household-indexer.yml,file:///work-dir/configs/egov-indexer/project-task-indexer.yml,file:///work-dir/configs/egov-indexer/stock-indexer.yml,file:///work-dir/configs/egov-indexer/facility-indexer.yml,file:///work-dir/configs/egov-indexer/project-staff-indexer.yml,file:///work-dir/configs/egov-indexer/service-request-indexer.yml,file:///work-dir/configs/works/egov-indexer/measurement-indexer.yml,file:///work-dir/configs/works/egov-indexer/ifms-pi-indexer.yml,file:///work-dir/configs/works/egov-indexer/expensepayment-indexer.yml,file:///work-dir/configs/egov-indexer/egov-pqm-service.yml,file:///work-dir/configs/egov-indexer/pqm-service-indexer.yml,file:///work-dir/configs/egov-indexer/pqm-anomaly-finder-indexer.yml"

egov-persister:
  replicas: 1
  heap: "-Xmx256m -Xms256m"
  memory_limits: 512Mi
  images:
    - egovio/egov-persister
  persist-yml-path: "file:///work-dir/configs/fsm/egov-persister/impel-fsm-persister.yaml,file:///work-dir/configs/egov-persister/vehicle-persister.yaml,file:///work-dir/configs/egov-persister/vendor-persister.yaml,file:///work-dir/configs/egov-persister/fsm-calculator-persister.yaml,file:///work-dir/configs/egov-persister/mdms-persister.yml,file:///work-dir/configs/egov-persister/pt-mutation-calculator-persister.yml,file:///work-dir/configs/egov-persister/apportion-persister.yml,file:///work-dir/configs/egov-persister/billing-services-persist.yml,file:///work-dir/configs/egov-persister/egf-bill.yaml,file:///work-dir/configs/egov-persister/egov-user-event-persister.yml,file:///work-dir/configs/egov-persister/egov-workflow-v2-persister.yml,file:///work-dir/configs/egov-persister/firenoc_persiter.yaml,file:///work-dir/configs/egov-persister/hrms-employee-persister.yml,file:///work-dir/configs/egov-persister/pdf-generator.yml,file:///work-dir/configs/egov-persister/pg-service-persister.yml,file:///work-dir/configs/egov-persister/pgr.v3.yml,file:///work-dir/configs/egov-persister/property-services.yml,file:///work-dir/configs/egov-persister/pt-calculator-v2-persister.yml,file:///work-dir/configs/egov-persister/pt-drafts.yml,file:///work-dir/configs/egov-persister/pt-persist.yml,file:///work-dir/configs/egov-persister/tl-billing-slab-persister.yml,file:///work-dir/configs/egov-persister/tl-calculation-persister.yml,file:///work-dir/configs/egov-persister/uploader-persister.yml,file:///work-dir/configs/egov-persister/collection-migration-persister.yml,file:///work-dir/configs/egov-persister/property-services-registry.yml,file:///work-dir/configs/egov-persister/tradelicense.yml,file:///work-dir/configs/egov-persister/sewerage-persist.yml,file:///work-dir/configs/egov-persister/water-persist.yml,file:///work-dir/configs/egov-persister/water-meter.yml,file:///work-dir/configs/egov-persister/bpa-persister.yml,file:///work-dir/configs/egov-persister/assessment-persister.yml,file:///work-dir/configs/egov-persister/chatbot.yml,file:///work-dir/configs/egov-persister/fsm-persister.yaml,file:///work-dir/configs/egov-persister/vehicle-persister.yaml,file:///work-dir/configs/egov-persister/vendor-persister.yaml,file:///work-dir/configs/egov-persister/fsm-calculator-persister.yaml,file:///work-dir/configs/egov-persister/mdms-persister.yml,file:///work-dir/configs/works/egov-persister/attendance-service-persister.yml,file:///work-dir/configs/works/egov-persister/audit-service-persister.yml,file:///work-dir/configs/works/egov-persister/bankaccounts-persister.yml,file:///work-dir/configs/works/egov-persister/btr-persister.yml,file:///work-dir/configs/works/egov-persister/contract-service-persister.yml,file:///work-dir/configs/works/egov-persister/estimate-service.yml,file:///work-dir/configs/works/egov-persister/expence-calculator-service-persister.yml,file:///work-dir/configs/works/egov-persister/expense-bill-payment-persister.yaml,file:///work-dir/configs/works/egov-persister/expense-billarray-payment-persister.yaml,file:///work-dir/configs/works/egov-persister/expensebilling-service-persister.yml,file:///work-dir/configs/works/egov-persister/muster-service-persister.yml,file:///work-dir/configs/works/egov-persister/organisation-persister.yml,file:///work-dir/configs/egov-persister/project-persister.yml,file:///work-dir/configs/egov-persister/product-persister.yml,file:///work-dir/configs/egov-persister/individual-persister.yml,file:///work-dir/configs/egov-persister/household-persister.yml,file:///work-dir/configs/egov-persister/project-task-persister.yml,file:///work-dir/configs/egov-persister/stock-persister.yml,file:///work-dir/configs/egov-persister/facility-persister.yml,file:///work-dir/configs/egov-persister/service-request-persister.yml,file:///work-dir/configs/egov-persister/pgr-services-persister.yml,file:///work-dir/configs/works/egov-persister/measurement-persister.yml,file:///work-dir/configs/works/egov-persister/measurement-service-persister.yml,file:///work-dir/configs/egov-persister/pqm-persister.yaml,file:///work-dir/configs/egov-persister/referral-management-persister.yml,file:///work-dir/configs/egov-persister/pqm-anomaly-finder-persister.yaml,file:///work-dir/configs/egov-persister/boundary-persister.yml"
  initContainers:
    gitSync:
      repo: "git@github.com:egovernments/configs"      ##### Change repo url with Your fork Repo url
      branch: "UNIFIED-DEV"                                    ##### Change repo branch with Your fork Repo branch

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# financials >>>>>>>>>>>>>>>>>>>>>>>>>>>>

fsm:
  memory_limits: 384Mi
  heap: -Xmx384m -Xms256m