# Common Labels
labels:
  app: "mukta-individual"
  group: "digit-works"

namespace: mukta

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "mukta-individual"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "individual_schema"
    image:
      repository: "mukta-individual-db"

# Container Configs
image:
  repository: "mukta-individual"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/mukta-individual/health"
  readinessProbePath: "/mukta-individual/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_CONTEXT_PATH
    value: /mukta-individual
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /mukta-individual
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: health-individual
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_ENC_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-enc-service
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user       
  - name: EGOV_ENC_ENCRYPT_ENDPOINT
    value: "egov-enc-service/crypto/v1/_encrypt"
  - name: EGOV_ENC_DECRYPT_ENDPOINT
    value: "egov-enc-service/crypto/v1/_decrypt"
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "egov-mdms-service/v1/_search"
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_IDGEN_PATH
    value: "egov-idgen/id/_generate"
  - name: EGOV_IDGEN_INTEGRATION_ENABLED
    value: "true"
  - name: IDGEN.INDIVIDUAL.ID.FORMAT
    value: "individual.id"
  - name: SPRING_REDIS_HOST
    value: redis.backbone
  - name: SPRING_REDIS_PORT
    value: "6379"
  - name: SPRING_CACHE_TYPE
    value: "redis"
  - name: SPRING_CACHE_REDIS_TIME-TO-LIVE
    value: "60"
  - name: SPRING_CACHE_AUTOEXPIRY
    value: "true"
  - name: INDIVIDUAL.CONSUMER.BULK.CREATE.TOPIC
    value: "individual-consumer-bulk-create-topic"
  - name: INDIVIDUAL.CONSUMER.BULK.UPDATE.TOPIC
    value: "individual-consumer-bulk-update-topic"
  - name: INDIVIDUAL.CONSUMER.BULK.DELETE.TOPIC
    value: "individual-consumer-bulk-delete-topic"
  - name: INDIVIDUAL.CONSUMER.SAVE.TOPIC
    value: "save-individual-topic"
  - name: INDIVIDUAL.CONSUMER.UPDATE.TOPIC
    value: "update-individual-topic"
  - name: INDIVIDUAL.CONSUMER.DELETE.TOPIC
    value: "delete-individual-topic"
  - name: KAFKA_TOPICS_NOTIFICATION_SMS
    value: "egov.core.notification.sms"
  - name: KAFKA_TOPICS_WORKS_NOTIFICATION_SMS
    value: "works.notification.sms"
  - name: SMS_ISADDTIONALFIELDREQUIRED
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: sms-isAdditonalFieldRequired
  {{- if index .Values "state-level-tenant-id" }}
  - name: STATE_LEVEL_TENANT_ID
    value: {{ index .Values "state-level-tenant-id" | quote }}
  {{- end }}
  {{- if index .Values "aadhaar-pattern" }}
  - name: AADHAAR_PATTERN
    value: {{ index .Values "aadhaar-pattern" | quote }}
  {{- end }}
  {{- if index .Values "mobile-pattern" }}
  - name: MOBILE_PATTERN
    value: {{ index .Values "mobile-pattern" | quote }}
  {{- end }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-enable-debug" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false" 
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
