{{- with index .Values "cluster-configs" "nginx-errors" -}}
{{- if .enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: {{ index $.Values "cluster-configs" "root-ingress" "cert-issuer" }}
    kubernetes.io/ingress.class: nginx
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  rules:
  - host: {{ $.Values.global.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ .serviceName }}
          servicePort: {{ .servicePort }}
        path: /*
  tls:
  - hosts:
    - {{ $.Values.global.domain }}
    secretName: {{ $.Values.global.domain }}-tls-certs         
{{- end -}}
{{- end -}}
