{{- $envOverrides := index .Values (tpl .Chart.Name .) -}} 
{{- $baseValues := .Values | deepCopy -}}
{{- $values := dict "Values" (mustMergeOverwrite $baseValues $envOverrides) -}}
{{- with mustMergeOverwrite . $values }}
{{- if or .Values.serviceAccount -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ .Chart.Name }}
    group: gateway
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Values.global.namespace }}  
{{- end -}}   
{{- end -}}   