# Common Labels
labels:
  app: "egov-user"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "user"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_user_schema"
    image:
      repository: "egov-user-db"

# Container Configs
image:
  repository: "egov-user"
replicas: "2"
healthChecks:
  enabled: true
  livenessProbePath: "/user/health"
  readinessProbePath: "/user/health"
appType: "java-spring"
tracing-enabled: true
state-level-tenant-id: "pg"
decryption-abac-enabled: "false"
account-unlock-cool-down-period-minutes: "30"
otp-validation: "true"
citizen-otp-enabled: "true"
employee-otp-enabled: "false"
access-token-validity: "10080"
refresh-token-validity: "20160"
default-password-expiry: "90"
mobile-number-validation: "false"
roles-state-level: "true"
citizen-registration-withlogin: "true"
citizen-otp-fixed: "123456"
citizen-otp-fixed-enabled: "true"
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: SPRING_REDIS_HOST
    value: redis.backbone
  - name: SPRING_REDIS_PORT
    value: "6379"
  - name: EGOV_OTP_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-otp
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_SERVICES_ACCESSCONTROL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-accesscontrol
  - name: EGOV_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  - name: MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_ENC_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-enc-service
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: state-level-tenant-id
  - name: DECRYPTION_ABAC_ENABLED
    value: {{ index .Values "decryption-abac-enabled" | quote }}
  - name: KAFKA_TOPIC_AUDIT
    value: "enc-user-audit-data"         
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: "egov-user"
  - name: ACCOUNT_UNLOCK_COOL_DOWN_PERIOD_MINUTES
    value: {{ index .Values "account-unlock-cool-down-period-minutes" | quote }}
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer  
  {{- if index .Values "otp-validation" }}
  - name: OTP_VALIDATION_REGISTER_MANDATORY
    value: {{ index .Values "otp-validation" | quote }}
  {{- end }}
  {{- if index .Values "citizen-otp-enabled" }}
  - name: CITIZEN_LOGIN_PASSWORD_OTP_ENABLED
    value: {{ index .Values "citizen-otp-enabled" | quote }}
  {{- end }}
  {{- if index .Values "employee-otp-enabled" }}
  - name: EMPLOYEE_LOGIN_PASSWORD_OTP_ENABLED
    value: {{ index .Values "employee-otp-enabled" | quote }}
  {{- end }}
  {{- if index .Values "access-token-validity" }}
  - name: ACCESS_TOKEN_VALIDITY_IN_MINUTES
    value: {{ index .Values "access-token-validity" | quote }}
  {{- end }}
  {{- if index .Values "refresh-token-validity" }}
  - name: REFRESH_TOKEN_VALIDITY_IN_MINUTES
    value: {{ index .Values "refresh-token-validity" | quote }}
  {{- end }}
  {{- if index .Values "default-password-expiry" }}
  - name: DEFAULT_PASSWORD_EXPIRY_IN_DAYS
    value: {{ index .Values "default-password-expiry" | quote }}
  {{- end }}
  {{- if index .Values "mobile-number-validation" }}
  - name: MOBILE_NUMBER_VALIDATION_WORKAROUND_ENABLED
    value: {{ index .Values "mobile-number-validation" | quote }}
  {{- end }}
  {{- if index .Values "roles-state-level" }}
  - name: ROLES_STATE_LEVEL_ENABLED
    value: {{ index .Values "roles-state-level" | quote }}
  {{- end }}
  {{- if index .Values "citizen-registration-withlogin" }}
  - name: CITIZEN_REGISTRATION_WITHLOGIN_ENABLED
    value: {{ index .Values "citizen-registration-withlogin" | quote }}
  {{- end }}
  {{- if index .Values "citizen-otp-fixed" }}
  - name: CITIZEN_LOGIN_PASSWORD_OTP_FIXED_VALUE
    value: {{ index .Values "citizen-otp-fixed" | quote }}
  {{- end }}
  {{- if index .Values "citizen-otp-fixed-enabled" }}
  - name: CITIZEN_LOGIN_PASSWORD_OTP_FIXED_ENABLED
    value: {{ index .Values "citizen-otp-fixed-enabled" | quote }}
  {{- end }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "global" "mobile-validation-workaround" }}
  - name: MOBILE_NUMBER_VALIDATION_WORKAROUND_ENABLED
    value: "true"
  {{- end }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false" 
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
