# Common Labels
labels:
  app: "firenoc-services"
  group: "rainmaker"

namespace: urban  

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "firenoc-services"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "firenoc_services_schema"
    image:
      repository: "firenoc-services-db"

# Container Configs
image:
  repository: "firenoc-services"
appType: "java-spring"
tracing-enabled: true

# Additional Container Envs
env: |
  - name: DB_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-host
  - name: DB_NAME
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-name
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: EGOV_DEFAULT_STATE_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id      
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: EGOV_PROPERTY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: pt-services-v2
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_FN_CALCULATOR_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: firenoc-calculator
  - name: EGOV_HOST_BASE_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/egov-mdms-service/v1/_search"
  - name: DB_PORT
    value: "5432"          
  - name: KAFKA_TOPICS_FIRENOC_CREATE
    value: "save-fn-firenoc"
  - name: KAFKA_TOPICS_FIRENOC_UPDATE
    value: "update-fn-firenoc"
  - name: KAFKA_TOPICS_FIRENOC_WORKFLOW
    value: "update-fn-workflow" 
  - name: KAFKA_TOPICS_RECEIPT_CREATE
    value: "egov.collection.payment-create"   
  - name: KAFKA_TOPICS_NOTIFICATION_SMS
    value: "egov.core.notification.sms"
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-firenoc-services
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: WORKFLOW_CONTEXT_PATH
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: WORKFLOW_TRANSITION_PATH
    value: "egov-workflow-v2/egov-wf/process/_transition"
  - name: KAFKA_BROKER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
  - name: SERVER_PORT
    value: "8080"
