{{- with index .Values "cluster-configs" "secrets" "egov-pg-service" }}
{{- if index . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
{{- if index . "axis-merchant-id" }}
  axismerchantid: {{ index . "axis-merchant-id" | b64enc | quote }}
  axismerchantsecret: {{ index . "axis-merchant-secret-key" | b64enc | quote }}
  axismerchantuser: {{ index . "axis-merchant-user" | b64enc | quote }}
  axismerchantpwd: {{ index . "axis-merchant-pwd" | b64enc | quote }}
  axismerchantaccesscode: {{ index . "axis-merchant-access-code" | b64enc | quote }}
{{- end }}  
{{- if index . "easypay-merchant-id" }}
  easypay-merchant-id: {{ index . "easypay-merchant-id" | b64enc | quote }}
  easypay-aes-key: {{ index . "easypay-aes-key" | b64enc | quote }}
{{- end }}
{{- if index . "payu-merchant-key" }}
  payumerchantkey: {{ index . "payu-merchant-key" | b64enc | quote }}
  payumerchantsalt: {{ index . "payu-merchant-salt" | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}