namespace : staging
# Common Labels
labels:
  app: "trackingservice"
  group: "rainmaker"

hpa:
  enabled: true

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "trackingservice"
  namespace : egov
# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "trackingservice_schema"
    image:
      repository: "trackingservice-db"
# Container Configs
image:
  repository: "trackingservice"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/trackingservice/health"
  readinessProbePath: "/trackingservice/health"
appType: "java-spring"
tracing-enabled: true
memory_limits: 712Mi
heap: "-Xmx512m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"
#egov.idgen.pqm.applicationNum.format: "[CITY.CODE]-FSM-[cy:yyyy-MM-dd]-[SEQ_EGOV_FSM]"
# Additional Container Envs
env: |
  # - name: EGOV_FSM_HOST
  #   valueFrom:
  #     configMapKeyRef:
  #       name: egov-service-host
  #       key: fsm
  # - name: EGOV_VEHICLE_HOST
  #   valueFrom:
  #     configMapKeyRef:
  #       name: egov-service-host
  #       key: vehicle
  - name: EGOV_FSM_HOST
    value: ${DIGIT_FSM_URL:https://unified-demo.digit.org/}

  # Vehicle service
  - name: EGOV_VEHICLE_HOST
    value: ${DIGIT_VEHICLE_TRIP_URL:https://unified-demo.digit.org/}
    
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  {{- if index .Values "java-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-debug" | quote }}
  {{- else }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
