# Common Labels
labels:
  app: "case-management"
  group: "case-management"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "case_management_schema"
    image:
      repository: "case-management-db"

# Container Configs
image:
  repository: "case-management"
replicas: "1"
tracing-enabled: true
healthChecks:
  enabled: true
  livenessProbePath: "/case-management/actuator/health"
  readinessProbePath: "/case-management/actuator/health"
heap: "-Xmx192m -Xms192m -XX:TieredStopAtLevel=1"
java-args: ""
es-index-name: "case-management"
persister-save-case-topic: "save-cms-case"
persister-update-case-topic: "update-cms-case"
es-case-topic: "es-cms-case"
consumer-group: "case-management"
es-url: elasticsearch-client-v1.es-cluster:9200
subject-health-details-collector-onboarding: Health Details Collector On-Boarding Details
subject-case-admin-onboarding: Isolation Case Manager On-Boarding Details

# Additional Container Envs
env: |
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: /case-management
  - name: ES_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: es-host
  - name: ES_PORT
    value: "9200"
  - name: SPRING_ELASTICSEARCH_REST_URIS
    value: {{ index .Values "es-url" | quote }}  
  - name: ES_INDEX_NAME
    value: {{ index .Values "es-index-name" | quote }}
  - name: EGOV_ENC_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-enc-service
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user-enc      
  - name: EGOV_ROOT_TENANT_ID
    valueFrom:
      configMapKeyRef:
        key: egov-state-level-tenant-id
        name: egov-config          
  - name: PERSISTER_SAVE_CASE_TOPIC
    value: {{ index .Values "persister-save-case-topic" | quote }}       
  - name: PERSISTER_UPDATE_CASE_TOPIC
    value: {{ index .Values "persister-update-case-topic" | quote }}     
  - name: ES_CASE_TOPIC
    value: {{ index .Values "es-case-topic" | quote }}
  - name: FLYWAY_ENABLED
    value: "false"      
  - name: APP_TIMEZONE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: timezone     
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: {{ index .Values "consumer-group" | quote }}  
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers    
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}    
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SMS_CREATE_CASE_TEMPLATE
    value: {{ index .Values "sms-create-case-template" | quote }}
  - name: EMAIL_SUBJECT_ONBOARD_HEALTH_DETAILS_COLLECTOR
    value: {{ index .Values "subject-health-details-collector-onboarding" | quote }}
  - name: EMAIL_SUBJECT_ONBOARD_CASE_ADMIN
    value: {{ index .Values "subject-case-admin-onboarding" | quote }}      
  - name: EMAIL_ATTACHMENT_ONBOARD_CASE_ADMIN_FILESTOREID
    value: {{ index .Values "attachment-case-admin-filestoreid" | quote }}  
  - name: ISOLATION_HEALTH_COLLECTION_TIME
    value: {{ index .Values "isolation-health-report-collection-time" | quote }}  
  - name: COVA_FETCH_URL
    value: {{ index .Values "cova-fetch-url" | quote }}
  - name: COVA_CREATE_HEALTH_RECORD_URL
    value: {{ index .Values "cova-create-health-record-url" | quote }}
  - name: COVA_AUTH_TOKEN
    valueFrom:
      secretKeyRef:
        name: case-management
        key: cova-auth-token                      
