# Common Labels
labels:
  app: "data-upload"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "data-upload"

# Init Containers Configs
initContainers:
  gitSync:
    enabled: true
    repo: "git@github.com:egovernments/configs"
    branch: "master"  

# Container Configs
image:
  repository: "data-upload"
replicas: "1"
tracing-enabled: true
healthChecks:
  enabled: true
  livenessProbePath: "/data-upload/actuator/health"
  readinessProbePath: "/data-upload/actuator/health"
heap: "-Xmx192m -Xms192m -XX:TieredStopAtLevel=1"
java-args: ""
config-paths: "file:///work-dir/configs/data-upload/case-management.yaml"

# Additional Container Envs
env: |
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: /data-upload   
  - name: EGOV_ROOT_TENANT_ID
    valueFrom:
      configMapKeyRef:
        key: egov-state-level-tenant-id
        name: egov-config          
  - name: CONFIG_REPO_PATH
    value: {{ index .Values "config-paths" | quote }}       
  - name: APP_TIMEZONE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: timezone      
  - name: EGOV_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore        
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}    
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
