# Common Labels
labels:
  app: "egov-apportion-service"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "apportion-service"


# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_apportion_service_schema"
    image:
      repository: "egov-apportion-service-db"

# Container Configs
image:
  repository: "egov-apportion-service"
healthChecks:
  enabled: true
  livenessProbePath: "/apportion-service/health"
  readinessProbePath: "/apportion-service/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-tl-services
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: PERSISTER_SAVE_APPORTION_REQUEST_TOPIC
    value: save-apportion-request
  - name: PERSISTER_SAVE_APPORTION_RESPONSE_TOPIC
    value: save-apportion-response
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/egov-mdms-service/v1/_search"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
