# Common Labels
labels:
  app: "egov-notification-sms"
  group: "core"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "egov-notification-sms"
replicas: "1"
appType: "java-spring"
tracing-enabled: true
sms-provider-url: "https://msdgweb.mgov.gov.in/esms/sendsmsrequest"
sms-sender: "egov"
sms-sender-requesttype: "POST"
sms-extra-req-params: "smsservicetype=unicodemsg"
sms-gateway-to-use: "MSDG"
sms.provider.url: "https://msdgweb.mgov.gov.in/esms/sendsmsrequest"
sms.provider.requestType: "POST"
sms.provider.contentType: "application/json"
sms.provider.class: "MSDG"
sms.verify.response: true
sms.print.response: false
sms.success.codes: "200,201,202"
sms.verify.responseContains: "SMS message(s) sent"
sms.error.codes: "401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418" 
heap: "-Xmx192m -Xms192m"
java-args: ""
memory_limits: "256Mi"
cpu_limits: "50m"

# Additional Container Envs
env: |
  - name: KAFKA_TOPICS_NOTIFICATION_SMS_NAME
    value: egov.core.notification.sms
  - name: KAFKA_TOPICS_NOTIFICATION_SMS_ID
    value: egov.core.notification.sms
  - name: KAFKA_TOPICS_NOTIFICATION_SMS_GROUP
    value: egov.core.notification.sms
  {{- if index .Values "sms-config-map" }}
  - name: SMS_CONFIG_MAP
    value: {{ index .Values "sms-config-map" | quote }}
  {{- end }}
  - name: SMS_PROVIDER_URL
    value: {{ index .Values "sms-provider-url" | quote }}
  - name: SMS_SENDER_USERNAME
    valueFrom:
      secretKeyRef:
        name: egov-notification-sms
        key: username
  - name: SMS_SENDER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: egov-notification-sms
        key: password
  {{- if index .Values "secure-key" }}
  - name: SMS_SENDER_SECURE_KEY
    valueFrom:
      secretKeyRef:
        name: egov-notification-sms
        key: secure-key        
  {{- end }}
  - name: SMS_ENABLED
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: sms-enabled
  - name: SMS_SENDER
    value: {{ index .Values "sms-sender" | quote }}
  - name: SMS_SENDER_REQUESTTYPE
    value: {{ index .Values "sms-sender-requesttype" | quote }}
  {{- if index .Values "sms-custom-config" }}
  - name: SMS_SENDER_REQ_PARAM_NAME
    value: {{ index .Values "sms-sender-req-param-name" | quote }}
  - name: SMS_SENDER_USERNAME_REQ_PARAM_NAME
    value: {{ index .Values "sms-sender-username-req-param-name" | quote }}
  - name: SMS_SENDER_PASSWORD_REQ_PARAM_NAME
    value: {{ index .Values "sms-sender-password-req-param-name" | quote }}
  - name: SMS_DESTINATION_MOBILE_REQ_PARAM_NAME
    value: {{ index .Values "sms-destination-mobile-req-param-name" | quote }}
  - name: SMS_TYPE_REQ_PARAM_NAME  
    value: "smsservicetype"  
  - name: SMS_MESSAGE_REQ_PARAM_NAME
    value: {{ index .Values "sms-message-req-param-name" | quote }}
  - name: "SMS_EXTRA_REQ_PARAMS"
    value: {{ index .Values "sms-extra-req-params" | quote }}
  - name: SMS_VERIFY_SSL
    value: "false"
  - name: SMS_URL_DONT_ENCODE_URL
    value: "true"
  {{- end }}
  - name: SMS_SPICEDIGITAL_PROVIDER_URL
    value: {{ index .Values "sms-provider-url" | quote }}
  - name: SMS_SPICEDIGITAL_SENDER_USERNAME
    valueFrom:
      secretKeyRef:
        name: egov-notification-sms
        key: username
  - name: SMS_SPICEDIGITAL_SENDER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: egov-notification-sms
        key: password
  - name: LOGGING_LEVEL_org.egov.tracer.kafka    
    value: "DEBUG"              
  - name: SMS_SPICEDIGITAL_SENDER    
    value: {{ index .Values "sms-sender" | quote }}
  - name: SMS_GATEWAY_TO_USE
    value: {{ index .Values "sms-gateway-to-use" | quote }}        
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SMS_PROVIDER_USERNAME    
    valueFrom:
      secretKeyRef:
        name: egov-notification-sms
        key: username
  - name: SMS_PROVIDER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: egov-notification-sms
        key: password
  {{- if index .Values "sms.provider.class" }}
  - name: SMS_PROVIDER_CLASS
    value: {{ index .Values "sms.provider.class" | quote }} 
  {{- end }}
  {{- if index .Values "sms.provider.requestType" }}
  - name: SMS_PROVIDER_REQUESTTYPE
    value: {{ index .Values "sms.provider.requestType" | quote }} 
  {{- end }}
  {{- if index .Values "sms.senderid" }}
  - name: SMS_SENDERID
    value: {{ index .Values "sms.senderid" | quote }} 
  {{- end }}
  {{- if index .Values "sms.provider.contentType" }}
  - name: SMS_PROVIDER_CONTENTTYPE
    value: {{ index .Values "sms.provider.contentType" | quote }} 
  {{- end }}
  {{- if index .Values "sms.category.map" }}
  - name: SMS_CATEGORY_MAP
    value: {{ index .Values "sms.category.map" | quote }} 
  {{- end }}
  {{- if index .Values "sms.extra.config.map" }}
  - name: SMS_EXTRA_CONFIG_MAP
    value: {{ index .Values "sms.extra.config.map" | quote }} 
  {{- end }}
  {{- if index .Values "sms.print.response" }}
  - name: SMS_PRINT_RESPONSE
    value: {{ index .Values "sms.print.response" | quote }} 
  {{- end }}  
  {{- if index .Values "sms.verify.response" }}
  - name: SMS_VERIFY_RESPONSE
    value: {{ index .Values "sms.verify.response" | quote }} 
  {{- end }}  
  {{- if index .Values "sms.verify.responseContains" }}
  - name: SMS_VERIFY_RESPONSECONTAINS
    value: {{ index .Values "sms.verify.responseContains" | quote }} 
  {{- end }}  
  {{- if index .Values "sms.success.codes" }}
  - name: SMS_SUCCESS_CODES
    value: {{ index .Values "sms.success.codes" | quote }} 
  {{- end }}  
  {{- if index .Values "sms.error.codes" }}
  - name: SMS_ERROR_CODES
    value: {{ index .Values "sms.error.codes" | quote }} 
  {{- end }}  
  {{- if index .Values "sms.blacklist.numbers" }}
  - name: SMS_BLACKLIST_NUMBERS
    value: {{ index .Values "sms.blacklist.numbers" | quote }} 
  {{- end }}  
  {{- if index .Values "sms.whitelist.numbers" }}
  - name: SMS_WHITELIST_NUMBERS
    value: {{ index .Values "sms.whitelist.numbers" | quote }} 
  {{- end }}  
  {{- if index .Values "sms.mobile.prefix" }}
  - name: SMS_MOBILE_PREFIX
    value: {{ index .Values "sms.mobile.prefix" | quote }} 
  {{- end }}  
  {{- if index .Values "kafka.topics.backup.sms" }}
  - name: KAFKA_TOPICS_BACKUP_SMS
    value: {{ index .Values "kafka.topics.backup.sms" | quote }} 
  {{- end }}  
  {{- if index .Values "kafka.topics.expiry.sms" }}
  - name: KAFKA_TOPICS_EXPIRY_SMS
    value: {{ index .Values "kafka.topics.expiry.sms" | quote }} 
  {{- end }}  
  {{- if index .Values "kafka.topics.error.sms" }}
  - name: KAFKA_TOPICS_ERROR_SMS
    value: {{ index .Values "kafka.topics.error.sms" | quote }} 
  {{- end }}       
