# Common Labels
labels:
  app: "health-muster-roll"
  group: "health"

namespace: health

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "health-muster-roll"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "muster_roll_schema"
    image:
      repository: "health-muster-roll-db"

# Container Configs
image:
  repository: "health-muster-roll"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/health-muster-roll/health"
  readinessProbePath: "/health-muster-roll/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
memory_limits: 512Mi
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: SERVER_CONTEXT_PATH
    value: /health-muster-roll
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /health-muster-roll 
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: ATTENDANCE_LOG_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: health-attendance-service
  - name: INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: health-individual
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EXPENSE_CALCULATOR_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: health-expense-calculator
  - name: APP_TIMEZONE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: timezone
  - name: MUSTERROLL_KAFKA_CREATE_TOPIC
    value: "save-musterroll-health"
  - name: MUSTERROLL_KAFKA_UPDATE_TOPIC
    value: "update-musterroll-health"
  - name: MUSTERROLL_KAFKA_CALCULATE_TOPIC
    value: "calculate-musterroll-health"
  - name: KAFKA_TOPICS_NOTIFICATION_SMS
    value: "egov.core.notification.sms"
  {{- if index .Values "notification-sms-enabled" }}
  - name: NOTIFICATION_SMS_ENABLED
    value: {{ index .Values "notification-sms-enabled" | quote }}
  {{- end }}
  {{- if index .Values "musterroll-default-offset" }}
  - name: MUSTERROLL_DEFAULT_OFFSET
    value: {{ index .Values "musterroll-default-offset" | quote }}
  {{- end }}
  {{- if index .Values "musterroll-default-limit" }}
  - name: MUSTERROLL_DEFAULT_LIMIT
    value: {{ index .Values "musterroll-default-limit" | quote }}
  {{- end }}
  {{- if index .Values "musterroll-search-max-limit" }}
  - name: MUSTERROLL_SEARCH_MAX_LIMIT
    value: {{ index .Values "musterroll-search-max-limit" | quote }}
  {{- end }}
  {{- if index .Values "musterroll-workflow-business-service" }}
  - name: MUSTERROLL_WORKFLOW_BUSINESS_SERVICE
    value: {{ index .Values "musterroll-workflow-business-service" | quote }}
  {{- end }}
  {{- if index .Values "attendance-log-search-endpoint" }}
  - name: ATTENDANCE_LOG_SEARCH_ENDPOINT
    value: {{ index .Values "attendance-log-search-endpoint" | quote }}
  {{- end }}
  {{- if index .Values "attendance-register-search-endpoint" }}
  - name: ATTENDANCE_REGISTER_SEARCH_ENDPOINT
    value: {{ index .Values "attendance-register-search-endpoint" | quote }}
  {{- end }}
  {{- if index .Values "attendance-register-search-limit" }}
  - name: ATTENDANCE_REGISTER_SEARCH_LIMIT
    value: {{ index .Values "attendance-register-search-limit" | quote }}
  {{- end }}
  {{- if index .Values "individual-search-endpoint" }}
  - name: INDIVIDUAL_SEARCH_ENDPOINT
    value: {{ index .Values "individual-search-endpoint" | quote }}
  {{- end }}
  {{- if index .Values "muster-restricted-search-roles" }}
  - name: MUSTER_RESTRICTED_SEARCH_ROLES
    value: {{ index .Values "muster-restricted-search-roles" | quote }}
  {{- end }}
  - name: EGOV_MDMS_V2_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: mdms-service-v2

  
