# Common Labels
labels:
  app: "health-muster-roll"
  group: "health"

namespace: health

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "health-muster-roll"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "muster_roll_schema"
    image:
      repository: "health-muster-roll-db"

# Container Configs
image:
  repository: "health-muster-roll"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/health-muster-roll/health"
  readinessProbePath: "/health-muster-roll/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
memory_limits: 512Mi
java-args: ""
egov-mdms-service-host-key: "egov-mdms-service"
egov-mdms-service-endpoint-key: "egov-mdms-service/v1/_search"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_CONTEXT_PATH
    value: /health-muster-roll
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /health-muster-roll 
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: WORKS_ATTENDANCE_LOG_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: health-attendance
  - name: WORKS_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: health-individual
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: WORKS_EXPENSE_CALCULATOR_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: health-expense-calculator
  - name: APP_TIMEZONE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: timezone
  - name: MUSTERROLL_KAFKA_CREATE_TOPIC
    value: "save-musterroll-health"
  - name: MUSTERROLL_KAFKA_UPDATE_TOPIC
    value: "update-musterroll-health"
  - name: MUSTERROLL_KAFKA_CALCULATE_TOPIC
    value: "calculate-musterroll-health"
  - name: KAFKA_TOPICS_NOTIFICATION_SMS
    value: "egov.core.notification.sms"
  - name: EGOV_USER_CONTEXT_PATH
    value: "user"
  - name: EGOV_USER_CREATE_PATH
    value: "/users/_createnovalidate"
  - name: EGOV_USER_SEARCH_PATH
    value: "/v1/_search"
  - name: EGOV_USER_UPDATE_PATH
    value: "/users/_updatenovalidate"
  {{- if index .Values "notification-sms-enabled" }}
  - name: NOTIFICATION_SMS_ENABLED
    value: {{ index .Values "notification-sms-enabled" | quote }}
  {{- end }}
  {{- if index .Values "musterroll-default-offset" }}
  - name: MUSTERROLL_DEFAULT_OFFSET
    value: {{ index .Values "musterroll-default-offset" | quote }}
  {{- end }}
  {{- if index .Values "musterroll-default-limit" }}
  - name: MUSTERROLL_DEFAULT_LIMIT
    value: {{ index .Values "musterroll-default-limit" | quote }}
  {{- end }}
  {{- if index .Values "musterroll-search-max-limit" }}
  - name: MUSTERROLL_SEARCH_MAX_LIMIT
    value: {{ index .Values "musterroll-search-max-limit" | quote }}
  {{- end }}
  {{- if index .Values "musterroll-workflow-business-service" }}
  - name: MUSTERROLL_WORKFLOW_BUSINESS_SERVICE
    value: {{ index .Values "musterroll-workflow-business-service" | quote }}
  {{- end }}
  {{- if index .Values "attendance-log-search-endpoint" }}
  - name: WORKS_ATTENDANCE_LOG_SEARCH_ENDPOINT
    value: {{ index .Values "attendance-log-search-endpoint" | quote }}
  {{- end }}
  {{- if index .Values "attendance-register-search-endpoint" }}
  - name: WORKS_ATTENDANCE_REGISTER_SEARCH_ENDPOINT
    value: {{ index .Values "attendance-register-search-endpoint" | quote }}
  {{- end }}
  {{- if index .Values "attendance-register-update-endpoint" }}
  - name: WORKS_ATTENDANCE_REGISTER_UPDATE_ENDPOINT
    value: {{ index .Values "attendance-register-update-endpoint" | quote }}
  {{- end }}
  {{- if index .Values "attendance-register-search-limit" }}
  - name: WORKS_ATTENDANCE_REGISTER_SEARCH_LIMIT
    value: {{ index .Values "attendance-register-search-limit" | quote }}
  {{- end }}
  {{- if index .Values "individual-search-endpoint" }}
  - name: WORKS_INDIVIDUAL_SEARCH_ENDPOINT
    value: {{ index .Values "individual-search-endpoint" | quote }}
  {{- end }}
  {{- if index .Values "expense-calculator-endpoint" }}
  - name: WORKS_EXPENSE_CALCULATOR_ENDPOINT
    value: {{ index .Values "expense-calculator-endpoint" | quote }}
  {{- end }}
  {{- if index .Values "muster-restricted-search-roles" }}
  - name: MUSTER_RESTRICTED_SEARCH_ROLES
    value: {{ index .Values "muster-restricted-search-roles" | quote }}
  {{- end }}
  - name: EGOV_MDMS_V2_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: {{ index .Values "egov-mdms-service-host-key" | quote }}
  - name: EGOV_MDMS_V2_SEARCH_ENDPOINT 
    value: {{ index .Values "egov-mdms-service-endpoint-key" | quote }}
  {{- if index .Values "musterroll-update-recompute-attendance-enabled" }}
  - name: MUSTERROLL_UPDATE_RECOMPUTE_ATTENDANCE_ENABLED
    value: {{ index .Values "musterroll-update-recompute-attendance-enabled" | quote }}
  {{- end }}
  {{- if index .Values "musterroll-individual-entry-roles-enabled" }}
  - name: MUSTERROLL_INDIVIDUAL_ENTRY_ROLES_ENABLED
    value: {{ index .Values "musterroll-individual-entry-roles-enabled" | quote }}
  {{- end }}
  {{- if index .Values "musterroll-validate-start-date-monday-enabled" }}
  - name: MUSTERROLL_VALIDATE_START_DATE_MONDAY_ENABLED
    value: {{ index .Values "musterroll-validate-start-date-monday-enabled" | quote }}
  {{- end }}
  {{- if index .Values "musterroll-add-bank-account-details-enabled" }}
  - name: MUSTERROLL_ADD_BANK_ACCOUNT_DETAILS_ENABLED
    value: {{ index .Values "musterroll-add-bank-account-details-enabled" | quote }}
  {{- end }}
  {{- if index .Values "musterroll-update-attendance-register-review-status-enabled" }}
  - name: MUSTERROLL_UPDATE_ATTENDANCE_REGISTER_REVIEW_STATUS_ENABLED
    value: {{ index .Values "musterroll-update-attendance-register-review-status-enabled" | quote }}
  {{- end }}
  {{- if index .Values "musterroll-workflow-enabled" }}
  - name: MUSTERROLL_WORKFLOW_ENABLED
    value: {{ index .Values "musterroll-workflow-enabled" | quote }}
  {{- end }}
  - name: MUSTERROLL_NOWORKFLOW_CREATE_STATUS
    value: "APPROVAL_PENDING"
  {{- if index .Values "musterroll-validate-attendance-register-enabled" }}
  - name: MUSTERROLL_VALIDATE_ATTENDANCE_REGISTER_ENABLED
    value: {{ index .Values "musterroll-validate-attendance-register-enabled" | quote }}
  {{- end }}
  {{- if index .Values "musterroll-set-default-duration-enabled" }}
  - name: MUSTERROLL_SET_DEFAULT_DURATION_ENABLED
    value: {{ index .Values "musterroll-set-default-duration-enabled" | quote }}
  {{- end }}

  
