# Common Labels
labels:
  app: "egov-idgen"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "egov-idgen"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_idgen_schema"
    image:
      repository: "egov-idgen-db"

# Container Configs
image:
  repository: "egov-idgen"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/egov-idgen/health"
  readinessProbePath: "/egov-idgen/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: "-Dspring.profiles.active=monitoring"
idformat-from-mdms: "false"
autocreate-new-seq: "false"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: IDFORMAT_FROM_MDMS
    value: {{ index .Values "idformat-from-mdms" | quote }}
  - name: AUTOCREATE_NEW_SEQ
    value: {{ index .Values "autocreate-new-seq" | quote }}
  - name: MDMS_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: MDMS_SERVICE_SEARCH_URI
    value: "mdms-v2/v1/_search"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false" 
