# Common Labels
labels:
  app: "statements"
  group: "works"

namespace: staging

hpa:
  enabled: true

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "statements"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "statements_schema"
    image:
      repository: "statements-db"
    env: |
      {{- if index .Values "statements-ismultischema-enabled" }}        
      - name: SCHEMA_NAME
        value: {{ index .Values "statements-schemas" | quote }}
      {{- end }}
      - name: "DB_URL"
        valueFrom: 
          configMapKeyRef: 
            name: egov-config
            key: db-url-works
      - name: "SCHEMA_TABLE"
        value: {{ .Values.initContainers.dbMigration.schemaTable | quote }}              
      - name: "FLYWAY_USER"
        valueFrom: 
          secretKeyRef: 
            name: db
            key: flyway-username
      - name: "FLYWAY_PASSWORD"
        valueFrom:
          secretKeyRef: 
            name: db
            key: flyway-password
      - name: "FLYWAY_LOCATIONS"
        valueFrom: 
          configMapKeyRef: 
            name: egov-config
            key: flyway-locations  
      {{- if index .Values.global "is-environment-central-instance" }}        
      - name: IS_ENVIRONMENT_CENTRAL_INSTANCE
        valueFrom:
          configMapKeyRef:
            name: egov-config
            key: is-environment-central-instance
      - name: STATE_LEVEL_TENANTID_LENGTH
        valueFrom:
          configMapKeyRef:
            name: egov-config
            key: state-level-tenantid-length
      {{- end }} 


# Container Configs
image:
  repository: "statements"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/statements/health"
  readinessProbePath: "/statements/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
memory_limits: 512Mi
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: SERVER_CONTEXT_PATH
    value: /statements
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /statements
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: EGOV_MDMS_V2_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service-v2 
  - name: EGOV_MDMS_V2_SEARCH_ENDPOINT
    value: "/mdms-v2/v1/_search"
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/egov-mdms-service/v1/_search"
  - name: WORKS_ESTIMATE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: estimate-service                
  - name: WORKS_MEASUREMENT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: measurement-service 
  - name: WORKS_CONTRACT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: contract-service
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/egov-mdms-service/v1/_search"
