# Common Labels
labels:
  app: "egov-indexer"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "egov-indexer"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_indexer_schema"
    image:
      repository: "egov-indexer-db"
      tag: core-2.9-lts-mvn-check-5f0cc52126-55
  gitSync:
    enabled: true
    repo: "git@github.com:egovernments/configs"
    branch: "master"

# Container Configs
image:
  repository: "egov-indexer"
  tag: core-2.9-lts-mvn-check-5f0cc52126-55
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/egov-indexer/health"
  readinessProbePath: "/egov-indexer/health"
appType: "java-spring"
tracing-enabled: true
egov-indexer-yaml-repo-path: "file:///work-dir/configs/egov-indexer/billingservices-indexer.yml,file:///work-dir/configs/egov-indexer/collection-indexer.yml,file:///work-dir/configs/egov-indexer/egov-telemetry-indexer.yml,file:///work-dir/configs/egov-indexer/egov-uploader-indexer.yml,file:///work-dir/configs/egov-indexer/error-queue.yml,file:///work-dir/configs/egov-indexer/finance-rolloutadotpion-indexer.yml,file:///work-dir/configs/egov-indexer/payment-indexer.yml,file:///work-dir/configs/egov-indexer/rainmaker-pgr-indexer.yml,file:///work-dir/configs/egov-indexer/rainmaker-pt-indexer.yml,file:///work-dir/configs/egov-indexer/tradelicense-indexer.yml,file:///work-dir/configs/egov-indexer/rainmaker-tl-indexer.yml"
heap: "-Xmx192m -Xms192m"
indexer-host: "egov-indexer"

# Additional Container Envs
env: |
  - name: EGOV_SERVICES_INFRA_INDEXER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: {{ index .Values "indexer-host" }}
  - name: EGOV_INFRA_INDEXER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: es-indexer-host
  - name: EGOV_INDEXER_YML_REPO_PATH
    value: {{ index .Values "egov-indexer-yaml-repo-path" | quote }}
  {{- if index .Values "global" "serializers-timezone-in-ist" }}
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
  {{- end }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: EGOV_STATELEVEL_TENANTID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: EGOV_INDEXER_ES_USERNAME
    valueFrom:
      secretKeyRef:
        name: elasticsearch-credentials
        key: username
  - name: EGOV_INDEXER_ES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-credentials
        key: password   