# Common Labels
labels:
  app: "beneficiary-idgen"
  group: "health"

namespace: health

# Ingress Configs
ingress:
  enabled: true
  namespace: egov
  zuul: true
  context: "beneficiary-idgen"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "beneficiary_idgen_schema"
    image:
      repository: "beneficiary-idgen-db"

# Container Configs
image:
  repository: "beneficiary-idgen"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/beneficiary-idgen/health"
  readinessProbePath: "/beneficiary-idgen/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx384m -Xms384m"
java-args: "-Dspring.profiles.active=monitoring"
idformat-from-mdms: "false"
autocreate-new-seq: "false"
memory_limits: "1Gi"
cpu_limits: "200m"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: SERVER_CONTEXT_PATH
    value: /beneficiary-idgen
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /beneficiary-idgen
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: IDFORMAT_FROM_MDMS
    value: {{ index .Values "idformat-from-mdms" | quote }}
  - name: AUTOCREATE_NEW_SEQ
    value: {{ index .Values "autocreate-new-seq" | quote }}
  - name: MDMS_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: mdms-service-v2
  - name: EGOV_MDMS_SEARCH_URI
    value: {{ .Values.mdmsSearchPath | default "/mdms-v2/v1/_search" }}
  - name: REDIS_TTL_IN_DAYS
    value: {{ index .Values "redis-ttl-in-days" | quote }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false" 
  - name: SPRING_REDIS_HOST
    value: redis.backbone
  - name: SPRING_REDIS_PORT
    value: {{ .Values.spring.redis.port | quote }}
  - name: SPRING_CACHE_TYPE
    value: {{ .Values.spring.redis.cache.type }}
  - name: SPRING_CACHE_REDIS_TIME_TO_LIVE
    value: {{ .Values.spring.redis.cache.timeToLive | quote }}
  - name: SPRING_CACHE_AUTOEXPIRY
    value: {{ .Values.spring.redis.cache.autoExpiry | quote }}
  - name: REDISSON_REDIS_HOST
    value: redis.backbone
  - name: REDISSON_REDIS_PORT
    value: {{ .Values.redisson.redis.port | quote }}
  - name: REDISSON_REDIS_TIMEOUT
    value: {{ .Values.redisson.redis.timeout | quote }}
  - name: REDISSON_REDIS_CONNECTION_POOL_SIZE
    value: {{ .Values.redisson.redis.connectionPoolSize | quote }}
  - name: REDISSON_REDIS_CONNECTION_MIN_IDLE_SIZE
    value: {{ .Values.redisson.redis.connectionMinimumIdleSize | quote }}
  - name: REDISSON_REDIS_THREADS
    value: {{ .Values.redisson.redis.threads | quote }}
  - name: REDISSON_REDIS_NETTY_THREADS
    value: {{ .Values.redisson.redis.nettyThreads | quote }}
  - name: KAFKA_TOPICS_SAVE_IN_ID_POOL
    value: {{ .Values.kafka.topics.saveInIdPool | quote }}
  - name: KAFKA_TOPICS_UPDATE_ID_POOL_STATUS
    value: {{ .Values.kafka.topics.updateIdPoolStatus | quote }}
  - name: KAFKA_TOPICS_SAVE_IN_DISPATCH_LOG
    value: {{ .Values.kafka.topics.saveInDispatchLog | quote }}
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: ID_POOL_SEQ_CODE
    value: {{ .Values.idgen.pool.seqCode }}
  - name: IDGEN_RANDOM_BUFFER
    value: {{ .Values.idgen.random.buffer | quote }}
  - name: LIMIT_PER_USER
    value: {{ .Values.idgen.limit.perUser | quote }}
  - name: IDPOOL_FETCH_LIMIT_FROM_DB
    value: {{ .Values.idgen.fetch.limitFromDb | quote }}
  - name: MULTI_LOCK_WAIT_TIME
    value: {{ .Values.multiLock.waitTime | quote }}
  - name: MULTI_LOCK_LEASE_TIME
    value: {{ .Values.multiLock.leaseTime | quote }}
  - name: ID_POOL_CREATE_MAX_BATCH_SIZE
    value: {{ .Values.idPool.create.maxBatchSize | quote }}
  - name: ID_VALIDATION_ENABLED
    value: {{ .Values.idPool.validation.enabled | quote }}
  - name: SPRING_DATA_REDIS_DEFAULT_REPLENISHRATE
    value: "4"
  - name: SPRING_DATA_REDIS_DEFAULT_BURSTCAPACITY
    value: "4"
