# Common Labels
labels:
  app: "xstate-chatbot"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "xstate-chatbot"
  ip-whitelist: "0.0.0.0/0"
  additionalAnnotations: | 
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ index .Values "ingress" "ip-whitelist" | quote }}


# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "xstate_chatbot_schema"
    image:
      repository: "xstate-chatbot-db"

# Container Configs
image:
  repository: "xstate-chatbot"
replicas: "1"
tracing-enabled: true

# Additional Container Envs
env: |  
  - name: KAFKA_BOOTSTRAP_SERVER
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
  - name: DB_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-host
  - name: DB_NAME
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-name
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: GOOGLE_MAPS_API_KEY
    valueFrom:
      secretKeyRef:
        name: egov-location
        key: gmapskey
  - name: EGOV_SERVICES_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: EXTERNAL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: USER_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user-chatbot
  - name: MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: zuul
  - name: URL_SHORTNER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: PGR_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: zuul
  - name: LOCALIZATION_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: zuul
  - name: EGOV_FILESTORE_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: zuul
  - name: BILL_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: zuul
  - name: COLLECTION_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: zuul      
  - name: ROOT_TENANTID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: CONTEXT_PATH
    value: "/xstate-chatbot"
  - name: SERVICE_PORT
    value: "8080"
  - name: USER_SERVICE_HARDCODED_PASSWORD
    valueFrom:
      secretKeyRef:
        name: egov-user-chatbot
        key: citizen-login-password-otp-fixed-value
  - name: VALUEFIRST_USERNAME
    valueFrom:
      secretKeyRef:
        name: chatbot
        key: valuefirst-username
  - name: VALUEFIRST_PASSWORD
    valueFrom:
      secretKeyRef:
        name: chatbot
        key: valuefirst-password
  - name: TRACER_OPENTRACING_ENABLED
    value: "true"
  - name: FLOW_RESET_KEYWORDS
    value: "Hi,Hey,Hello,mseva,Start,missedCall"
  {{- if index .Values "contact-card-whatsapp-number" }}
  - name: CONTACT_CARD_WHATSAPP_NUMBER
    value: {{ index .Values "contact-card-whatsapp-number" | quote }}
  {{- end }}
  {{- if index .Values "contact-card-whatsapp-name" }}
  - name: CONTACT_CARD_WHATSAPP_NAME
    value: {{ index .Values "contact-card-whatsapp-name" | quote }}
  {{- end }}
  {{- if index .Values "valuefirst-whatsapp-number" }}
  - name: WHATSAPP_BUSINESS_NUMBER
    value: {{ index .Values "valuefirst-whatsapp-number" | quote }}
  {{- end }}
  {{- if index .Values "valuefirst-notification-assigned-templateid" }}
  - name: VALUEFIRST_NOTIFICATION_ASSIGNED_TEMPLATEID
    value: {{ index .Values "valuefirst-notification-assigned-templateid" | quote }}
  {{- end }}
  {{- if index .Values "valuefirst-notification-resolved-templateid" }}
  - name: VALUEFIRST_NOTIFICATION_RESOLVED_TEMPLATEID
    value: {{ index .Values "valuefirst-notification-resolved-templateid" | quote }}
  {{- end }}
  {{- if index .Values "valuefirst-notification-rejected-templateid" }}
  - name: VALUEFIRST_NOTIFICATION_REJECTED_TEMPLATEID
    value: {{ index .Values "valuefirst-notification-rejected-templateid" | quote }}
  {{- end }}
  {{- if index .Values "valuefirst-notification-reassigned-templateid" }}
  - name: VALUEFIRST_NOTIFICATION_REASSIGNED_TEMPLATEID
    value: {{ index .Values "valuefirst-notification-reassigned-templateid" | quote }}
  {{- end }}
  {{- if index .Values "valuefirst-notification-commented-templateid" }}
  - name: VALUEFIRST_NOTIFICATION_COMMENTED_TEMPLATEID
    value: {{ index .Values "valuefirst-notification-commented-templateid" | quote }}
  {{- end }}
  {{- if index .Values "valuefirst-notification-welcome-templateid" }}
  - name: VALUEFIRST_NOTIFICATION_WELCOME_TEMPLATEID
    value: {{ index .Values "valuefirst-notification-welcome-templateid" | quote }}
  {{- end }}
  {{- if index .Values "valuefirst-notification-root-templateid" }}
  - name: VALUEFIRST_NOTIFICATION_ROOT_TEMPLATEID
    value: {{ index .Values "valuefirst-notification-root-templateid" | quote }}
  {{- end }}
  {{- if index .Values "valuefirst-send-message-url" }}
  - name: VALUEFIRST_SEND_MESSAGE_URL
    value: {{ index .Values "valuefirst-send-message-url" | quote }}
  {{- end }}
  {{- if index .Values "whatsapp-provider" }}
  - name: WHATSAPP_PROVIDER
    value: {{ index .Values "whatsapp-provider" | quote }}
  {{- end }}
  {{- if index .Values "bill-supported-modules" }}
  - name: BILL_SUPPORTED_MODULES
    value: {{ index .Values "bill-supported-modules" | quote }}
  {{- end }}
  {{- if index .Values "pgr-version" }}
  - name: PGR_VERSION
    value: {{ index .Values "pgr-version" | quote }}
  {{- end }}
  {{- if index .Values "pgr-update-topic" }}
  - name: PGR_UPDATE_TOPIC
    value: {{ index .Values "pgr-update-topic" | quote }}
  {{- end }}
  {{- if index .Values "information-image-filestoreid" }}
  - name: INFORMATION_IMAGE_FILESTORE_ID
    value: {{ index .Values "information-image-filestoreid" | quote }}
  {{- end }}