# Common Labels
labels:
  app: "plan-service"
  group: "health"

namespace: health

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "plan-service"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "plan_schema"
    image:
      repository: "plan-service-db"

# Container Configs
image:
  repository: "plan-service"
replicas: "3"
healthChecks:
  enabled: true
  livenessProbePath: "/plan-service/health"
  readinessProbePath: "/plan-service/health"
appType: "java-spring"
tracing-enabled: true
memory_limits: 1Gi
heap: "-Xmx768m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"
egov-mdms-service-host-key: "mdms-service-v2"
egov-mdms-service-endpoint-key: "/mdms-v2/v1/_search"

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: plan-service
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id 
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: {{ index .Values "egov-mdms-service-host-key" | quote }}
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: {{ index .Values "egov-mdms-service-endpoint-key" | quote }}
  - name: EGOV_MDMS_SEARCH_V2_ENDPOINT
    value: {{ index .Values "egov-mdms-service-v2-endpoint-key" | quote }}
  - name: EGOV_MDMS_INTEGRATION_ENABLED
    value: "true"
  - name: EGOV_USER_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_PROJECT_FACTORY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: project-factory
  - name: EGOV_FACILITY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: facility
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: EGOV_BOUNDARY_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: boundary-service
  - name: EGOV_CENSUS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: census-service
  - name: WORKFLOW_INITIATE_ACTION
    value: "INITIATE"
  - name: WORKFLOW_INTERMEDIATE_ACTION
    value: "EDIT_AND_SEND_FOR_APPROVAL,APPROVE"
  - name: WORKFLOW_SEND_BACK_ACTION
    value: "SEND_BACK_FOR_CORRECTION"
  - name: ROLE_MAP
    value: "{'ROOT_FACILITY_CATCHMENT_MAPPER':'FACILITY_CATCHMENT_MAPPER', 'FACILITY_CATCHMENT_MAPPER':'ROOT_FACILITY_CATCHMENT_MAPPER', 'ROOT_POPULATION_DATA_APPROVER':'POPULATION_DATA_APPROVER', 'POPULATION_DATA_APPROVER':'ROOT_POPULATION_DATA_APPROVER', 'ROOT_PLAN_ESTIMATION_APPROVER':'PLAN_ESTIMATION_APPROVER', 'PLAN_ESTIMATION_APPROVER':'ROOT_PLAN_ESTIMATION_APPROVER'}"
  - name: PLAN_ESTIMATION_APPROVER_ROLES
    value: "ROOT_PLAN_ESTIMATION_APPROVER,PLAN_ESTIMATION_APPROVER"
  - name: FINAL_STATUS_FOR_PLAN_CONFIG
    value: EXECUTION_TO_BE_DONE
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-enable-debug" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: RESOURCE_CONFIG_CONSUMER_PLAN_CREATE_TOPIC
    value: "resource-microplan-create-topic"
  - name: PLAN_DEFAULT_LIMIT
    value: "50"
