{{- if .Values.master.ingress.enabled }}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: {{ .Values.master.ingress.apiVersion }}
{{- end }}
kind: Ingress
metadata:
  namespace: {{ template "jenkins.namespace" . }}
  labels:
{{- include "common.labels" . | nindent 4 }} 
{{- if .Values.master.ingress.annotations }}
  annotations:
{{ toYaml .Values.master.ingress.annotations | indent 4 }}
{{- end }}
  name: {{ template "jenkins.fullname" . }}
spec:
  rules:
  - http:
      paths:
{{- if len (.Values.master.ingress.paths) }}
{{ tpl (toYaml .Values.master.ingress.paths | indent 6) . }}
{{- else }}
      - backend:
          service:
            name: {{ template "jenkins.fullname" . }}
            port:
              number: {{ .Values.master.servicePort }}
{{- if .Values.master.ingress.path }}
        path: {{ .Values.master.ingress.path }}
        pathType: Prefix
{{- end }}
{{- end }}
    host: {{ .Values.global.domain }}
  tls:
  - hosts:
    - {{ .Values.global.domain }}
    secretName: {{ .Values.global.domain }}-tls-certs 
{{- end }}
