# Common Labels
name: kafka-connect
namespace: kafka-cluster    
labels:
  app: "kafka-connect"
  group: "infra"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: cp-kafka-connect
  tag: latest

replicas: "1"
httpPort: 8083
heap: "-Xms512M -Xmx512M"
config-storage-replication-factor: "3"
offset-storage-replication-factor: "3"
status-storage-replication-factor: "3"
memory_limits: 768Mi
resources: |
  requests:
    memory: {{ .Values.memory_limits | quote }}
  limits:
    memory: {{ .Values.memory_limits | quote }}

# Additional Container Envs
env: |
  - name: CONNECT_REST_ADVERTISED_HOST_NAME
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: CONNECT_BOOTSTRAP_SERVERS
    value: "PLAINTEXT://{{ index $.Values "cluster-configs" "configmaps" "egov-config" "data" "kafka-brokers" }}"
  - name: CONNECT_GROUP_ID
    value: {{ .Values.name }}
  - name: CONNECT_CONFIG_STORAGE_TOPIC
    value: {{ .Values.name }}-config
  - name: CONNECT_OFFSET_STORAGE_TOPIC
    value: {{ .Values.name }}-offset
  - name: CONNECT_STATUS_STORAGE_TOPIC
    value: {{ .Values.name }}-status
  - name: KAFKA_HEAP_OPTS
    value: {{ .Values.heap | quote }}
  - name: "CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR"
    value: {{ index .Values "config-storage-replication-factor" | quote }}
  - name: "CONNECT_INTERNAL_KEY_CONVERTER"
    value: "org.apache.kafka.connect.json.JsonConverter"
  - name: "CONNECT_INTERNAL_VALUE_CONVERTER"
    value: "org.apache.kafka.connect.json.JsonConverter"
  - name: "CONNECT_KEY_CONVERTER"
    value: "org.apache.kafka.connect.json.JsonConverter"
  - name: "CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE"
    value: "false"
  - name: "CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR"
    value: {{ index .Values "offset-storage-replication-factor" | quote }}
  - name: "CONNECT_PLUGIN_PATH"
    value: "/usr/share/java"
  - name: "CONNECT_STATUS_STORAGE_REPLICATION_FACTOR"
    value: {{ index .Values "status-storage-replication-factor" | quote }}
  - name: "CONNECT_VALUE_CONVERTER"
    value: "org.apache.kafka.connect.json.JsonConverter"
  - name: "CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE"
    value: "false"   