# Common Labels
labels:
  app: "digit-studio"
  group: "web"

namespace: studio

# Ingress Configs
ingress:
  enabled: true
  context: "digit-studio"

# Init Containers Configs
initContainers: {}

resources: |
  limits:
    cpu: "300m"
    memory: "512Mi"
  requests:
    cpu: "300m"
    memory: "512Mi"

# Container Configs
image:
  repository: "digit-studio"
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/digit-studio/"
  readinessProbePath: "/digit-studio/"

extraVolumes: |
  - name: js-injection
    configMap:
      name: digit-studio-js-injection

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
