# Common Labels
labels:
  app: "referralmanagement"
  group: "health"

namespace: health

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "referralmanagement"
 

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "referralmanagement_schema"
    image:
      repository: "referralmanagement-db"

# Container Configs
image:
  repository: "referralmanagement"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/referralmanagement/health"
  readinessProbePath: "/referralmanagement/health"
appType: "java-spring"
tracing-enabled: true
memory_limits: 768Mi
heap: "-Xmx384m -Xms384m"
java-args: ""
persist-yml-path: "file:///work-dir/configs/egov-persister/referral-management-persister.yml"
indexer-yml-path: "file:///work-dir/configs/egov-indexer/referral-management-indexer.yml"
egov-mdms-service-host-key: "egov-mdms-service"

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: health-referral-management
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_IDGEN_PATH
    value: "egov-idgen/id/_generate"
  - name: EGOV_IDGEN_INTEGRATION_ENABLED
    value: "true"
  - name: REFERRALMANAGEMENT.SIDEEFFECT.IDGEN.ID.FORMAT
    value: "referralmanagement.sideeffect.id"
  - name: REFERRALMANAGEMENT.REFERRAL.IDGEN.ID.FORMAT
    value: "referralmanagement.referral.id"
  - name: SPRING_REDIS_HOST
    value: redis.backbone
  - name: SPRING_REDIS_PORT
    value: "6379"
  - name: SPRING_CACHE_TYPE
    value: "redis"
  - name: SPRING_CACHE_REDIS_TIME-TO-LIVE
    value: "60"
  - name: SPRING_CACHE_AUTOEXPIRY
    value: "true"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-enable-debug" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user-egov
  - name: EGOV_SEARCH_USER_URL
    value: "/user/_search"
  - name: EGOV_USER_INTEGRATION_ENABLED
    value: "true"
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: EGOV_LOCATION_CONTEXT_PATH
    value: "/egov-location/location/v11"
  - name: EGOV_LOCATION_ENDPOINT
    value: "/boundarys/_search"
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: {{ index .Values "egov-mdms-service-host-key" | quote }}
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/egov-mdms-service/v1/_search"
  - name: EGOV_MDMS_INTEGRATION_ENABLED
    value: "true"
  - name: EGOV_MDMS_MASTER_NAME
    value: "referralmanagement_master"
  - name: EGOV_MDMS_MODULE_NAME
    value: "referralmanagement"
  - name: EGOV_HOUSEHOLD_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: household
  - name: EGOV_SEARCH_HOUSEHOLD_URL
    value: "/household/v1/_search"
  - name: EGOV_SEARCH_HOUSEHOLD_MEMBER_URL
    value: "/household/member/v1/_search"
  - name: EGOV_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: health-individual
  - name: EGOV_SEARCH_INDIVIDUAL_URL
    value: "/health-individual/v1/_search"
  - name: EGOV_PRODUCT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: product
  - name: EGOV_SEARCH_PRODUCT_VARIANT_URL
    value: "/product/variant/v1/_search"
  - name: EGOV_PROJECT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: health-project
  - name: EGOV_SEARCH_PROJECT_TASK_URL
    value: "/health-project/task/v1/_search"
  - name: EGOV_SEARCH_PROJECT_BENEFICIARY_URL
    value: "/health-project/beneficiary/v1/_search"
  - name: EGOV_SEARCH_PROJECT_STAFF_URL
    value: "/health-project/staff/v1/_search"
  - name: REFERRALMANAGEMENT.SIDEEFFECT.KAFKA.CREATE.TOPIC
    value: "save-side-effect-health-topic"
  - name: REFERRALMANAGEMENT.SIDEEFFECT.KAFKA.UPDATE.TOPIC
    value: "update-side-effect-health-topic"
  - name: REFERRALMANAGEMENT.SIDEEFFECT.KAFKA.DELETE.TOPIC
    value: "delete-side-effect-health-topic"
  - name: REFERRALMANAGEMENT.SIDEEFFECT.CONSUMER.BULK.CREATE.TOPIC
    value: "save-side-effect-bulk-health-topic"
  - name: REFERRALMANAGEMENT.SIDEEFFECT.CONSUMER.BULK.UPDATE.TOPIC
    value: "update-side-effect-bulk-health-topic"
  - name: REFERRALMANAGEMENT.SIDEEFFECT.CONSUMER.BULK.DELETE.TOPIC
    value: "delete-side-effect-bulk-health-topic"
  - name: REFERRALMANAGEMENT.REFERRAL.KAFKA.CREATE.TOPIC
    value: "save-referral-health-topic"
  - name: REFERRALMANAGEMENT.REFERRAL.KAFKA.UPDATE.TOPIC
    value: "update-referral-health-topic"
  - name: REFERRALMANAGEMENT.REFERRAL.KAFKA.DELETE.TOPIC
    value: "delete-referral-health-topic"
  - name: REFERRALMANAGEMENT.REFERRAL.CONSUMER.BULK.CREATE.TOPIC
    value: "save-referral-bulk-health-topic"
  - name: REFERRALMANAGEMENT.REFERRAL.CONSUMER.BULK.UPDATE.TOPIC
    value: "update-referral-bulk-health-topic"
  - name: REFERRALMANAGEMENT.REFERRAL.CONSUMER.BULK.DELETE.TOPIC
    value: "delete-referral-bulk-health-topic"
  - name: REFERRALMANAGEMENT.HFREFERRAL.KAFKA.CREATE.TOPIC
    value: "save-hfreferral-health-topic"
  - name: REFERRALMANAGEMENT.HFREFERRAL.KAFKA.UPDATE.TOPIC
    value: "update-hfreferral-health-topic"
  - name: REFERRALMANAGEMENT.HFREFERRAL.KAFKA.DELETE.TOPIC
    value: "delete-hfreferral-health-topic"
  - name: REFERRALMANAGEMENT.HFREFERRAL.CONSUMER.BULK.CREATE.TOPIC
    value: "save-hfreferral-bulk-health-topic"
  - name: REFERRALMANAGEMENT.HFREFERRAL.CONSUMER.BULK.UPDATE.TOPIC
    value: "update-hfreferral-bulk-health-topic"
  - name: REFERRALMANAGEMENT.HFREFERRAL.CONSUMER.BULK.DELETE.TOPIC
    value: "delete-hfreferral-bulk-health-topic"
  
  - name: SEARCH_API_LIMIT
    value: "1000"
  - name: REFERRALMANAGEMENT.DOCUMENT.ID.VERIFICATION.REQUIRED
    value: "false"
  - name: REFERRALMANAGEMENT.DEFAULT.OFFSET
    value: "0"
  - name: REFERRALMANAGEMENT.DEFAULT.LIMIT
    value: "100"
  - name: REFERRALMANAGEMENT.SEARCH.MAX.LIMIT
    value: "200"
  - name: EGOV.IDGEN.PROJECT.NUMBER.NAME
    value: "project.number"
  - name: PROJECT.RESOURCE.IDGEN.ID.FORMAT
    value: "project.resource.id"
  - name: EGOV_FACILITY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: facility
  - name: EGOV_SEARCH_FACILITY_URL
    value: "/facility/v1/_search"
  - name: EGOV_SEARCH_PROJECT_FACILITY_URL: 
    value: "/project/facility/v1/_search"
  - name: PROJECT_MDMS_MODULE
    value: "HCM-PROJECT-TYPES"
  - name: EGOV_LOCATION_HIERARCHY_TYPE
    value: "ADMIN"
  - name: EGOV_LOCATION_CODE_QUERY_PARAM
    value: "code"
