{{- with index .Values "cluster-configs" "secrets" "chatbot" }}
{{- if index . "valuefirst-password" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  valuefirst-username: {{ index . "valuefirst-username" | b64enc | quote }}
  valuefirst-password: {{ index . "valuefirst-password" | b64enc | quote }}
  {{- if index . "twilio-account-sid" }}
  twilio-account-sid: {{ index . "twilio-account-sid" | b64enc | quote }}
  {{- end }}
  {{- if index . "twilio-auth-token" }}
  twilio-auth-token: {{ index . "twilio-auth-token" | b64enc | quote }}
  {{- end }}
  {{- if index . "twilio-whatsapp-number" }}
  twilio-whatsapp-number: {{ index . "twilio-whatsapp-number" | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}