{{- with index .Values "cluster-configs" "secrets" "covid-chatbot" }}
{{- if index . "valuefirst-password" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  valuefirst-username: {{ index . "valuefirst-username" | b64enc | quote }}
  valuefirst-password: {{ index . "valuefirst-password" | b64enc | quote }}
{{- end }}
{{- end }}