{{- with index .Values "cluster-configs" "secrets" "egov-notification-sms" }}
{{- if index . "password" }}
---
{{- range $ns := .namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $.Values "cluster-configs" "secrets" "egov-notification-sms" "name" }}
  namespace: {{ $ns }}
type: Opaque
data:
  username: {{ index .Values "cluster-configs" "secrets" "egov-notification-sms" "username" | b64enc | quote }}
  password: {{ index .Values "cluster-configs" "secrets" "egov-notification-sms" "password" | b64enc | quote }}
{{- if index .Values "cluster-configs" "secrets" "egov-notification-sms" "secure-key" }}
  secure-key: {{ index .Values "cluster-configs" "secrets" "egov-notification-sms" "secure-key" | b64enc | quote }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}
