{{- with index .Values "cluster-configs" "secrets" "egov-malware-detection" }}
{{- if index . "slack-webhook-url" }}
---
{{- range $ns := .namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $.Values "cluster-configs" "secrets" "egov-malware-detection" "name" }}
  namespace: {{ $ns }}
type: Opaque
data:
  slack-webhook-url: {{ index $.Values "cluster-configs" "secrets" "egov-malware-detection" "slack-webhook-url" | b64enc | quote }}
  mail-alert-recipients: {{ index $.Values "cluster-configs" "secrets" "egov-malware-detection" "mail-alert-recipients" | b64enc | quote }}
---
{{- end }}
{{- end }}
{{- end }}

