{{- with index .Values "cluster-configs" "secrets" "egov-filestore" }}
{{- if index . "aws-secret-key" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  awskey: {{ index . "aws-key" | b64enc | quote }}
  awssecretkey: {{ index . "aws-secret-key"  | b64enc | quote }}
{{- end }}
{{- end }}