{{- with index .Values "cluster-configs" "secrets" "hcm-moz-impl" }}
{{- if index . "kubeconfig" }}
{{- if index . "awssecretkey" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  kubeconfig: {{ index . "kubeconfig" | b64enc | quote }}
  githubusername: {{ index . "githubusername"  | b64enc | quote }}
  githubpat: {{ index . "githubpat"  | b64enc | quote }}
  dhis2user: {{ index . "dhis2user"  | b64enc | quote }}
  dhis2pass: {{ index . "dhis2pass"  | b64enc | quote }}
  awskey: {{ index . "aws-key" | b64enc | quote }}
  awssecretkey: {{ index . "awssecretkey"  | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
