{{- with index .Values "cluster-configs" "secrets" "keycloak" }}
{{- if index . "keycloak-admin-user" }}
---
{{- range $ns := .namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $.Values "cluster-configs" "secrets" "keycloak" "name" }}
  namespace: {{ $ns }}
type: Opaque
data:
  keycloak-admin-user: {{ index $.Values "cluster-configs" "secrets" "keycloak" "keycloak-admin-user" | b64enc | quote }}
  keycloak-admin-pass: {{ index $.Values "cluster-configs" "secrets" "keycloak" "keycloak-admin-pass" | b64enc | quote }}
  citizen-broker-client-id: {{ index $.Values "cluster-configs" "secrets" "keycloak" "citizen-broker-client-id" | b64enc | quote }}
  citizen-broker-client-secret: {{ index $.Values "cluster-configs" "secrets" "keycloak" "citizen-broker-client-secretd" | b64enc | quote }}
{{- end }}
---
{{- end }}
{{- end }}

