{{- with index .Values "cluster-configs" "secrets" "vault-root-token" }}
{{- if index . "token" }}
---
{{- range $ns := .namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $.Values "cluster-configs" "secrets" "vault-root-token" "name" }}
  namespace: {{ $ns }}
type: Opaque
data:
 token: {{ index $.Values "cluster-configs" "secrets" "vault-root-token" "token" | b64enc | quote }}
 {{- end }}
---
{{- end }}
{{- end }}
