# Common Labels
labels:
  app: "egov-filestore"
  group: "core"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_filestore_schema"
    image:
      repository: "egov-filestore-db"

# Ingress Configs
ingress:
  zuul: true
  context: "filestore"

# Container Configs
image:
  repository: "egov-filestore"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/filestore/health"
  readinessProbePath: "/filestore/health"
appType: "java-spring"
tracing-enabled: true
is-bucket-fixed: "true"
fixed-bucketname: "unified-dev-bucket-s3"
heap: "-Xmx192m -Xms192m"
file-storage-mount-path: "/filestore"
is-nfs-enabled: false
is-s3-enabled: true

persistence:
  enabled: false

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false" 
  - name: FILE_STORAGE_MOUNT_PATH
    value: {{ index .Values "file-storage-mount-path" | quote }}
  - name: TEMP_FOLDER_PATH
    value: "/tmp"
  - name: SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE
    value: "6MB"
  - name: ISNFSSTORAGEENABLED
    value: {{ index .Values "is-nfs-enabled" | quote }}
  {{- if index .Values "is-nfs-enabled" }}
  - name: ISNFSSTORAGEENABLED
    value: "true"
  - name: DISK_STORAGE_HOST_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: SOURCE_DISK
    value: "diskStorage"
  {{- end }}
  {{- if index .Values "is-s3-enabled" }}
  - name: ISS3ENABLED
    value: "true"
  {{- end }}  
  {{- if index .Values "minio-enabled" }}
  - name: AWS_KEY
    valueFrom:
      secretKeyRef:
        key: accesskey
        name: minio
  - name: AWS_SECRETKEY
    valueFrom:
      secretKeyRef:
        key: secretkey
        name: minio
  {{else}}
  - name: AWS_KEY
    valueFrom:
      secretKeyRef:
        name: egov-filestore
        key: awskey
  - name: AWS_SECRETKEY
    valueFrom:
      secretKeyRef:
        name: egov-filestore
        key: awssecretkey
  {{- end }}
  {{- if index .Values "is-bucket-fixed" }}
  - name: IS_BUCKET_FIXED
    value: {{ index .Values "is-bucket-fixed" | quote }}
  {{- end }}
  {{- if index .Values "fixed-bucketname" }}
  - name: FIXED_BUCKETNAME
    value: {{ index .Values "fixed-bucketname" | quote }}
  {{- end }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: ALLOWED_FORMATS_MAP
    value: {{ index .Values "allowed-file-formats-map" | quote }}
  {{- if index .Values "minio-enabled" }}  
  - name: MINIO_URL
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: minio-url
  {{- end }}
  {{- if index .Values "filestore-url-validity" }}   
  - name: PRESIGNED_URL_EXPIRY_TIME_IN_SECS     
    value: {{ index .Values "filestore-url-validity" | quote }}   
  {{- end }}  

