# Common Labels
labels:
  app: "echallan-services"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "echallan-services"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "echallan_services_schema"
    image:
      repository: "echallan-services-db"

# Container Configs
image:
  repository: "echallan-services"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/echallan-services/health"
  readinessProbePath: "/echallan-services/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"
egov-msg-pay-link: citizen/withoutAuth/egov-common/pay?consumerCode=$consumercode&tenantId=$tenantId&businessService=$businessservice

# Additional Container Envs
env: |
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: EGOV_EDCR_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_BILLINGSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: billing-service
  - name: EGOV_ECHALLAN_CALCULATOR_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: echallan-calculator
  - name: EGOV_URL_SHORTNER_HOST 
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-url-shortening
  - name: EGOV_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore               
  - name: EGOV_UI_APP_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: WORKFLOW_CONTEXT_PATH
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: EGOV_COLLECTION_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: collection-services
  - name: BILLING.SERVICE.HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: billing-service
  - name: SMS_EXPENDITURE_ENABLED
    value: {{ index .Values "sms-expenditure-enabled" | quote }}
  - name: SMS_EXPENDITURE_MARK_BILL_ENABLED
    value: {{ index .Values "sms-expenditure-mark-bill-enabled" | quote }}
  - name: SMS_MONTHY_SUMMARY_ENABLED
    value: {{ index .Values "sms-monthy-summary-enabled" | quote }}
  - name: EGOV_COLLECTION_SERVICE_CREATE_ENDPOINT
    value: "/collection-services/payments/_create"
  - name: EGOV_COLLECTION_SERVICE_SEARCH
    value: "/collection-services/payments/_search"
  - name: EGOV_COLLECTION_SERVICE_UPDATE
    value: "/collection-services/payments/EXPENSE/_workflow"
  - name: EGOV_BILLING_SERICE_SEARCH_PATH
    value: "/billing-service/bill/v2/_search"
  - name: EGOV_VENDOR_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: vendor
  - name: EGOV_VENDOR_CONTEXT_PATH
    value: "/vendor/v1"   
  - name: EGOV_VENDOR_SEARCH_PATH
    value: "/_search"     
  - name: WORKFLOW_TRANSITION_PATH
    value: "egov-workflow-v2/egov-wf/process/_transition"
  - name: EGOV_MSG_PAY_LINK
    value: {{ index .Values "egov-msg-pay-link" | quote }}
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-echallan-services
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: EGOV_IDGEN_CHALLANNUM_FORMAT
    value: {{ index .Values "egov-idgen-challanNum-format" | quote }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
