{{- define "common.service" -}}
{{- $envOverrides := index .Values (tpl .Chart.Name .) -}} 
{{- $baseCommonValues := .Values.common | deepCopy -}}
{{- $values := dict "Values" (mustMergeOverwrite $baseCommonValues .Values $envOverrides) -}}
{{- with mustMergeOverwrite . $values }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}  
  annotations: 
{{- if .Values.metrics }}   
    prometheus.io/path: {{ .Values.metrics.path | quote }}
    prometheus.io/port: {{ .Values.metrics.port | quote }}
    prometheus.io/scrape: "true"  
{{- end }}
{{- if .Values.ingress.zuul }} 
    zuul/route-path: {{ .Values.ingress.context }}
{{- end }}
  labels:
{{- include "common.labels" . | nindent 4 }}   
spec:
  selector: 
{{- include "common.labels" . | nindent 4 }}    
  ports:
  - port: {{ .Values.httpPort }}
    targetPort: {{ .Values.httpPort }}  
{{- end -}}
{{- end -}}