# Common Labels
labels:
  app: "tl-calculator"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "tl-calculator"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "tl_calculator_schema"
    image:
      repository: "tl-calculator-db"

# Container Configs
image:
  repository: "tl-calculator"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/tl-calculator/health"
  readinessProbePath: "/tl-calculator/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: "-Dspring.profiles.active=monitoring"

# Additional Container Envs
env: |
  - name: SERVER_CONTEXTPATH
    value: /tl-calculator
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: tl-calculator
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: KAFKA_TOPICS_SAVE_SERVICE
    value: save-tl-billingslab
  - name: KAFKA_TOPICS_UPDATE_SERVICE
    value: update-tl-billingslab
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: /egov-mdms-service/v1/_search
  - name: EGOV_BILLINGSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: billing-service
  - name: EGOV_TRADELICENSE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: tl-services
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
