# Common Labels
labels:
  app: "egov-common-masters"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "egov-common-masters"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_common_masters_schema"
    image:
      repository: "egov-common-masters-db"

# Container Configs
image:
  repository: "egov-common-masters"
replicas: "1"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx384m -Xms256m"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: KAFKA_TOPICS_HOLIDAY_NAME
    value: egov-common-holiday
  - name: KAFKA_TOPICS_HOLIDAY_ID
    value: egov-common-holiday
  - name: KAFKA_TOPICS_HOLIDAY_GROUP
    value: egov-common-holiday
  {{- if index .Values "global" "serializers-timezone-in-ist" }}
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
  {{- end }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: EGOV_SERVICES_ESINDEXER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: es-indexer-host
