# Common Labels
labels:
  app: "stock"
  group: "health"

namespace: health

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "stock"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "stock_schema"
    image:
      repository: "stock-db"

# Container Configs
image:
  repository: "stock"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/stock/health"
  readinessProbePath: "/stock/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""
persist-yml-path: "file:///work-dir/health-campaign-config/egov-persister/stock-persister.yml"
indexer-yml-path: "file:///work-dir/health-campaign-config/egov-indexer/stock-indexer.yml"

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: health-stock
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_IDGEN_PATH
    value: "egov-idgen/id/_generate"
  - name: EGOV_IDGEN_INTEGRATION_ENABLED
    value: "true"
  - name: STOCK.IDGEN.ID.FORMAT
    value: "stock.id"
  - name: STOCK.RECONCILIATION.IDGEN.ID.FORMAT
    value: "stock.reconciliation.id"
  - name: SPRING_REDIS_HOST
    value: redis.backbone
  - name: SPRING_REDIS_PORT
    value: "6379"
  - name: SPRING_CACHE_TYPE
    value: "redis"
  - name: SPRING_CACHE_REDIS_TIME-TO-LIVE
    value: "60"
  - name: SPRING_CACHE_AUTOEXPIRY
    value: "true"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-enable-debug" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: EGOV_PRODUCT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: product
  - name: EGOV_SEARCH_PRODUCT_VARIANT_URL
    value: "/product/variant/v1/_search"
  - name: STOCK.KAFKA.CREATE.TOPIC
    value: "save-stock-topic"
  - name: STOCK.KAFKA.UPDATE.TOPIC
    value: "update-stock-topic"
  - name: STOCK.KAFKA.DELETE.TOPIC
    value: "delete-stock-topic"
  - name: STOCK.CONSUMER.BULK.DELETE.TOPIC
    value: "delete-stock-bulk-topic"
  - name: STOCK.CONSUMER.BULK.CREATE.TOPIC
    value: "create-stock-bulk-topic"
  - name: STOCK.CONSUMER.BULK.UPDATE.TOPIC
    value: "update-stock-bulk-topic"
  - name: SEARCH_API_LIMIT
    value: "1000"
  - name: STOCK.RECONCILIATION.KAFKA.CREATE.TOPIC
    value: "save-stock-reconciliation-topic"
  - name: STOCK.RECONCILIATION.KAFKA.UPDATE.TOPIC
    value: "update-stock-reconciliation-topic"
  - name: STOCK.RECONCILIATION.KAFKA.DELETE.TOPIC
    value: "delete-stock-reconciliation-topic"
  - name: STOCK.RECONCILIATION.CONSUMER.BULK.DELETE.TOPIC
    value: "delete-stock-reconciliation-bulk-topic"
  - name: STOCK.RECONCILIATION.CONSUMER.BULK.CREATE.TOPIC
    value: "create-stock-reconciliation-bulk-topic"
  - name: STOCK.RECONCILIATION.CONSUMER.BULK.UPDATE.TOPIC
    value: "update-stock-reconciliation-bulk-topic"
  - name: EGOV_FACILITY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: facility
  - name: EGOV_SEARCH_FACILITY_URL
    value: "/facility/v1/_search"
  - name: EGOV_PROJECT_FACILITY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: project
  - name: EGOV_SEARCH_PROJECT_FACILITY_URL
    value: "/project/facility/v1/_search"
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV.USER.CONTEXT.PATH
    value: "/user/users"
  - name: EGOV.CREATE.USER.PATH
    value: "/_createnovalidate"
  - name: EGOV_SEARCH_USER_URL
    value: "/user/_search"
  - name: EGOV.UPDATE.USER.URL
    value: "/_updatenovalidate"
  - name: EGOV.USER.INTEGRATION.ENABLED
    value: "true"
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/egov-mdms-service/v1/_search"
  - name: EGOV.MDMS.MASTER.NAME
  - name: EGOV.MDMS.MASTER.NAME
  - name: EGOV.MDMS.INTEGRATION.ENABLED
    value: "false"
