apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "name" . }}
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      app: {{ template "name" . }}
      kubernetes.io/cluster-service: "true"
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - name: fluent-bit
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 2020
          env:
            - name: KAFKA_BROKERS
              value: {{ index $.Values "cluster-configs" "configmaps" "egov-config" "data" "kafka-infra-brokers" | quote }}   
            - name: KAFKA_EGOV_SERVICES_LOGS_TOPIC
              value: {{ index .Values "egov-services-log-topic" | quote }}
            - name: KAFKA_EGOV_INFRA_LOGS_TOPIC
              value: {{ index .Values "egov-infra-log-topic" | quote }}   
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: {{ template "name" . }}-config
              mountPath: /fluent-bit/etc/
      affinity: {}       
      terminationGracePeriodSeconds: 10
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: {{ template "name" . }}-config
          configMap:
            name: {{ template "name" . }}-config
      serviceAccountName: {{ template "name" . }}
      serviceAccount: {{ template "name" . }} 
