apiVersion: v1
data:
  zookeeper-config: |
    {{conf['zookeeper-config']['data']}}
kind: ConfigMap
metadata:
  name: zookeeper-config
  namespace: backbone
---
apiVersion: v1
data:
  sms-enabled: "{{conf['egov-config']['sms-enabled']}}"
  es-log-request: "{{conf['egov-config']['es-log-request']}}"
  db-url: {{conf['egov-config']['db-url']}}
  kafka-brokers: {{conf['egov-config']['kafka-brokers']}}
  spring-datasource-tomcat-initialSize: "{{conf['egov-config']['spring-datasource-tomcat-initialSize']}}"
  es-indexer-host: {{conf['egov-config']['es-indexer-host']}}
  es-host: {{conf['egov-config']['es-host']}}
  flyway-locations: {{conf['egov-config']['flyway-locations']}}
  timezone: "{{conf['time-config']['timezone']}}"

kind: ConfigMap
metadata:
  name: egov-config
  namespace: egov
---
apiVersion: v1
data:
  topics: {{conf['kafka-config']['topics']}}
  zookeeper-connect: {{conf['kafka-config']['zookeeper-connect']}}
  kafka-brokers: {{conf['kafka-config']['kafka-brokers']}}
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: backbone
---
apiVersion: v1
data:
  es-host: "{{conf['logging-config']['es-host']}}"
  es-port: "{{conf['logging-config']['es-port']}}"
kind: ConfigMap
metadata:
  name: logging-config
  namespace: logging
{% if conf['es-alerts']%}
---
apiVersion: v1
data:
  es-host: "{{conf['es-alerts']['es-host']}}"
  es-port: "{{conf['es-alerts']['es-port']}}"
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: monitoring
{% endif %}

{% if conf['egov-user']['flyway-locations']%}
---
apiVersion: v1
data:
  flyway-locations: "{{conf['egov-user']['flyway-locations']}}"
kind: ConfigMap
metadata:
  name: egov-user
  namespace: egov
{% endif %}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-configuration
  namespace: monitoring
  labels:
    app: jaeger
    jaeger-infra: configuration
data:
  span-storage-type: elasticsearch
  collector: |
    es:
      server-urls: {{conf['egov-config']['es-indexer-host']}}
    collector:
      zipkin:
        http-port: 9411
  query: |
    es:
      server-urls: {{conf['egov-config']['es-indexer-host']}}
  agent: |
    collector:
      host-port: "jaeger-collector:14267"
  sampling-strategies: |
    {
    "service_strategies": [
        {
        "service": "egov-user",
        "type": "probabilistic",
        "param": 0.5,
        "operation_strategies": [
            { "operation": "query", "type": "probabilistic", "param": 0.1 }
        ]
        },
        {
        "service": "zuul",
        "type": "probabilistic",
        "param": 0.1
        }        
    ],
    "default_strategy": { "type": "probabilistic", "param": 1 }
    }
