# Common Labels
labels:
  app: "account"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "account"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "account_schema"
    image:
      repository: "account-db"

# Container Configs
image:
  repository: "account"
replicas: 1
appType: "go"
tracing-enabled: true
memory_limits: 512Mi
healthChecks:
  enabled: false
  livenessProbePath: "/health"
  readinessProbePath: "/health"
# Resource configuration for Go service
resources: |
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "200m"
    memory: "512Mi"


# Additional Container Envs
env: |
  - name: DB_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-host
  - name: DB_PORT
    value: "5432"
  - name: DB_USER
    valueFrom:
        secretKeyRef:
          name: db
          key: username
  - name: DB_PASSWORD
    valueFrom:
        secretKeyRef:
          name: db
          key: password
  - name: DB_NAME
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-name
  - name: DB_SSL_MODE
    value: "require"
  - name: SERVER_PORT
    value: "8080"
  - name: KEYCLOAK_BASE_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: keycloak-base-url
  - name: KEYCLOAK_ADMIN_USER
    valueFrom:
      secretKeyRef:
        name: keycloak
        key: keycloak-admin-user
  - name: KEYCLOAK_ADMIN_PASS
    valueFrom:
      secretKeyRef:
        name: keycloak
        key: keycloak-admin-pass
  - name: GIN_MODE
    value: "release"
  - name: CITIZEN_BROKER_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: keycloak
        key: citizen-broker-client-id
  - name: CITIZEN_BROKER_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: keycloak
        key: citizen-broker-client-secret
  - name: NOTIFICATION_BASE_URL
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: notification 
