# Common Labels
labels:
  app: "firenoc-services"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "firenoc-services"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "firenoc_services_schema"
    image:
      repository: "firenoc-services-db"
    env: |
        {{- if index .Values "firenoc-ismultischema-enabled" }}        
        - name: SCHEMA_NAME
          value: {{ index .Values "firenoc-schemas" | quote }}
        {{- end }}
        - name: "DB_URL"
          valueFrom: 
            configMapKeyRef: 
              name: egov-config
              key: db-url
        - name: "SCHEMA_TABLE"
          value: {{ .Values.initContainers.dbMigration.schemaTable | quote }}              
        - name: "FLYWAY_USER"
          valueFrom: 
            secretKeyRef: 
                name: db
                key: flyway-username
        - name: "FLYWAY_PASSWORD"
          valueFrom:
            secretKeyRef: 
                name: db
                key: flyway-password
        - name: "FLYWAY_LOCATIONS"
          valueFrom: 
            configMapKeyRef: 
                name: egov-config
                key: flyway-locations

# Container Configs
image:
  repository: "firenoc-services"
replicas: "1"
appType: "java-spring"
tracing-enabled: true

# Additional Container Envs
env: |
  - name: DB_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-host
  - name: DB_NAME
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-name
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: internal-gateway
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: EGOV_PROPERTY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: pt-services-v2
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_FN_CALCULATOR_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: internal-gateway
  - name: EGOV_HOST_BASE_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  {{- if index .Values "global" "is-environment-central-instance" }}        
  - name: IS_ENVIRONMENT_CENTRAL_INSTANCE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: is-environment-central-instance
  {{- end }}
  {{- if index .Values "global" "is-environment-central-instance" }}        
  - name: STATE_LEVEL_TENANTID_LENGTH
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: state-level-tenantid-length
  {{- end }}
  {{- if index .Values "egov-state-level-tenant-id" }}
  - name: EGOV_DEFAULT_STATE_ID
    value: {{ index .Values "egov-state-level-tenant-id" | quote }}
  {{- end }}
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/egov-mdms-service/v1/_search"
  - name: DB_PORT
    value: "5432"          
  - name: KAFKA_TOPICS_FIRENOC_CREATE
    value: "save-fn-firenoc"
  - name: KAFKA_TOPICS_FIRENOC_UPDATE
    value: "update-fn-firenoc"
  - name: KAFKA_TOPICS_FIRENOC_WORKFLOW
    value: "update-fn-workflow" 
  - name: KAFKA_TOPICS_RECEIPT_CREATE
    value: "egov.collection.payment-create"   
  - name: KAFKA_TOPICS_NOTIFICATION_SMS
    value: "egov.core.notification.sms"
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-firenoc-services
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: WORKFLOW_CONTEXT_PATH
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: WORKFLOW_TRANSITION_PATH
    value: "egov-workflow-v2/egov-wf/process/_transition"
  - name: KAFKA_BROKER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
  - name: SERVER_PORT
    value: "8080"
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: state-level-tenant-id
  {{- if index .Values "cluster-configs" "configmaps" "egov-config" "data" "is-environment-central-instance" }}        
  - name: IS_ENVIRONMENT_CENTRAL_INSTANCE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: is-environment-central-instance
  {{- end }}      
