apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ service_name }}
  namespace: egov
spec:
  replicas: {{ '{{' }}conf['{{ service_name }}']['replicas']{{ '}}' }}
  template:
    metadata:
      labels:
        app: {{ service_name }}
        group: {{ project }}
{%  if (db_migration) %}
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "{{ service_name }}-db-migration",
            "image": "{{ '{{' }}conf["{{ service_name }}"]["db_migration_image"]{{ '}}' }}",
            "env": [
              {"name": "DB_URL", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "db-url"}}},
              {"name": "SCHEMA_TABLE", "value": "{{ service_schema }}"},
              {"name": "FLYWAY_USER", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-username"}}},
              {"name": "FLYWAY_PASSWORD", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-password"}}},
              {"name": "FLYWAY_LOCATIONS", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "flyway-locations"}}}
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
{% endif %}
    spec:
      containers:
      - name: {{ service_name }}
        image: {{ '{{' }}conf['{{ service_name }}']['images'][0]{{ '}}' }}
        ports:
        - containerPort: 8080
        env:
{{ environment_variables }}
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory : {{ '{{' }}conf['{{ service_name }} ']['memory_limits']{{ '}}' }} or "256Mi"
