# Common Labels
labels:
  app: "frontend-mgramseva"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "mgramseva"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "frontend-mgramseva"
replicas: "2"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/mgramseva/"
  readinessProbePath: "/mgramseva/"
dashboard-url: ""

namespace: mgramseva 
memory_limits: "768Mi"  
extraVolumes: |
  - name: js-injection
    configMap:
      name: frontend-mgramseva-js-injection
extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf


