# Common Labels
labels:
  app: "egov-notification-mail"
  group: "core"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "egovio/egov-notification-mail"
replicas: "1"
appType: "java-spring"
tracing-enabled: true
username: "egov-micro.services@egovernments.org"
heap: "-Xmx192m -Xms192m"

# Additional Container Envs
env: |
  - name: KAFKA_TOPICS_NOTIFICATION_MAIL_NAME
    value: egov.core.notification.email
  - name: KAFKA_TOPICS_NOTIFICATION_MAIL_ID
    value: egov.core.notification.email
  - name: KAFKA_TOPICS_NOTIFICATION_MAIL_GROUP
    value: egov.core.notification.email
  - name: MAIL_SENDER_USERNAME
    value: {{ index .Values "username" | quote }}
  - name: MAIL_SENDER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: egov-notification-mail
        key: mailsenderpassword                   
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}

