# Common Labels
labels:
  app: "audit-service"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "audit-service"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "audit_service_schema"
    image:
      repository: "audit-service-db"

# Container Configs
image:
  repository: "audit-service"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/audit-service/health"
  readinessProbePath: "/audit-service/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
memory_limits: 512Mi
java-args: "-Dspring.profiles.active=monitoring"

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: audit-service
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: PROCESS_AUDIT_LOGS_KAFKA_TOPIC
    value: process-audit-records
  - name: PERSIST_AUDIT_LOGS_KAFKA_TOPIC
    value: persist-audit-records
  - name: EGOV_PERSIST_YML_REPO_PATH
    value: {{ index .Values "persist-yml-path" | quote }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: EGOV_ENC_SIGN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-enc-service