{{- $serviceName := include "nginx-ingress.name" . -}}
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: {{ template "nginx-ingress.name" . }}
  name: {{ template "nginx-ingress.fullname" . }}
  namespace: {{ .Values.namespace }}  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "nginx-ingress.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "nginx-ingress.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
{{- end -}}
