# Common Labels
labels:
  app: "echallan-calculator"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  namespace: "upyog"
  context: "echallan-calculator"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "echallan-calculator"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/echallan-calculator/health"
  readinessProbePath: "/echallan-calculator/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx384m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"

# Additional Container Envs
env: |
  - name: SERVER_CONTEXTPATH
    value: /echallan-calculator
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: echallan-calculator
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: KAFKA_TOPICS_UPDATE_SERVICE
    value: update-bpa-billingslab
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: /egov-mdms-service/v1/_search
  - name: EGOV_BILLINGSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: billing-service
  - name: EGOV_EDCR_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user        
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
