apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.stage.name }} 
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.clusterIssuer.stage.acme.server }} 
    # Email address used for ACME registration
    email: {{ .Values.clusterIssuer.stage.acme.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.stage.acme.secretName }}
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class:  nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.prod.name }}
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.clusterIssuer.prod.acme.server }}    
    # Email address used for ACME registration
    email: {{ .Values.clusterIssuer.prod.acme.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.prod.acme.secretName }}
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx 