{{- if .Values.query.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-query
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "name" . }}
    app.kubernetes.io/component: query
{{- if .Values.query.service.annotations }}
  annotations:
    {{- toYaml .Values.query.service.annotations | nindent 4 }}
{{- end }}
spec:
  ports:
  - name: query
    port: {{ .Values.query.service.port }}
    protocol: TCP
    targetPort: query
{{- if and (eq .Values.query.service.type "NodePort") (.Values.query.service.nodePort) }}
    nodePort: {{ .Values.query.service.nodePort }}
{{- end }}
  - name: admin
    port: 16687
    protocol: TCP
    targetPort: admin
  - name: jaeger-query
    port: 16686
    protocol: TCP
    targetPort: 16686  
  selector:
    app: {{ template "name" . }}
    app.kubernetes.io/component: query
  type: {{ .Values.query.service.type }}
{{- end -}}
