# Common Labels
labels:
  app: "egov-notification-mail"
  group: "core"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "egov-notification-mail"
  tag: core-2.9-lts-mvn-check-c33cfe45ab-4
replicas: "1"
appType: "java-spring"
tracing-enabled: true
username: "egov-testing@egovernments.org"
heap: "-Xmx192m -Xms192m"

# Additional Container Envs
env: |
  - name: KAFKA_TOPICS_NOTIFICATION_MAIL_NAME
    value: egov.core.notification.email
  - name: KAFKA_TOPICS_NOTIFICATION_MAIL_ID
    value: egov.core.notification.email
  - name: KAFKA_TOPICS_NOTIFICATION_MAIL_GROUP
    value: egov.core.notification.email
  - name: MAIL_SENDER_USERNAME
    valueFrom:
      secretKeyRef:
        name: egov-notification-mail
        key: mailsenderusername                   
  - name: MAIL_SENDER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: egov-notification-mail
        key: mailsenderpassword
  {{- if index .Values "mail-port" }}
  - name: MAIL_PORT
    value: {{ index .Values "mail-port" | quote }}
  - name: MAIL_HOST
    valueFrom:
      secretKeyRef:
        name: egov-notification-mail
        key: mail-host
  {{- end }}        
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_USER_STATE_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id        
