# Common Labels
labels:
  app: "pgadmin"
  group: "pgadmin"
namespace: playground

# Ingress Configs
ingress:
  enabled: true
  context: "pgadmin"
  additionalAnnotations: |
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Script-Name /pgadmin;
    {{- if index .Values "whitelist-ips" }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ index .Values "whitelist-ips" | quote }}
    {{- end }}
  #   nginx.ingress.kubernetes.io/auth-signin:  https://$host/oauth2/start?rd=$escaped_request_uri
  #   nginx.ingress.kubernetes.io/auth-url:     https://$host/oauth2/auth 

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "pgadmin"
  tag: "v4.7.7"

replicas: "1"
httpPort: "8080"
dbUrl: "egov-dev-db.ctm6jbmr5mnj.ap-south-1.rds.amazonaws.com"
dbPort: "5432"
dbWriteUser: "read"
dbReadUser: "write"
maintenance-db-name: "postgres"
db-admin-username: "egov"
db-read-username: "readonly"
environment: "DEV"
data-dir: "/var/lib/pgadmin"
log-file-path: "/var/lib/pgadmin/pgadmin4.log"
sqlite-path: "/var/lib/pgadmin/pgadmin4.db"
session-path: "/var/lib/pgadmin/sessions"
storage-path: "/var/lib/pgadmin/storage"
cookie-protection: "True"
ui-languages: "{'en': 'English'}"
enable-save-password: "False"
max-query-history: "50"
max-login-attempts: "5"
shared-storage: "[{'name': 'Shared Folder', 'path': '/var/lib/pgadmin/shared_folder', 'restricted_access': True}]"

persistence:
  enabled: false
  storageClassName: default
  accessMode: ReadWriteOnce
  volumeMode: Filesystem
#  dataDirSize: 1Gi
#  aws:
#    volumeId: "value"
#    zone: ap-south-1a
#  azure:
#    diskName: zookeeper-0
#    diskUri: value
#  openstack: f37a03aa-6212-4c62-a805-9ce139fab180
#  iscsi:
#    targetPortal: 192.0.2.100:3260
#    iqn: iqn.2017-10.local.example.server:disk1

extraVolumes: |
  - name: config
    configMap:
      name: {{ .Chart.Name }}-config
  - name: storage
    persistentVolumeClaim:
      claimName: {{ .Chart.Name }}-data

extraVolumeMounts: |
  - mountPath: /pgadmin4/servers.json
    name: config
    subPath: servers.json
    readOnly: true
  - mountPath: /pgadmin4/config_local.py
    name: config
    subPath: config_local.py
    readOnly: true
  - mountPath: /var/lib/pgadmin
    name: storage

securityContext:
  fsGroup: 5050

# Additional Container Envs
env: |
  - name: PGADMIN_DEFAULT_EMAIL
    valueFrom:
      secretKeyRef:
        name: pgadmin
        key: admin-email
  - name: PGADMIN_DEFAULT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pgadmin
        key: admin-password
  - name: CONFIG_DATABASE_CONNECTION_POOL_SIZE
    value: "5"
  - name: PGADMIN_LISTEN_PORT
    value: {{ .Values.httpPort | quote }}
  - name: PGADMIN_DISABLE_POSTFIX
    value: "true"
