# Common Labels
labels:
  app: "pgadmin"
  group: "pgadmin"
namespace: playground

# Ingress Configs
ingress:
  enabled: true
  context: "pgadmin"
  # additionalAnnotations: |
  #   nginx.ingress.kubernetes.io/auth-signin:  https://$host/oauth2/start?rd=$escaped_request_uri
  #   nginx.ingress.kubernetes.io/auth-url:     https://$host/oauth2/auth 

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "pgadmin"
  tag: "v4.1.1"
replicas: "1"
httpPort: 8080
serverBasePath: "/pgadmin"
dbUrl: "egov-dev-db.ctm6jbmr5mnj.ap-south-1.rds.amazonaws.com"
environment: "DEV"
maintenance-db-name: "postgres"           

# Additional Container Envs
env: |  
  - name: SERVER_HOST
    value: {{ .Values.dbUrl | quote }}     
  - name: SERVER_PORT
    value: "5432" 
  - name: SERVER_MODE
    value: "False"         
  - name: SERVER_NAME
    value: {{ .Values.environment | quote }}                 
  - name: MAINTENANCE_DB_NAME
    value: {{ index .Values "maintenance-db-name" | quote }}               
  - name: PGADMIN_PORT
    value: {{ .Values.httpPort | quote }}
  - name: SCRIPT_NAME
    value: {{ .Values.serverBasePath | quote }} 