apiVersion: v2
name: mseva-ui
description: A Helm chart for mSeva UI
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
- name: common
  version: 0.0.5
  repository: file://../../common