# Common Labels
labels:
  app: "mseva-ui"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "mseva-ui"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "mseva-ui"
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/mseva-ui/"
  readinessProbePath: "/mseva-ui/"

extraVolumes: |
  - name: js-injection
    configMap:
      name: mseva-ui-js-injection

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
