# Common Labels
labels:
  app: "expense-calculator"
  group: "works"

namespace: staging

hpa:
  enabled: true

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "expense-calculator"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "expense-calculator_schema"
    image:
      repository: "expense-calculator-db"
    env: |
      {{- if index .Values "expense-calculator-ismultischema-enabled" }}        
      - name: SCHEMA_NAME
        value: {{ index .Values "expense-calculator-schemas" | quote }}
      {{- end }}
      - name: "DB_URL"
        valueFrom: 
          configMapKeyRef: 
            name: egov-config
            key: db-url-works
      - name: "SCHEMA_TABLE"
        value: {{ .Values.initContainers.dbMigration.schemaTable | quote }}              
      - name: "FLYWAY_USER"
        valueFrom: 
          secretKeyRef: 
            name: db
            key: flyway-username
      - name: "FLYWAY_PASSWORD"
        valueFrom:
          secretKeyRef: 
            name: db
            key: flyway-password
      - name: "FLYWAY_LOCATIONS"
        valueFrom: 
          configMapKeyRef: 
            name: egov-config
            key: flyway-locations  
      {{- if index .Values.global "is-environment-central-instance" }}        
      - name: IS_ENVIRONMENT_CENTRAL_INSTANCE
        valueFrom:
          configMapKeyRef:
            name: egov-config
            key: is-environment-central-instance
      - name: STATE_LEVEL_TENANTID_LENGTH
        valueFrom:
          configMapKeyRef:
            name: egov-config
            key: state-level-tenantid-length
      {{- end }}

# Container Configs
image:
  repository: "expense-calculator"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/expense-calculator/health"
  readinessProbePath: "/expense-calculator/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: SERVER_CONTEXT_PATH
    value: /expense-calculator
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /expense-calculator
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: EXPENSE_CALCULATOR_CONSUME_TOPIC
    value: "calculate-musterroll"
  - name: EXPENSE_CALCULATOR_ERROR_TOPIC
    value: "calculate-error"
  - name: EXPENSE_CALCULATOR_CREATE_BILL_TOPIC
    value: "calculate-billmeta"
  - name: EGOV_MUSTERROLL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: muster-roll-service
  - name: EGOV_BILL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: expense
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/egov-mdms-service/v1/_search"
  - name: EGOV_MDMS_V2_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service-v2  
  - name: EGOV_MDMS_V2_SEARCH_ENDPOINT
    value: "/mdms-v2/v1/_search"
  - name: EGOV_IDGEN_HOST
    valueFrom: 
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_CONTRACT_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: contract-service
  - name: EGOV_ORGANISATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: organisation
