# Common Labels
labels:
  app: "studio-service-request"
  group: "rainmaker"

namespace: studio
# Ingress Configs
ingress:
  namespace: studio
  enabled: true
  zuul: true
  context: "studio-service-request"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "service-request_schema"
    image:
      repository: "studio-service-request-db"

# Container Configs
image:
  repository: "studio-service-request"
replicas: "1"
studioChecks:
  enabled: true
  livenessProbePath: "/studio-service-request/health"
  readinessProbePath: "/studio-service-request/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
memory_limits: 512Mi
java-args: "-Dspring.profiles.active=monitoring"

# Additional Container Envs
env: |
  - name: SERVER_CONTEXT_PATH
    value: /studio-service-request
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /studio-service-request
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: service-request-studio
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: EGOV_SERVICE_DEFINITION_CREATE_TOPIC
    value: save-service-definition-studio
  - name: EGOV_SERVICE_CREATE_TOPIC
    value: save-service-studio
  - name: EGOV_SERVICE_UPDATE_TOPIC
    value: update-service-studio
  - name: EGOV_SERVICE_DEFINITION_UPDATE_TOPIC
    value: update-service-definition-studio
  - name: EGOV_SERVICE_REQUEST_DEFAULT_OFFSET
    value: "0"
  - name: EGOV_SERVICE_REQUEST_DEFAULT_LIMIT
    value: "10"
  - name: EGOV_SERVICE_REQUEST_MAX_LIMIT
    value: "100"
  - name: EGOV_MAX_STRING_INPUT_SIZE
    value: "8192"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
