# Common Labels
labels:
  app: "citizen"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "citizen"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "citizen"
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/citizen/"
  readinessProbePath: "/citizen/"

extraVolumes: |
  - name: js-injection
    configMap:
      name: citizen-js-injection

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection    
    subPath: sub_filter.conf

namespace: state1   