# Common Labels
labels:
  app: "egov-url-shortening"
  group: "egov"

# Ingress Configs
ingress:
  enabled: true
  zuul: false
  context: "eus"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov-url-shortening_schema"
    image:
      repository: "egov-url-shortening-db"

# Container Configs
image:
  repository: "egov-url-shortening"
#replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/egov-url-shortening/health"
  readinessProbePath: "/egov-url-shortening/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: "-Dspring.profiles.active=monitoring"
server-context: "/eus"

memory_requests: "256Mi"
memory_limits: "512Mi"
cpu_limits: "20m"
cpu_requests: "10m"

# Additional Container Envs
env: |
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  - name: SPRING_REDIS_HOST
    value: redis.backbone
  - name: SPRING_REDIS_PORT
    value: "6379"
  - name: SERVER_CONTEXT_PATH
    value: {{ index .Values "server-context" | quote }}
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: {{ index .Values "server-context" | quote }}
  - name: SERVER_CONTEXTPATH
    value: {{ index .Values "server-context" | quote }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: HOST_NAME
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
