apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-errors.fullname" . }}
  namespace: ifix
  labels:
    {{- include "nginx-errors.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-errors.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-errors.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
