# Common Labels
labels:
  app: "bankaccounts"
  group: "works"

namespace: staging

hpa:
  enabled: true

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "bankaccount-service"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "bankaccounts_schema"
    image:
      repository: "bankaccounts-db"
    env: |
      {{- if index .Values "bankaccounts-ismultischema-enabled" }}        
      - name: SCHEMA_NAME
        value: {{ index .Values "bankaccounts-schemas" | quote }}
      {{- end }}
      - name: "DB_URL"
        valueFrom: 
          configMapKeyRef: 
            name: egov-config
            key: db-url-works
      - name: "SCHEMA_TABLE"
        value: {{ .Values.initContainers.dbMigration.schemaTable | quote }}              
      - name: "FLYWAY_USER"
        valueFrom: 
          secretKeyRef: 
            name: db
            key: flyway-username
      - name: "FLYWAY_PASSWORD"
        valueFrom:
          secretKeyRef: 
            name: db
            key: flyway-password
      - name: "FLYWAY_LOCATIONS"
        valueFrom: 
          configMapKeyRef: 
            name: egov-config
            key: flyway-locations  
      {{- if index .Values.global "is-environment-central-instance" }}        
      - name: IS_ENVIRONMENT_CENTRAL_INSTANCE
        valueFrom:
          configMapKeyRef:
            name: egov-config
            key: is-environment-central-instance
      - name: STATE_LEVEL_TENANTID_LENGTH
        valueFrom:
          configMapKeyRef:
            name: egov-config
            key: state-level-tenantid-length
      {{- end }}

# Container Configs
image:
  repository: "bankaccounts"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/bankaccount-service/health"
  readinessProbePath: "/bankaccount-service/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: SERVER_CONTEXT_PATH
    value: /bankaccount-service
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /bankaccount-service  
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/egov-mdms-service/v1/_search" 
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: BANK_ACCOUNT_KAFKA_CREATE_TOPIC
    value: "save-bank-account"
  - name: BANK_ACCOUNT_KAFKA_UPDATE_TOPIC
    value: "update-bank-account"
  {{- if index .Values "bank-account-default-limit" }}
  - name: BANK_ACCOUNT_DEFAULT_LIMIT
    value: {{ index .Values "bank-account-default-limit" | quote }} 
  {{- end }}
  {{- if index .Values "bank-account-search-max-limit" }}
  - name: BANK_ACCOUNT_SEARCH_MAX_LIMIT
    value: {{ index .Values "bank-account-search-max-limit" | quote }} 
  {{- end }}
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: "bankaccounts"
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
  - name: EGOV_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: individual
  - name: EGOV_MDMS_V2_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service-v2  
  - name: EGOV_ORGANISATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: organisation
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
