# Common Labels
labels:
  app: "project-management-system"
  group: "works"

namespace: staging

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "pms"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "project_management_system_schema"
    image:
      repository: "project-management-system-db"
    env: |
      {{- if index .Values "project-management-system-ismultischema-enabled" }}        
      - name: SCHEMA_NAME
        value: {{ index .Values "project-management-system-schemas" | quote }}
      {{- end }}
      - name: "DB_URL"
        valueFrom: 
          configMapKeyRef: 
            name: egov-config
            key: db-url-works
      - name: "SCHEMA_TABLE"
        value: {{ .Values.initContainers.dbMigration.schemaTable | quote }}              
      - name: "FLYWAY_USER"
        valueFrom: 
          secretKeyRef: 
            name: db
            key: flyway-username
      - name: "FLYWAY_PASSWORD"
        valueFrom:
          secretKeyRef: 
            name: db
            key: flyway-password
      - name: "FLYWAY_LOCATIONS"
        valueFrom: 
          configMapKeyRef: 
            name: egov-config
            key: flyway-locations  
      {{- if index .Values.global "is-environment-central-instance" }}        
      - name: IS_ENVIRONMENT_CENTRAL_INSTANCE
        valueFrom:
          configMapKeyRef:
            name: egov-config
            key: is-environment-central-instance
      - name: STATE_LEVEL_TENANTID_LENGTH
        valueFrom:
          configMapKeyRef:
            name: egov-config
            key: state-level-tenantid-length
      {{- end }}

# Container Configs
image:
  repository: "project-management-system"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/pms/health"
  readinessProbePath: "/pms/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: SERVER_CONTEXT_PATH
    value: /pms
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /pms 
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/egov-mdms-service/v1/_search"
  - name: EGOV_MDMS_V2_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service-v2
  - name: EGOV_MDMS_V2_SEARCH_ENDPOINT
    value: "/mdms-v2/v1/_search"
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: PROJECT_MANAGEMENT_SYSTEM_KAFKA_CREATE_TOPIC
    value: "save-project"
  - name: PROJECT_MANAGEMENT_SYSTEM_KAFKA_UPDATE_TOPIC
    value: "update-project"
  {{- if index .Values "project-default-offset" }}
  - name: PROJECT_MANAGEMENT_SYSTEM_DEFAULT_OFFSET
    value: {{ index .Values "project-default-offset" | quote }} 
  {{- end }}
  {{- if index .Values "project-default-limit" }}
  - name: PROJECT_MANAGEMENT_SYSTEM_DEFAULT_LIMIT
    value: {{ index .Values "project-default-limit" | quote }} 
  {{- end }}
  {{- if index .Values "project-search-max-limit" }}
  - name: PROJECT_MANAGEMENT_SYSTEM_SEARCH_MAX_LIMIT
    value: {{ index .Values "project-search-max-limit" | quote }} 
  {{- end }}
  {{- if index .Values "project-mdms-module" }}
  - name: PROJECT_MANAGEMENT_SYSTEM_MDMS_MODULE
    value: {{ index .Values "project-mdms-module" | quote }} 
  {{- end }}
  {{- if index .Values "egov-location-hierarchy-type" }}
  - name: PROJECT_MANAGEMENT_SYSTEM_EGOV_LOCATION_HIERARCHY_TYPE
    value: {{ index .Values "egov-location-hierarchy-type" | quote }} 
  {{- end }}