# Common Labels
labels:
  app: "works-pdf"
  group: "rainmaker"

namespace: works

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "egov-pdf"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "works_pdf_schema"
    image:
      repository: "works-pdf-db"

# Container Configs
image:
  repository: "works-pdf"

# Additional Container Envs
env: |
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: DB_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-host
  - name: DB_NAME
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-name
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: KAFKA_BROKER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
  - name: DB_PORT
    value: "5432"
  - name: EGOV_PDF_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: pdf-service
  - name: EGOV_PROJECT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: project-management-system
  - name: EGOV_ESTIMATE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: estimate-service  
  - name: EGOV_MUSTER_ROLL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: muster-roll-service  
  - name: EGOV_CONTRACT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: contract-service 
  - name:  EGOV_ORGANISATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: organisation                   
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user  
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2   
  - name: EXPENSE_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: expense
  - name: BANKACCOUNT_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: bankaccounts
  - name: EXPENSE_CALCULATOR_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: expense-calculator
  - name: EGOV_FILESTORE_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_AUDIT_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: audit-service
  - name: CONTEXT_PATH
    value: "/egov-pdf" 
  - name: PROJECT_DETAILS_TEMPLATE
    value: "project-detail"
  - name: ESTIMATE_TEMPLATE
    value: "estimate"
  - name: NOMINAL_MUSTER_ROLL_TEMPLATE
    value: "nominal-muster-roll" 
  - name: WORK_ORDER_TEMPLATE
    value: "work-order" 
  - name: WORK_ORDER_TEMPLATE_HINDI
    value: "work-order-hindi"      
  - name: EGOV_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name