# Common Labels
labels:
  app: "telemetry"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  context: "v1/telemetry"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "telemetry"
httpPort: 9001
tracing-enabled: true

# Additional Container Envs
env: |
  - name: telemetry_kafka_broker_list
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers  
  - name: telemetry_kafka_topic
    value: "telemetry-raw-input"
  - name: telemetry_local_storage_type
    value: "kafka"
  - name: telemetry_service_port
    value: "9001"
  - name: telemetry_file_maxsize
    value: "100m"
  - name: telemetry_file_maxfiles
    value: "100"
  - name: telemetry_service_threads
    value: "2"
  - name: SERVER_PORT
    value: "9001"