# Common Labels
labels:
  app: "statements"
  group: "digit-works"

namespace: works

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "statements"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "statements_schema"
    image:
      repository: "statements-db"

# Container Configs
image:
  repository: "statements"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/statements/health"
  readinessProbePath: "/statements/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
memory_limits: 512Mi
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: SERVER_CONTEXT_PATH
    value: /statements
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /statements
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: EGOV_MDMS_V2_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service-v2  
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: WORKS_ESTIMATE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: estimate-service                
  - name: WORKS_MEASUREMENT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: measurement-service 
  - name: WORKS_CONTRACT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: contract-service
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2