# Common Labels
labels:
  app: "egov-index-custom-consumer"
  group: "core"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "egov-index-custom-consumer"
replicas: "1"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx384m -Xms256m"

# Additional Container Envs
env: |
  - name: EGOV_PT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: pt-services-v2
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: "egov-index-custom-consumer-group"
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  {{- if index .Values "global" "serializers-timezone-in-ist" }}
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
  {{- end }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SERVER_PORT
    value: "8080"
