# Common Labels
labels:
  app: "egov-localization"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "localization"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_localization_schema"
    image:
      repository: "egov-localization-db"

# Container Configs
image:
  repository: "egov-localization"
replicas: "1"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx512m -Xms386m"
memory_limits: 768Mi
healthChecks:
  enabled: true
  livenessProbePath: "/localization/health"
  readinessProbePath: "/localization/health"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SPRING_REDIS_HOST
    value: redis.backbone
  - name: SPRING_REDIS_PORT
    value: "6379"
  - name: JAEGER_SAMPLER_PARAM
    value: "1"
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: state-level-tenant-id
  - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
    value: "20"
  - name: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
    value: "5"
  - name: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
    value: "30000"
  - name: SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT
    value: "600000"
  - name: SPRING_DATASOURCE_HIKARI_MAX_LIFETIME
    value: "1800000"
