{{- define "common.ingress" -}}
{{- if .Values.ingress.enabled -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "common.name" . }}
{{- if .Values.ingress.namespace }}
  namespace: {{ .Values.ingress.namespace }}    
{{- else }}  
  namespace: {{ .Values.namespace }}  
{{- end }}  
  annotations:
{{- toYaml .Values.ingress.annotations | nindent 4 }}   
{{- if .Values.ingress.waf.enabled }}      
{{- toYaml .Values.ingress.waf.annotations | nindent 4 }} 
{{- end  }}
{{- if .Values.ingress.additionalAnnotations }}                                   
  {{- tpl  .Values.ingress.additionalAnnotations . | nindent 4 }}
{{- end }} 
  labels:
{{- include "common.labels" . | nindent 4 }}                            
spec:
  rules:
{{- if .Values.ingress.host }}   
  {{- tpl  .Values.ingress.host . | nindent 2 }}
{{- else if .Values.ingress.hostName }} 
  - host: {{ .Values.ingress.hostName }}
{{- else }}  
  - host: {{ .Values.global.domain }}
{{- end }}  
    http:
      paths:
      - backend:
{{- if .Values.ingress.zuul }}          
          serviceName: zuul
          servicePort: 8080
{{ else }}
          serviceName: {{ .Values.ingress.serviceName | default (include "common.name" .) }}
          servicePort: {{ .Values.ingress.servicePort | default .Values.httpPort }}
{{- end }}            
        path: /{{ .Values.ingress.context }}
  tls:
{{- if .Values.ingress.tls }}
  {{- tpl  .Values.ingress.tls . | nindent 2 }}
{{- else }} 
{{- if .Values.ingress.hostName }}
  - hosts: 
    - {{ .Values.ingress.hostName }}
    secretName: {{ .Values.ingress.hostName }}-tls-certs  
{{- else }}      
  - hosts:
    - {{ .Values.global.domain }}
    secretName: {{ .Values.global.domain }}-tls-certs 
{{- end }} 
{{- end }} 
{{- end -}} 
{{- end -}} 
