{{- define "common.ingress" -}}
{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "common.name" . }}
  {{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  {{- else }}
  namespace: {{ .Values.ingress.namespace | default .Values.namespace }}
  {{- end }}
  annotations:
{{ toYaml .Values.ingress.annotations | nindent 4 }}
{{- if .Values.ingress.waf.enabled }}
{{ toYaml .Values.ingress.waf.annotations | nindent 4 }}
{{- end }}
{{- if .Values.ingress.additionalAnnotations }}
{{ tpl .Values.ingress.additionalAnnotations . | nindent 4 }}
{{- end }}
  labels:
{{ include "common.labels" . | nindent 4 }}
spec:
  rules:
  {{- if .Values.ingress.zuul }}
    {{- if .Values.global.hosts }}
      {{- range .Values.global.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /{{ $.Values.ingress.context }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: gateway
            port:
              number: 8080
      {{- end }}
    {{- else }}
  - host: {{ .Values.global.domain | default "example.com" }}
    http:
      paths:
      - path: /{{ $.Values.ingress.context }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: gateway
            port:
              number: 8080
    {{- end }}
  {{- else }}
  - host: {{ .Values.global.domain }}
    http:
      paths:
      - path: /{{ .Values.ingress.context }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $.Values.ingress.serviceName | default $.Chart.Name }}
            port:
              number: {{ $.Values.ingress.servicePort | default $.Values.httpPort }}
  {{- end }}
  tls:
  {{- if .Values.ingress.zuul }}
    {{- if .Values.global.hosts }}
      {{- range .Values.global.hosts }}
  - hosts:
    - {{ . }}
    secretName: {{ . }}-tls-certs
      {{- end }}
    {{- else }}
  - hosts:
    - {{ .Values.global.domain | default "example.com" }}
    secretName: {{ .Values.global.domain | default "example.com" }}-tls-certs
    {{- end }}
  {{- else }}
  - hosts:
    - {{ .Values.global.domain }}
    secretName: {{ .Values.global.domain }}-tls-certs
  {{- end }}
{{- end -}}
{{- end -}}
