# Common Labels
labels:
  app: "contract-service"
  group: "digit-works"

namespace: works

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "contract-service"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "contract_service_schema"
    image:
      repository: "contract-service-db"

# Container Configs
image:
  repository: "contract-service"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/contract-service/health"
  readinessProbePath: "/contract-service/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: SERVER_CONTEXT_PATH
    value: /contract-service
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /contract-service 
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: WORKS_ESTIMATE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: estimate-service
  - name: WORKS_HRMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-hrms
  - name: WORKS_ATTENDANCE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: attendance-service
  - name: CONTRACT_KAFKA_CREATE_TOPIC
    value: "save-contract"
  - name: CONTRACT_KAFKA_UPDATE_TOPIC
    value: "update-contract"
  {{- if index .Values "contract-default-offset" }}
  - name: CONTRACT_DEFAULT_OFFSET
    value: {{ index .Values "contract-default-offset" | quote }}
  {{- end }}
  {{- if index .Values "contract-default-limit" }}
  - name: CONTRACT_DEFAULT_LIMIT
    value: {{ index .Values "contract-default-limit" | quote }}
  {{- end }}
  {{- if index .Values "contract-search-max-limit" }}
  - name: CONTRACT_SEARCH_MAX_LIMIT
    value: {{ index .Values "contract-search-max-limit" | quote }}
  {{- end }}
  {{- if index .Values "contract-workflow-business-service" }}
  - name: CONTRACT_WORKFLOW_BUSINESS_SERVICE
    value: {{ index .Values "contract-workflow-business-service" | quote }}
  {{- end }}
  {{- if index .Values "contract-workflow-module-name" }}
  - name: CONTRACT_WORKFLOW_MODULE_NAME
    value: {{ index .Values "contract-workflow-module-name" | quote }}
  {{- end }}
  {{- if index .Values "contract-org-id-verification-required" }}
  - name: CONTRACT_ORG_ID_VERIFICATION_REQUIRED
  value: {{ index .Values "contract-org-id-verification-required" | quote }}
  {{- end }}