# creation rules are evaluated sequentially, the first match wins
creation_rules:
        # upon creation of a file that matches the pattern *dev.yaml,
        # KMS set A is used
        # eGOV Internal ------------------------------------------------------------------------------------------------------------- #
        - path_regex: environments/sanitation\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:349271159511:key/29adbf26-7b85-4469-8c9e-f8050fd19a8e'
          pgp: '58BE5C4525DFE047D960AFF29E8891E02D93FD9F' 

        - path_regex: environments/unified\-dev\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'

        - path_regex: environments/unified\-works\-dev\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'

        - path_regex: environments/unified\-health\-dev\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'

        - path_regex: environments/unified\-urban\-dev\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'  
