# creation rules are evaluated sequentially, the first match wins
creation_rules:
        # upon creation of a file that matches the pattern *dev.yaml,
        # KMS set A is used
        # eGOV Internal ------------------------------------------------------------------------------------------------------------- #
        - path_regex: environments/dev\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'   

        - path_regex: environments/qa\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'  

        - path_regex: environments/playground\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'   
       
        - path_regex: environments/staging\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196' 

        # ePASS ------------------------------------------------------------------------------------------------------------- #
        - path_regex: environments/egov\-demo\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'    

        - path_regex: environments/epass\-prod\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'   

        - path_regex: environments/epass\-uat\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/93761f6b-a115-4ca2-870e-aeb2f66445f0'
          gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'              

        - path_regex: environments/epass\-micro-prod\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/93761f6b-a115-4ca2-870e-aeb2f66445f0'
          gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'  

        # CI ------------------------------------------------------------------------------------------------------------- #
        - path_regex: environments/ci\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'               

        # BIHAR ------------------------------------------------------------------------------------------------------------- #
        - path_regex: environments/bihar\-dev\-secrets\.yaml$
          encrypted_regex: '^(secrets)$'
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          #azure_keyvault: 'https://bihar-uat-key-vault.vault.azure.net/keys/sops/9c2ec70ac9584c4d9e458e01304ad07d'
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'                   

        - path_regex: environments/biharUat\-secrets\.yaml$
          encrypted_regex: '^(secrets)$'
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          #azure_keyvault: 'https://bihar-uat-key-vault.vault.azure.net/keys/sops/9c2ec70ac9584c4d9e458e01304ad07d'
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'  

        - path_regex: environments/bihar\-prod\-secrets\.yaml$
          encrypted_regex: '^(secrets)$'
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'AAD898A8752588AAA792BEA9A4E8C1B8BCC1E58D'                    

        # UKD ------------------------------------------------------------------------------------------------------------- #
        - path_regex: environments/ukd\-dev\-secrets\.yaml$
          encrypted_regex: '^(secrets)$'
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          #azure_keyvault: 'https://bihar-uat-key-vault.vault.azure.net/keys/sops/9c2ec70ac9584c4d9e458e01304ad07d'
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'          
          
        - path_regex: environments/ukd\-uat\-secrets\.yaml$
          encrypted_regex: '^(secrets)$'
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          #azure_keyvault: 'https://bihar-uat-key-vault.vault.azure.net/keys/sops/9c2ec70ac9584c4d9e458e01304ad07d'
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'

        - path_regex: environments/ukd\-sdc\-prod\-secrets\.yaml$
          encrypted_regex: '^(secrets)$'
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          #azure_keyvault: 'https://bihar-uat-key-vault.vault.azure.net/keys/sops/9c2ec70ac9584c4d9e458e01304ad07d'
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196' 

        - path_regex: environments/ukd\-sdc\-uat\-secrets\.yaml$
          encrypted_regex: '^(secrets)$'
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'AAD898A8752588AAA792BEA9A4E8C1B8BCC1E58D'   

        - path_regex: environments/ukd\-sdc\-dev\-secrets\.yaml$
          encrypted_regex: '^(secrets)$'
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          #azure_keyvault: 'https://bihar-uat-key-vault.vault.azure.net/keys/sops/9c2ec70ac9584c4d9e458e01304ad07d'
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196' 

        # PB ------------------------------------------------------------------------------------------------------------- #
        - path_regex: environments/pb\-qa\-secrets\.yaml$ 
          encrypted_regex: '^(secrets)$'
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'  
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'

        - path_regex: environments/pb\-uat\-secrets\.yaml$  # PMIDC-UAT
          encrypted_regex: '^(secrets)$'
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'

        - path_regex: environments/pb\-prod\-secrets\.yaml$   #PMIDC-PROD
          encrypted_regex: '^(secrets)$'
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'

        - path_regex: environments/pb\-uat-v2\-secrets\.yaml$   #PMIDC-PROD
          encrypted_regex: '^(secrets)$'
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'

        - path_regex: environments/pb\-prod-v2\-secrets\.yaml$   #PMIDC-PROD
          encrypted_regex: '^(secrets)$'
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'

        #nugp ---------------------------------------------------------------------------
        - path_regex: environments/nugp\-demo\-secrets\.yaml$   
          encrypted_regex: '^(secrets)$'
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196' 


        #UP ---------------------------------------------------------------------------
        - path_regex: environments/up\-dev\-secrets\.yaml$   #UP-DEV
          encrypted_regex: '^(secrets)$'
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'  

        - path_regex: environments/up\-uat\-secrets\.yaml$   #up-uat
          encrypted_regex: '^(secrets)$'
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196' 

        - path_regex: environments/up\-prod\-secrets\.yaml$   #up-prod
          encrypted_regex: '^(secrets)$'
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196' 
        - path_regex: environments/single-instance\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          # pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'
        # DEFAULT ------------------------------------------------------------------------------------------------------------- #
        # Finally, if the rules above have not matched, this one is a
        # catchall that will encrypt the file using KMS set C
        # The absence of a path_regex means it will match everything
        - kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
          #gcp_kms: 'projects/digit-egov/locations/asia-south1/keyRings/egov-sops/cryptoKeys/egov-sops-key'
          encrypted_regex: '^(secrets)$'
          pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'

        # - path_regex: environments/dev\.yaml$
        #   encrypted_regex: '^(secrets)$'
        #   kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'
        #   pgp: 'C7ED80C79625B40667A6FAD6774DE10645AAD1BB'
