# Common Labels
labels:
  app: "property-services"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "property-services"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "property_services_schema"
    image:
      repository: "property-services-db"

# Container Configs
image:
  repository: "property-services"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/property-services/health"
  readinessProbePath: "/property-services/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: "-Dspring.profiles.active=monitoring"
notification-sms-enabled: ""
employee-allowed-search-params: ""
citizen-allowed-search-params: ""
egov-url-shortner-endpoint: "egov-url-shortening/shortener"

# Additional Container Envs
env: |
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: internal-gateway
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_CALCULATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: internal-gateway
  - name: EGOV_PT-SERVICES-V2_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: pt-services-v2
  - name: EGOV_URL_SHORTNER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-url-shortening
  - name: EGOV_URL_SHORTNER_ENDPOINT
    value: {{ index .Values "egov-url-shortner-endpoint" | quote }}              
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-property-services
  - name: PERSISTER_SAVE_PROPERTY_TOPIC
    value: save-property-registry
  - name: PERSISTER_UPDATE_PROPERTY_TOPIC
    value: update-property-registry
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: NOTIFICATION_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name       
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: ASSESSMENT_WORKFLOW_ENABLED
    value: "false"

  {{- if index .Values "is-workflow-enabled" }}
  - name: IS_WORKFLOW_ENABLED
    value: {{ index .Values "is-workflow-enabled" | quote }}
  {{- else }}  
  - name: IS_WORKFLOW_ENABLED
    value: "true"
  {{- end }}

  {{- if index .Values "is.mutation.workflow.enabled" }}
  - name: IS_MUTATION_WORKFLOW_ENABLED
    value: {{ index .Values "is.mutation.workflow.enabled" | quote }}
  {{- else }}  
  - name: IS_MUTATION_WORKFLOW_ENABLED
    value: "true"
  {{- end }}
  
  - name: EGOV_IDGEN_ACK_FORMAT
    value: {{ index .Values "egov-idgen-ack-format" | quote }}
  - name: EGOV_IDGEN_MUTATION_FORMAT
    value: {{ index .Values "egov-idgen-mutation-format" | quote }} 
  - name: EGOV_IDGEN_ASSM_FORMAT
    value: {{ index .Values "egov-idgen-assm-format" | quote }} 
  - name: EGOV_IDGEN_PTID_FORMAT
    value: {{ index .Values "egov-idgen-ptid-format" | quote }}        
  - name: EGOV_USER_EVENT_NOTIFICATION_ENABLED
    value: "true"
  {{- if index .Values "employee-allowed-search-params" }}
  - name: EMPLOYEE_ALLOWED_SEARCH_PARAMS
    value: {{ index .Values "employee-allowed-search-params" | quote }}
  {{- end }}
  {{- if index .Values "citizen-allowed-search-params" }}
  - name: CITIZEN_ALLOWED_SEARCH_PARAMS
    value: {{ index .Values "citizen-allowed-search-params" | quote }}
  {{- end }}
  - name: EGOV_UI_APP_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: EGOV_USR_EVENTS_CREATE_TOPIC
    value: "persist-user-events-async"
  - name: EGOV_USR_EVENTS_PAY_LINK
    value: "citizen/withoutAuth?redirectTo=egov-common/pay?consumerCode=$consumerCode&tenantId=$tenantId&businessService=$businessService"
  - name: EGOV_USR_EVENTS_PAY_CODE
    value: "PAY"          
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: state-level-tenant-id
  - name: EGOV_ENC_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-enc-service
  {{- if index .Values "cluster-configs" "configmaps" "egov-config" "data" "is-environment-central-instance" }}        
  - name: IS_ENVIRONMENT_CENTRAL_INSTANCE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: is-environment-central-instance
  {{- end }}
  {{- if index .Values "cluster-configs" "configmaps" "egov-config" "data" "is-environment-central-instance" }}        
  - name: STATE_LEVEL_TENANTID_LENGTH
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: state-level-tenantid-length
  {{- end }}        