# mysql Labels
labels:
  app: "mysql"
  group: "web"
namespace: pspcl

# Container Configs

image:
  repository: "docker.io/mysql"
  tag: "5.7"
replicas: "1"
httpPort: 3306

initContainers:
  extraInitContainers: |
    - name: "remove-lost-found"
      image: "{{ .Values.busybox.image}}:{{ .Values.busybox.tag }}"
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: 10Mi
          cpu: 10m
      command:  ["rm", "-fr", "/var/lib/mysql/lost+found"]

healthChecks:
  enabled: true
  livenessProbe: |
    exec:
      command:
      - sh
      - -c
      - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 60
    successThreshold: 1
    failureThreshold: 5 
  readinessProbe: |
    exec:
      command:
      - sh
      - -c
      - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 60
    successThreshold: 1
    failureThreshold: 5     

## WordPress containers' resource requests and limits
resources: |
  requests:
    cpu: 100m
    memory: 256Mi

env: |
  - name: MYSQL_ROOT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: {{ .Chart.Name }}
        key: mysql-password
  - name: MYSQL_USER
    value: {{ default "" .Values.mysqlUser | quote }}
  - name: MYSQL_DATABASE
    value: {{ default "" .Values.mysqlDatabase | quote }}
    {{- if .Values.timezone }}
  - name: TZ
    value: {{ .Values.timezone }}
    {{- end }}      

persistence:
  enabled: true
  aws:
    volumeId: "vol-0d860de150830abad"
  ## wordpress data Persistent Volume Storage Class
  storageClassName: default
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  ##
  ## If you want to reuse an existing claim, you can pass the name of the PVC using
  ## the existingClaim variable
  # existingClaim: your-claim
  accessMode: ReadWriteOnce
  dataDirSize: 10Gi 
  volumeMode: Filesystem

extraVolumeMounts: |
  - name: mysql-volume
    mountPath: /var/lib/mysql
extraVolumes: |
  - name: mysql-volume
    persistentVolumeClaim:
      claimName: mysql-volume 

# Ingress Configs
ingress:
  enabled: false
  zuul: false
  waf: 
    enabled: false

busybox:
  image: "busybox"
  tag: "1.31.1"  

# Init Containers Configs
initContainer:
  

