# Common Labels
labels:
  app: "disbursal"
  group: "digit-works"

namespace: works

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "disbursal"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "disbursal_schema"
    image:
      repository: "disbursal-db"

# Container Configs
image:
  repository: "disbursal"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/disbursal/health"
  readinessProbePath: "/disbursal/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
memory_limits: 384Mi
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: SERVER_CONTEXT_PATH
    value: /disbursal
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /disbursal 
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service-v2
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: EGOV_UBP_APPLICATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: uba-application-host
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  