cluster-configs:
  db:
    namespace: [ egov, works, health, urban, sanitation ]
    name: db-service
    port: 5432
    targetPort: 5432

  root-ingress:
    name: root-ingress
    namespace: egov
    cert-issuer: "letsencrypt-staging"
    appRoot: citizen
    serviceName: citizen
    servicePort: 80

  nginx-errors:
    enabled: false
    name: nginx-errors
    namespace: egov
    serviceName: nginx-errors
    servicePort: 80

  configmaps:
    egov-config:
      namespace: [ egov ]
      name: egov-config
      server-tomcat-max-connections: "500"
      server-tomcat-max-threads: "10"
      spring-datasource-tomcat-initialSize: "1"
      spring-datasource-tomcat-max-active: "2"
      spring-jpa-show-sql: "true"  

    egov-service-host:    
      name: egov-service-host
      namespace: [ egov ] 

    hcm-moz-impl:
      name: hcm-moz-impl
      namespace: [ health ]

  secrets:
    db: 
      namespace: [ egov, works, health, urban, sanitation ]
      name: db

    egov-notification-sms:
      namespace: egov
      name: egov-notification-sms

    egov-filestore:
      namespace: egov
      name: egov-filestore

    hcm-moz-impl:
      namespace: health
      name: hcm-moz-impl
      
    egov-location: 
      namespace: egov
      name: egov-location

    egov-pg-service: 
      namespace: egov
      name: egov-pg-service                 

    pgadmin: 
      namespace: playground
      name: pgadmin       

    egov-enc-service: 
      namespace: egov
      name: egov-enc-service       

    egov-notification-mail: 
      namespace: egov
      name: egov-notification-mail

    home-isolation-notification-mail: 
      namespace: egov
      name: home-isolation-notification-mail      

    git-sync: 
      namespace: [ egov, health, urban ]
      name: git-creds   

    kibana: 
      namespace: egov
      name: kibana-creds                       

    kibana-infra: 
      namespace: egov
      name: kibana-infra-creds     

    pgadmin: 
      namespace: playground
      name: pgadmin

    egov-si-microservice:
      namespace: egov
      name: egov-si-microservice

    egov-edcr-notification:
      namespace: egov
      name: egov-edcr-notification 

    egov-edcr-bank-gateway:
      namespace: egov
      name: egov-edcr-bank-gateway

    chatbot:
      namespace: egov
      name: chatbot
    
    covid-chatbot:
      namespace: egov
      name: covid-chatbot

    egov-user-chatbot:
      namespace: egov
      name: egov-user-chatbot

    oauth2-proxy:
      namespace: egov
      name: oauth2-proxy   

    case-management:
      namespace: egov
      name: case-management   
  
    minio:
      namespace: backbone
      name: minio

    alertmanager:
      namespace: monitoring
      name: alertmanager-main      

    jenkins:
      namespace: jenkins
      name: jenkins 
    
    mysql:
      namespace: egov
      name: mysql
    
    wordpress:
      namespace: egov
      name: wordpress

    postgres:
      namespace: jenkins
      name: postgres
