cluster-configs:
  configmaps:
    egov-config:
      namespace: egov
      name: egov-config
      server-tomcat-max-connections: "500"
      server-tomcat-max-threads: "10"
      spring-datasource-tomcat-initialSize: "1"
      spring-datasource-tomcat-max-active: "2"
      spring-jpa-show-sql: "true"  

    egov-service-host:    
      namespace: egov
      name: egov-service-host  

  secrets:
    db: 
      namespace: egov
      name: db

    egov-notification-sms:
      namespace: egov
      name: egov-notification-sms

    egov-filestore: 
      namespace: egov
      name: egov-filestore     
      
    egov-location: 
      namespace: egov
      name: egov-location

    egov-pg-service: 
      namespace: egov
      name: egov-pg-service                 

    pgadmin: 
      namespace: playground
      name: pgadmin       

    egov-enc-service: 
      namespace: egov
      name: egov-enc-service       

    egov-notification-mail: 
      namespace: egov
      name: egov-notification-mail

    git-sync: 
      namespace: egov
      name: git-creds   

    kibana: 
      namespace: egov
      name: kibana-creds                       

    kibana-infra: 
      namespace: egov
      name: kibana-infra-creds     

    pgadmin: 
      namespace: playground
      name: pgadmin