# Common Labels
labels:
  app: "egov-enc-service"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "egov-enc-service"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_enc_service_schema"
    image:
      repository: "egov-enc-service-db"
      tag: core-2.9-lts-mvn-check-c607f2d4de-20

# Container Configs
image:
  repository: "egov-enc-service"
  tag: core-2.9-lts-mvn-check-c607f2d4de-20
replicas: "1"
# healthChecks:
#   enabled: true
#   livenessProbePath: "/egov-enc-service/health"
#   readinessProbePath: "/egov-enc-service/health"
appType: "java-spring"
tracing-enabled: true
healthChecks:
  enabled: true
  livenessProbePath: "/egov-enc-service/health"
  readinessProbePath: "/egov-enc-service/health"
heap: "-Xmx256m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"

master-password-provider: software

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"         
  - name: SERVER_CONTEXT_PATH
    value: /egov-enc-service    
  - name: MASTER_PASSWORD_PROVIDER
    value: {{ index .Values "master-password-provider" | quote }}
  {{- if index .Values "number-of-symmetric-keys-per-tenant" }}
  - name: NUMBER_OF_SYMMETRIC_ACTIVE_KEYS_PER_TENANT
    value: {{ index .Values "number-of-symmetric-keys-per-tenant" | quote }}
  {{- end }}
  {{- if eq (index .Values "master-password-provider") "software" }}
  - name: MASTER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: egov-enc-service
        key: master.password    
  - name: MASTER_SALT
    valueFrom:
      secretKeyRef:
        name: egov-enc-service
        key: master.salt
  - name: MASTER_INITIALVECTOR
    valueFrom:
      secretKeyRef:
        name: egov-enc-service
        key: master.initialvector
  {{- end }}
  {{- if eq (index .Values "master-password-provider") "awskms" }}
  - name: AWS_KMS_REGION
    value: {{ index .Values "aws-kms-region" | quote }}
  - name: AWS_KMS_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: egov-enc-service
        key: aws-kms-access-key
  - name: AWS_KMS_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: egov-enc-service
        key: aws-kms-secret-key
  - name: AWS_KMS_MASTER_PASSWORD_KEY_ID
    value: {{ index .Values "aws-kms-master-password-key-id" | quote }}
  {{- end }}
