# Common Labels
labels:
  app: "finance-collections-voucher-consumer"
  group: "collections"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "finance-collections-voucher-consumer_schema"
    image:
      repository: "finance-collections-voucher-consumer-db"

# Container Configs
image:
  repository: "finance-collections-voucher-consumer"
replicas: "1"
appType: "java-spring"
tracing-enabled: true
erp-env-name: "dev"
erp-domain-name: "egovernments.org"
heap: "-Xmx192m -Xms192m"

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: EGOV_SERVICES_EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_SERVICES_MDMS_HOSTNAME
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: internal-gateway
  - name: EGOV_SERVICES_EGFINSTRUMENT_HOSTNAME
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egf-instrument
  - name: EGOV_SERVICES_EGFMASTER_HOSTNAME
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egf-master
  - name: EGOV_SERVICES_COLLECTIONS_HOSTNAME
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: collection-services
  - name: EGOV_SERVICES_BUSINESSSERVICE_HOSTNAME
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: FIN_COE_ERP_ENVIRONMENT_NAME
    value: {{ index .Values "erp-env-name" | quote }}
  - name: FIN_COE_ERP_DOMAIN_NAME
    value: {{ index .Values "erp-domain-name" | quote }}
  - name: SI_MICROSERVICE_USER
    value: "SIFINANCE"
  - name: SI_MICROSERVICE_PASSWORD
    value: "sifinance123@"
  - name: SI_MICROSERVICE_USERTYPE
    value: "SYSTEM"
  - name: SI_MICROSERVICE_SCOPE
    value: "read"
  - name: SI_MICROSERVICE_GRANTTYPE
    value: "password"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SERVER_PORT
    value: "8080"
