# Common Labels
labels:
  app: "measurement-service"
  group: "digit-works"

namespace: works

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "measurement-service"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "measurement_service_schema"
    image:
      repository: "measurement-service-db"

# Container Configs
image:
  repository: "measurement-service"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/measurement-service/health"
  readinessProbePath: "/measurement-service/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_CONTEXT_PATH
    value: /measurement-service
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /measurement-service
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: EGOV_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  - name: EGOV_CONTRACT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: contract-service
  - name: EGOV_ESTIMATE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: estimate-service
  - name: EGOV_MEASUREMENT_REGISTRY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: measurement-registry
  - name: APP_TIMEZONE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: timezone
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  {{- if index .Values "measurement-service-kafka-create-topic" }}
  - name: MEASUREMENT-SERVICE_KAFKA_CREATE_TOPIC
    value: {{ index .Values "measurement-service-kafka-create-topic" | quote }}
  {{- end }}
  {{- if index .Values "measurement-service-kafka-update-topic" }}
  - name: MEASUREMENT-SERVICE_KAFKA_UPDATE_TOPIC
    value: {{ index .Values "measurement-service-kafka-update-topic" | quote }}
  {{- end }}
  {{- if index .Values "measurement-service-default-offset" }}
  - name: MEASUREMENT-SERVICE_DEFAULT_OFFSET
    value: {{ index .Values "measurement-service-default-offset" | quote }}
  {{- end }}
  {{- if index .Values "measurement-service-default-limit" }}
  - name: MEASUREMENT-SERVICE_DEFAULT_LIMIT
    value: {{ index .Values "measurement-service-default-limit" | quote }}
  {{- end }}
  {{- if index .Values "measurement-service-search-max-limit" }}
  - name: MEASUREMENT-SERVICE_SEARCH_MAX_LIMIT
    value: {{ index .Values "measurement-service-search-max-limit" | quote }}
  {{- end }}
  {{- if index .Values "egov-mdms-tenantId" }}
  - name: EGOV_MDMS_TENANTID
    value: {{ index .Values "egov-mdms-tenantId" | quote }}
  {{- end }}
  {{- if index .Values "egov-mdms-moduleName" }}
  - name: EGOV_MDMS_MODULENAME
    value: {{ index .Values "egov-mdms-moduleName" | quote }}
  {{- end }}
  {{- if index .Values "egov-mdms-masterName" }}
  - name: EGOV_MDMS_MASTERNAME
    value: {{ index .Values "egov-mdms-masterName" | quote }}
  {{- end }}

