apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  {{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  {{- else }}
  namespace:  {{ .Values.namespace }}  
  {{- end }}
spec:
  externalName: {{ .Values.externalName }}
  ports:
  - port: {{ .Values.httpPort }}
    protocol: TCP
    targetPort: {{ .Values.httpPort }}
  sessionAffinity: None
  type: {{ .Values.type }}

