# Common Labels
labels:
  app: "certificate-verification"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: false
  context: "certificate-verification"

# Container Configs
image:
  repository: "certificate-verification"
replicas: "1"
httpPort: 80

extraVolumes: |
  - name: certificate-verification
    configMap:
      name: certificate-verification

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf

namespace: egov
