# Common Labels
labels:
  app: "certificate-verification"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: false
  context: "certificate-verification"

# Container Configs
image:
  repository: "certificate-verification"
replicas: "1"
