# Common Labels
labels:
  app: "inbox"
  group: "rainmaker"

namespace : staging

hpa:
  enabled: true

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "inbox"
  namespace : egov


# Container Configs
image:
  repository: "inbox"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/inbox/health"
  readinessProbePath: "/inbox/health"
appType: "java-spring"
tracing-enabled: true
memory_limits: 512Mi
heap: "-Xmx256m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"

# Additional Container Envs
env: |
  - name: SERVICES_ESINDEXER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: es-indexer-host
  - name: WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: EGOV_VEHICLE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: vehicle
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: mdms-v2
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_SEARCHER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-searcher      
  - name: WORKFLOW_PROCESS_SEARCH_PATH
    value: "egov-workflow-v2/egov-wf/process/_search"
  - name: WORKFLOW_BUSINESSSERVICE_SEARCH_PATH
    value: "egov-workflow-v2/egov-wf/businessservice/_search"
  - name: WORKFLOW_PROCESS_COUNT_PATH
    value: "egov-workflow-v2/egov-wf/process/_count"
  - name: WORKFLOW_PROCESS_STATUSCOUNT_PATH
    value: "egov-workflow-v2/egov-wf/process/_statuscount"
  - name: SERVICE_SEARCH_MAPPING
    value:  {{ index .Values "service-map" | quote }}
  - name: BS_BUSINESSCODE_SERVICE_SEARCH
    value:  {{ index .Values "bs-service-map" | quote }}  
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: EGOV_ES_USERNAME
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: username
  - name: EGOV_ES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: password
  - name: SERVICES_ESINDEXER_USERNAME
    valueFrom:
      secretKeyRef:
        name:  elasticsearch-master-credentials
        key: username
  - name: SERVICES_ESINDEXER_PASSWORD
    valueFrom:
      secretKeyRef:
        name:  elasticsearch-master-credentials
        key: password
  - name: WATER_ES_INDEX
    value: {{ index .Values "water-es-index" | quote }}
  - name: SEWERAGE_ES_INDEX
    value: {{ index .Values "sewerage-es-index" | quote }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
