# Common Labels
labels:
  app: "estimates"
  group: "digit-works"

namespace: works

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "estimate"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "estimates_schema"
    image:
      repository: "estimates-db"

# Container Configs
image:
  repository: "estimates"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/estimate/health"
  readinessProbePath: "/estimate/health"
appType: "java-spring"
tracing-enabled: true
memory_limits: 512Mi
heap: "-Xmx512m -Xms512m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: SERVER_CONTEXT_PATH
    value: /estimate
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /estimate
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_HRMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-hrms
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: EGOV_CONTRACT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: contract-service
  - name: EGOV_MEASUREMENTSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: measurement-service      
  - name: EGOV_MDMS_HOST_V2
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service-v2
  - name: ESTIMATE_KAFKA_CREATE_TOPIC
    value: "save-estimate"
  - name: ESTIMATE_KAFKA_UPDATE_TOPIC
    value: "update-estimate"
  - name: KAFKA_TOPICS_NOTIFICATION_SMS
    value: "egov.core.notification.sms"
  {{- if index .Values "estimate-default-limit" }}
  - name: ESTIMATE_DEFAULT_LIMIT
    value: {{ index .Values "estimate-default-limit" | quote }} 
  {{- end }}
  {{- if index .Values "estimate-search-max-limit" }}
  - name: ESTIMATE_SEARCH_MAX_LIMIT
    value: {{ index .Values "estimate-search-max-limit" | quote }} 
  {{- end }}
  {{- if index .Values "estimate-workflow-business-service" }}
  - name: ESTIMATE_WORKFLOW_BUSINESS_SERVICE
    value: {{ index .Values "estimate-workflow-business-service" | quote }} 
  {{- end }}
  {{- if index .Values "estimate-workflow-module-name" }}
  - name: ESTIMATE_WORKFLOW_MODULE_NAME
    value: {{ index .Values "estimate-workflow-module-name" | quote }} 
  {{- end }}
  - name: WORKS_PROJECT_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: project-management-system
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: "estimate-service"
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
