# Common Labels
labels:
  app: "billing-service"
  group: "billingservices"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "billing-service"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "billing_service_schema"
    image:
      repository: "billing-service-db"

# Container Configs
image:
  repository: "billing-service"
healthChecks:
  enabled: true
  livenessProbePath: "/billing-service/health"
  readinessProbePath: "/billing-service/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: "-Dspring.profiles.active=monitoring"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: USER_SERVICE_HOSTNAME
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_APPORTION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-apportion-service
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: bs-persist
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: KAFKA_TOPICS_RECEIVINGCENTER_CREATE_NAME
    value: egov.pgr.receiving-centertype-create
  - name: KAFKA_TOPICS_SAVE_BILL
    value: save-bill-db
  - name: KAFKA_TOPICS_UPDATE_BILL
    value: update-bill-db
  - name: KAFKA_TOPICS_SAVE_BILL_KEY
    value: save-bill
  - name: KAFKA_TOPICS_UPDATE_BILL_KEY
    value: update-bill
  - name: KAFKA_TOPICS_SAVE_DEMAND
    value: save-demand
  - name: KAFKA_TOPICS_UPDATE_DEMAND
    value: update-demand
  - name: KAFKA_TOPICS_SAVE_TAXHEADMASTER
    value: save-taxHeadMaster-db
  - name: KAFKA_TOPICS_SAVE_TAXHEADMASTER_KEY
    value: save-taxHeadMaster
  - name: KAFKA_TOPICS_UPDATE_TAXHEADMASTER
    value: update-taxHeadMaster-db
  - name: KAFKA_TOPICS_UPDATE_TAXHEADMASTER_KEY
    value: update-taxHeadMaster
  - name: KAFKA_CONSUMER_CONFIG_GROUP_ID
    value: bs-masters-group
  - name: BS_BILL_SEQ_NAME
    value: seq_egbs_bill
  - name: BS_BILLDETAIL_SEQ_NAME
    value: seq_egbs_billdetail
  - name: BS_BILLDETAIL_BILLNUMBER_SEQ_NAME
    value: seq_egbs_billnumber
  - name: BS_BILLACCOUNTDETAIL_SEQ_NAME
    value: seq_egbs_billaccountdetail
  - name: BS_DEMAND_SEQ_NAME
    value: seq_egbs_demand
  - name: BS_DEMANDDETAIL_SEQ_NAME
    value: seq_egbs_demanddetail
  - name: SERVER_CONTEXT_PATH
    value: /billing-service
  - name: KAFKA_TOPICS_RECEIPT_UPDATE_DEMAND
    value: egov.collection.receipt-create
  - name: KAFKA_TOPICS_SAVE_GLCODEMASTER
    value: save-glCodeMaster-db
  - name: KAFKA_TOPICS_SAVE_GLCODEMASTER_KEY
    value: save-glCodeMaster
  - name: KAFKA_TOPICS_UPDATE_GLCODEMASTER
    value: update-glCodeMaster-db
  - name: KAFKA_TOPICS_UPDATE_GLCODEMASTER_KEY
    value: update-glCodeMaster
  - name: KAFKA_TOPICS_CREATE_TAXPERIOD_NAME
    value: save-taxperiod-db
  - name: KAFKA_TOPICS_CREATE_TAXPERIOD_KEY
    value: save-taxperiod
  - name: KAFKA_TOPICS_UPDATE_TAXPERIOD_NAME
    value: update-taxperiod-db
  - name: KAFKA_TOPICS_UPDATE_TAXPERIOD_KEY
    value: update-taxperiod
  - name: KAFKA_TOPICS_CREATE_BUSINESSSERVICEDETAIL_NAME
    value: save-businessservicedetail-db
  - name: KAFKA_TOPICS_CREATE_BUSINESSSERVICEDETAIL_KEY
    value: save-businessservicedetail
  - name: KAFKA_TOPICS_UPDATE_BUSINESSSERVICEDETAIL_NAME
    value: update-businessservicedetail-db
  - name: KAFKA_TOPICS_UPDATE_BUSINESSSERVICEDETAIL_KEY
    value: update-businessservicedetail
  - name: BS_TAXHEAD_SEQ_NAME
    value: seq_egbs_taxheadmaster
  - name: BS_TAXHEAD_CODE_SEQ_NAME
    value: seq_egbs_taxheadmastercode
  - name: BS_GLCODEHEAD_SEQ_NAME
    value: seq_egbs_glcodemaster
  - name: BS_TAXPERIOD_SEQ_NAME
    value: seq_egbs_taxperiod
  - name: BS_BUSINESSSERVICEDETAIL_SEQ_NAME
    value: seq_egbs_business_srvc_details
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"     
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
