# Common Labels
labels:
  app: "egov-otp"
  group: "core"

hpa:
  enabled: true

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "otp"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_otp_schema"
    image:
      repository: "egov-otp-db"

# Container Configs
image:
  repository: "egov-otp"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/otp/health"
  readinessProbePath: "/otp/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
memory_limits: 512Mi

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"   
  - name: MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: mdms-v2
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: mdms-v2   
