# Common Labels
labels:
  app: "egov-location"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "egov-location"

service:
  additionalAnnotations: |
    gateway-burstCapacity: "1"
    gateway-keyResolver: "ipKeyResolver"
    gateway-replenishRate: "2"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_location_schema"
    image:
      repository: "egov-location-db"

# Container Configs
image:
  repository: "egov-location"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/egov-location/health"
  readinessProbePath: "/egov-location/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
memory_limits: 512Mi
java-args: "-Dspring.profiles.active=monitoring"
gmaps: true
# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-location-consumer-group
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  {{- if index .Values "global" "serializers-timezone-in-ist" }}
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
  {{- end }}
  - name: SERVER_PORT
    value: "8080"
  - name: EGOV_SERVICES_EGOV_MDMS_HOSTNAME
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: {{ .Values.mdmsHost | default "egov-mdms-service" }} 
  - name: EGOV_SERVICES_EGOV_MDMS_SEARCHPATH
    value: {{ .Values.mdmsSearchPath | default "egov-mdms-service/v1/_search" }}
  {{- if index .Values "gmaps" }}
  - name: GMAPS_API_KEY
    valueFrom:
      secretKeyRef:
        name: egov-location
        key: gmapskey
  {{- end }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"           
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
