# Common Labels
labels:
  app: "measurement-registry"
  group: "works"

namespace: staging

hpa:
  enabled: true

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "measurement-registry"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "measurement-registry_schema"
    image:
      repository: "measurement-registry-db"
    env: |
      {{- if index .Values "measurement-registry-ismultischema-enabled" }}        
      - name: SCHEMA_NAME
        value: {{ index .Values "measurement-registry-schemas" | quote }}
      {{- end }}
      - name: "DB_URL"
        valueFrom: 
          configMapKeyRef: 
            name: egov-config
            key: db-url-works
      - name: "SCHEMA_TABLE"
        value: {{ .Values.initContainers.dbMigration.schemaTable | quote }}              
      - name: "FLYWAY_USER"
        valueFrom: 
          secretKeyRef: 
            name: db
            key: flyway-username
      - name: "FLYWAY_PASSWORD"
        valueFrom:
          secretKeyRef: 
            name: db
            key: flyway-password
      - name: "FLYWAY_LOCATIONS"
        valueFrom: 
          configMapKeyRef: 
            name: egov-config
            key: flyway-locations  
      {{- if index .Values.global "is-environment-central-instance" }}        
      - name: IS_ENVIRONMENT_CENTRAL_INSTANCE
        valueFrom:
          configMapKeyRef:
            name: egov-config
            key: is-environment-central-instance
      - name: STATE_LEVEL_TENANTID_LENGTH
        valueFrom:
          configMapKeyRef:
            name: egov-config
            key: state-level-tenantid-length
      {{- end }}

# Container Configs
image:
  repository: "measurement-registry"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/measurement/health"
  readinessProbePath: "/measurement/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_CONTEXT_PATH
    value: /measurement
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /measurement
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/egov-mdms-service/v1/_search"
  - name: EGOV_MDMS_V2_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service-v2  
  - name: EGOV_MDMS_V2_SEARCH_ENDPOINT
    value: "/mdms-v2/v1/_search"
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  - name: APP_TIMEZONE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: timezone
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  {{- if index .Values "measurement-kafka-create-topic" }}
  - name: MEASUREMENT_KAFKA_CREATE_TOPIC
    value: {{ index .Values "measurement-kafka-create-topic" | quote }}
  {{- end }}
  {{- if index .Values "measurement-kafka-update-topic" }}
  - name: MEASUREMENT_KAFKA_UPDATE_TOPIC
    value: {{ index .Values "measurement-kafka-update-topic" | quote }}
  {{- end }}
  {{- if index .Values "measurement-idgen-name" }}
  - name: MEASUREMENT_IDGEN_NAME
    value: {{ index .Values "measurement-idgen-name" | quote }}
  {{- end }}
  {{- if index .Values "measurement-idgen-format" }}
  - name: MEASUREMENT_IDGEN_FORMAT
    value: {{ index .Values "measurement-idgen-format" | quote }}
  {{- end }}
  {{- if index .Values "mb-default-offset" }}
  - name: MB_DEFAULT_OFFSET
    value: {{ index .Values "mb-default-offset" | quote }}
  {{- end }}
  {{- if index .Values "mb-default-limit" }}
  - name: MB_DEFAULT_LIMIT
    value: {{ index .Values "mb-default-limit" | quote }}
  {{- end }}
  {{- if index .Values "mb-search-max-limit" }}
  - name: MB_SEARCH_MAX_LIMIT
    value: {{ index .Values "mb-search-max-limit" | quote }}
  {{- end }}
  {{- if index .Values "state-level-tenant-id" }}
  - name: STATE_LEVEL_TENANT_ID
    value: {{ index .Values "state-level-tenant-id" | quote }}
  {{- end }}
  

