# Default values for egov-finance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: upyog

# Common Labels
labels:
  app: "egov-finance"

# Container Configs
image:
  repository: "egov-finance"
  pullPolicy: IfNotPresent
  tag: latest
replicas: "1"
httpPort: 8080

resources: |
  limits:
    memory: "3Gi"
  requests:
    memory: "3Gi"
min-pool-connection: "5"
max-pool-connection: "5"
collection-version: V2

env: |
  - name: DB_URL
    valueFrom: 
      configMapKeyRef: 
        name: egov-config
        key: erp-db-url
  - name: DB_USERNAME
    valueFrom: 
      secretKeyRef: 
        name: db
        key: username
  - name: DB_PASSWORD
    valueFrom: 
      secretKeyRef: 
        name: db
        key: password
  - name: NO_TXN_DB_URL
    valueFrom: 
      configMapKeyRef: 
        name: egov-config
        key: erp-db-url   
  - name: NO_TXN_DB_USER
    valueFrom: 
      secretKeyRef: 
        name: db
        key: username
  - name: NO_TXN_DB_PASSWORD 
    valueFrom: 
      secretKeyRef: 
        name: db
        key: password
  - name: mail-sender-password
    valueFrom: 
      secretKeyRef: 
        name: egov-si-microservice
        key: mail-sender-password
  - name: sms-username
    valueFrom:
      secretKeyRef:  
        name: egov-notification-sms
        key: username
  - name: sms-password
    valueFrom:
      secretKeyRef:  
        name: egov-notification-sms
        key: password      
  - name: axis-merchant-access-code
    valueFrom:
      secretKeyRef:  
        name: egov-pg-service
        key: axismerchantaccesscode
  - name: axis-merchant-user
    valueFrom:
      secretKeyRef:  
        name: egov-pg-service
        key: axismerchantuser
  - name: axis-merchant-pwd
    valueFrom:
      secretKeyRef:  
        name: egov-pg-service
        key: axismerchantpwd
  - name: axis-merchant-secret-key
    valueFrom:
      secretKeyRef:  
        name: egov-pg-service
        key: axismerchantsecret
  - name: si-microservice-password
    valueFrom:
      secretKeyRef:  
        name: egov-si-microservice
        key: si-microservice-password
  - name: si-microservice-user
    valueFrom:
      secretKeyRef:  
        name: egov-si-microservice
        key: si-microservice-user
  - name: min-pool-size
    value: {{ index .Values "min-pool-connection" | quote }}
  - name: max-pool-size
    value: {{ index .Values "max-pool-connection" | quote }}
healthChecks:
  enabled: true
  livenessProbePath: "/"
  readinessProbePath: "/"

extraVolumeMounts: |
  - mountPath: /opt/jboss/wildfly/modules/system/layers/base/org/egov/settings/main/config/egov-erp-override.properties
    name: override-config
    subPath: egov-erp-override.properties 
extraVolumes: |
  - name: override-config
    configMap:
      name: egov-finance-config        


scheduler: true
dev_mode: false
finance: true
filestore: /tmp/egovfilestore
filestore_beanname: microDiskFileStoreService
rollout_dashboard_cron_expression: 0 0 * ? * *
token_authorization_key: Basic ZWdvdi11c2VyLWNsaWVudDo=
secure_cookie: true
sms: true
mail: true
captcha: low
redis_host: redis.backbone 
redis_port: 6379
db_flyway: true
statewide_migration: true
multitenancy: true
mail_config: |
  mail.port=465
  mail.host=smtp.gmail.com
  mail.protocol=smtps
  mail.sender.username=punjabulb@gmail.com
  mail.sender.password=${mail-sender-password}
  mail.smtps.auth=true
  mail.smtps.starttls.enable=true
  mail.smtps.debug=false

smc_config: |
  sms.provider.url=https://bmg.spicedigital.in/SMSGateway/messagePush
  sms.sender.username=${sms-username}
  sms.sender.password=${sms-password}
  sms.sender=PBSEWA
  sms.sender.req.param.name=senderId
  sms.sender.username.req.param.name=username
  sms.sender.password.req.param.name=password
  sms.destination.mobile.req.param.name=mobile
  sms.message.req.param.name=message
  sms.extra.req.params=messageType=text
  sms.error.codes=401,403,404,405,406,407,408,409,410,411,412,413,414       
  
elastic_config: |
  #elasticsearch.hosts=punjab-dev-es-cluster
  #elasticsearch.port=9300
  #elasticsearch.cluster.name=punjab-dev-es-cluster
  
elastic_search_config: |
  search.index.q=java:/jms/queue/searchindex
  #search.hosts=punjab-dev-es-cluster
  #search.port=9300
  #search.clusterName=punjab-dev-es-cluster

tenants: |
  tenant.sunam-dev.egovernments.org=sunam
  #tenant.longowal-dev.egovernments.org=longowal
  #tenant.kotfatta-dev.egovernments.org=kotfatta
  #tenant.bhikhi-dev.egovernments.org=bhikhi
  #tenant.budhlada-dev.egovernments.org=budhlada
  #tenant.morinda-dev.egovernments.org=morinda
  #tenant.boha-dev.egovernments.org=boha
  #tenant.khemkaran-dev.egovernments.org=khemkaran
  #tenant.mallanwala-dev.egovernments.org=mallanwala
  #tenant.ajnala-dev.egovernments.org=ajnala
  #tenant.badhnikalan-dev.egovernments.org=badhnikalan
  #tenant.majitha-dev.egovernments.org=majitha
  #tenant.ramdass-dev.egovernments.org=ramdass
  #tenant.jandialaguru-dev.egovernments.org=jandialaguru
  #tenant.bareta-dev.egovernments.org=bareta
  #tenant.phillaur-dev.egovernments.org=phillaur
  #tenant.samana-dev.egovernments.org=samana
  #tenant.sangatmandi-dev.egovernments.org=sangatmandi
  #tenant.talwandisabo-dev.egovernments.org=talwandisabo
  #tenant.balachaur-dev.egovernments.org=balachaur
  #tenant.bassipathana-dev.egovernments.org=bassipathana
  #tenant.batala-dev.egovernments.org=batala
  #tenant.srihargobindpur-dev.egovernments.org=srihargobindpur
  #tenant.bhadaur-dev.egovernments.org=bhadaur
  #tenant.dirba-dev.egovernments.org=dirba
  #tenant.bhuchomandi-dev.egovernments.org=bhuchomandi
  #tenant.sanaur-dev.egovernments.org=sanaur
  #tenant.sujanpur-dev.egovernments.org=sujanpur
  #tenant.jaitu-dev.egovernments.org=jaitu
  #tenant.goniana-dev.egovernments.org=goniana
  #tenant.mansa-dev.egovernments.org=mansa
  #tenant.rajasansi-dev.egovernments.org=rajasansi
  #tenant.banga-dev.egovernments.org=banga
  tenant.jalandhar-dev.egovernments.org=jalandhar
  tenant.amritsar-dev.egovernments.org=amritsar
  tenant.phagwara-dev.egovernments.org=phagwara
  location.user.role=Collection Operator
  collection.debitaccounthead.client.impl.class=org.egov.collection.integration.services.DebitAccountHeadDetailsServiceImpl

payment-gatway-credential: |
  axis.version=1
  axis.command=pay
  axis.command.query=queryDR
  axis.access.code=${axis-merchant-access-code}
  axis.merchant=${axis-merchant-id}
  axis.locale=en
  axis.operator.id=${axis-merchant-user}
  axis.password=${axis-merchant-pwd}
  axis.reconcile.url=https://migs.mastercard.com.au/vpcdps
  axis.secure.secret=${axis-merchant-secret-key}
  axis.hash.algorithm=SHA256

microservice: |
  egov.collection.version={{ index .Values "collection-version" }}
  egov.default.services.endpoint=https://egov-micro-dev.egovernments.org/
  egov.hrms.service.endpoint=http://egov-hrms.egov:8080/
  egov.accesscontrol.service.endpoint=http://egov-accesscontrol.egov:8080/
  egov.hr.masters.service.endpoint=http://hr-masters.egov:8080/
  egov.user.service.endpoint=http://egov-user.egov:8080/
  egov.common.masters.endpoint=http://egov-common-masters.egov:8080/
  egov.billing.service.endpoint=http://billing-service.egov:8080/
  egov.collection.service.endpoint=http://collection-services.egov:8080/
  egov.egf.master.service.endpoint=http://egf-master.egov:8080/
  egov.egf.instrument.service.endpoint=http://egf-instrument.egov:8080/
  egov.mdms.service.endpoint=http://egov-mdms-service.egov:8080/
  egov.indexer.service.endpoint=http://egov-indexer.egov:8080/
  egov.services.billing.service.bill.generate=billing-service/bill/v2/_fetchbill
  egov.filestore.service.endpoint=http://egov-filestore.egov:8080/

systemintegration: |
  si.microservice.user=${si-microservice-user}
  si.microservice.password=${si-microservice-password}
  si.microservice.usertype=SYSTEM
  si.microservice.scope=read
  si.microservice.granttype=password

# Ingress Configs
ingress:
  enabled: true
  zuul: false
  waf: 
    enabled: false
  #hostName: jalandhar-dev.egovernments.org
  additionalAnnotations: |
    nginx.ingress.kubernetes.io/rewrite-target: /services
  context: "services"
  

