{{- $serviceName := include "nginx-ingress.name" . -}}
{{- if and .Values.controller.metrics.enabled .Values.controller.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "nginx-ingress.controller.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "nginx-ingress.name" . }}
    {{- if .Values.controller.metrics.serviceMonitor.additionalLabels }}
{{ toYaml .Values.controller.metrics.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: metrics
      interval: {{ .Values.controller.metrics.serviceMonitor.scrapeInterval }}
      {{- if .Values.controller.metrics.serviceMonitor.honorLabels }}
      honorLabels: true
      {{- end }}
  {{- if .Values.controller.metrics.serviceMonitor.namespaceSelector }}
  namespaceSelector:
{{ toYaml .Values.controller.metrics.serviceMonitor.namespaceSelector | indent 4 -}}
  {{ else }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "nginx-ingress.name" . }}
{{- end }}