{{- if .Capabilities.APIVersions.Has "cert-manager.io/v1alpha1" }}
apiVersion: cert-manager.io/v1alpha1
{{- else }}
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.stage.name }} 
spec:
  acme:
    email: {{ .Values.clusterIssuer.stage.acme.email }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.stage.name }}
    server: {{ .Values.clusterIssuer.stage.acme.server }}
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}          
---
{{- if .Capabilities.APIVersions.Has "cert-manager.io/v1alpha1" }}
apiVersion: cert-manager.io/v1alpha1
{{- else }}
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.prod.name }}
spec:
  acme:
    email: {{ .Values.clusterIssuer.stage.acme.email }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.prod.name }}
    server: {{ .Values.clusterIssuer.prod.acme.server }}
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }} 