# Common Labels
labels:
  app: "attendance-service"
  group: "digit-works"

namespace: works

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "attendance"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "attendance_service_schema"
    image:
      repository: "attendance-service-db"

# Container Configs
image:
  repository: "attendance-service"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/attendance/health"
  readinessProbePath: "/attendance/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: SERVER_CONTEXT_PATH
    value: /attendance
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /attendance 
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: ATTENDANCE_SERVICE_LOG_KAFKA_CREATE_TOPIC
    value: "save-attendance-log"
  - name: ATTENDANCE_SERVICE_LOG_KAFKA_UPDATE_TOPIC
    value: "update-attendance-log"
  - name: ATTENDANCE_SERVICE_REGISTER_KAFKA_CREATE_TOPIC
    value: "save-attendance"
  - name: ATTENDANCE_SERVICE_REGISTER_KAFKA_UPDATE_TOPIC
    value: "update-attendance"
  - name: ATTENDANCE_SERVICE_STAFF_KAFKA_CREATE_TOPIC
    value: "save-staff"
  - name: ATTENDANCE_SERVICE_STAFF_KAFKA_UPDATE_TOPIC
    value: "update-staff"
  - name: ATTENDANCE_SERVICE_ATTENDEE_KAFKA_CREATE_TOPIC
    value: "save-attendee"
  - name: ATTENDANCE_SERVICE_ATTENDEE_KAFKA_UPDATE_TOPIC
    value: "update-attendee"
  {{- if index .Values "attendance-service-register-default-offset" }}
  - name: ATTENDANCE_SERVICE_REGISTER_DEFAULT_OFFSET
    value: {{ index .Values "attendance-service-register-default-offset" | quote }} 
  {{- end }}
  {{- if index .Values "attendance-service-register-default-limit" }}
  - name: ATTENDANCE_SERVICE_REGISTER_DEFAULT_LIMIT
    value: {{ index .Values "attendance-service-register-default-limit" | quote }} 
  {{- end }}
  {{- if index .Values "attendance-service-register-search-max-limit" }}
  - name: ATTENDANCE_SERVICE_REGISTER_SEARCH_MAX_LIMIT
    value: {{ index .Values "attendance-service-register-search-max-limit" | quote }} 
  {{- end }}
  {{- if index .Values "attendance-service-individual-service-integration-required" }}
  - name: ATTENDANCE_SERVICE_INDIVIDUAL_SERVICE_INTEGRATION_REQUIRED
    value: {{ index .Values "attendance-service-individual-service-integration-required" | quote }} 
  {{- end }}
  {{- if index .Values "attendance-service-staff-service-integration-required" }}
  - name: ATTENDANCE_SERVICE_STAFF_SERVICE_INTEGRATION_REQUIRED
    value: {{ index .Values "attendance-service-staff-service-integration-required" | quote }} 
  {{- end }}
  {{- if index .Values "attendance-service-document-id-verification-required" }}
  - name: ATTENDANCE_SERVICE_DOCUMENT_ID_VERIFICATION_REQUIRED
    value: {{ index .Values "attendance-service-document-id-verification-required" | quote }} 
  {{- end }}