# Common Labels
labels:
  app: "egov-user-event"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "egov-user-event"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_user_event_schema_version"
    image:
      repository: "egov-user-event-db"

# Container Configs
image:
  repository: "egov-user-event"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/egov-user-event/health"
  readinessProbePath: "/egov-user-event/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
memory_limits: 512Mi
java-args: ""

# Additional Container Envs
env: |
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: /egov-mdms-service/v1/_search
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-user-events
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: KAFKA_TOPICS_PERSISTER_SAVE_EVENTS
    value: save-user-events
  - name: KAFKA_TOPICS_PERSISTER_UPDATE_EVENTS
    value: update-user-events
  - name: KAFKA_TOPICS_LLT_DETAILS
    value: user-events-llt
  - name: KAFKA_TOPICS_SAVE_EVENTS
    value: persist-user-events-async
  - name: KAFKA_TOPICS_UPDATE_EVENTS
    value: update-user-events-async
  - name: MSEVA_NOTIF_SEARCH_OFFSET
    value: "0"
  - name: MSEVA_NOTIF_SEARCH_LIMIT
    value: "200"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"    
  - name: EGOV_LOCALISATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_LOCALISATION_IS_STATELEVEL
    value: "false"
  - name: MSEVA_NOTIF_SEARCH_OFFSET
    value: "0"
  - name: MSEVA_NOTIF_SEARCH_LIMIT
    value: "200"                     
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
