# Common Labels
labels:
  app: "facility"
  group: "health"

namespace: health

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "facility"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "facility_schema"
    image:
      repository: "facility-db"

# Container Configs
image:
  repository: "facility"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/facility/health"
  readinessProbePath: "/facility/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""
persist-yml-path: "file:///work-dir/health-campaign-config/egov-persister/facility-persister.yml"
indexer-yml-path: "file:///work-dir/health-campaign-config/egov-indexer/facility-indexer.yml"

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: health-project
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_IDGEN_PATH
    value: "egov-idgen/id/_generate"
  - name: EGOV_IDGEN_INTEGRATION_ENABLED
    value: "true"
  - name: FACILITY.IDGEN.ID.FORMAT
    value: "facility.id"
  - name: SPRING_REDIS_HOST
    value: redis.backbone
  - name: SPRING_REDIS_PORT
    value: "6379"
  - name: SPRING_CACHE_TYPE
    value: "redis"
  - name: SPRING_CACHE_REDIS_TIME-TO-LIVE
    value: "60"
  - name: SPRING_CACHE_AUTOEXPIRY
    value: "true"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-enable-debug" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  
  - name: FACILITY.KAFKA.CREATE.TOPIC
    value: "save-facility-health-topic"
  - name: FACILITY.KAFKA.UPDATE.TOPIC
    value: "update-facility-health-topic"
  - name: FACILITY.KAFKA.DELETE.TOPIC
    value: "delete-facility-health-topic"
  - name: FACILITY.CONSUMER.BULK.DELETE.TOPIC
    value: "delete-facility-bulk-health-topic"
  - name: FACILITY.CONSUMER.BULK.CREATE.TOPIC
    value: "create-facility-bulk-health-topic"
  - name: FACILITY.CONSUMER.BULK.UPDATE.TOPIC
    value: "update-facility-bulk-health-topic"
  - name: EGOV_BOUNDARY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: boundary-service
  - name: EGOV_BOUNDARY_SEARCH_URL
    value: "/boundary-service/boundary/_search"