apiVersion: v2
description: A Helm Chart to Deploy Digit Core Services
name: core-services
version: 1.0.0  # Update this version as per your release
appVersion: 1.0.0  # Update the app version as per your application's version

dependencies:
  - name: audit-service
    version: 0.1.0
    repository: "file://audit-service"

  - name: chatbot
    version: 0.1.0
    repository: "file://chatbot"

  - name: common
    version: 0.0.5
    repository: "file://../common"
