# Common Labels
labels:
  app: "mukta-works-shg-app"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "mukta-works-shg-app"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "mukta-works-shg-app"
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/mukta-works-shg-app/"
  readinessProbePath: "/mukta-works-shg-app/"

namespace: works 
extraVolumes: |
  - name: js-injection
    configMap:
      name: works-shg-app-js-injection
extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
