# Common Labels
labels:
  app: "organisation"
  group: "works"

namespace: staging

hpa:
  enabled: true

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "org-services"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "organisation_schema"
    image:
      repository: "organisation-db"
    env: |
      {{- if index .Values "organisation-ismultischema-enabled" }}        
      - name: SCHEMA_NAME
        value: {{ index .Values "organisation-schemas" | quote }}
      {{- end }}
      - name: "DB_URL"
        valueFrom: 
          configMapKeyRef: 
            name: egov-config
            key: db-url-works
      - name: "SCHEMA_TABLE"
        value: {{ .Values.initContainers.dbMigration.schemaTable | quote }}              
      - name: "FLYWAY_USER"
        valueFrom: 
          secretKeyRef: 
            name: db
            key: flyway-username
      - name: "FLYWAY_PASSWORD"
        valueFrom:
          secretKeyRef: 
            name: db
            key: flyway-password
      - name: "FLYWAY_LOCATIONS"
        valueFrom: 
          configMapKeyRef: 
            name: egov-config
            key: flyway-locations  
      {{- if index .Values.global "is-environment-central-instance" }}        
      - name: IS_ENVIRONMENT_CENTRAL_INSTANCE
        valueFrom:
          configMapKeyRef:
            name: egov-config
            key: is-environment-central-instance
      - name: STATE_LEVEL_TENANTID_LENGTH
        valueFrom:
          configMapKeyRef:
            name: egov-config
            key: state-level-tenantid-length
      {{- end }}

# Container Configs
image:
  repository: "organisation"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/org-services/health"
  readinessProbePath: "/org-services/health"
appType: "java-spring"
tracing-enabled: true
java-enable-debug: true
heap: "-Xmx192m -Xms192m"
java-args: "-Dspring.main.allow-bean-definition-overriding=true"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: SERVER_CONTEXT_PATH
    value: /org-services
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /org-services  
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/egov-mdms-service/v1/_search"
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: EGOV_URL_SHORTNER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-url-shortening
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: WORKS_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: individual
  - name: EGOV_HRMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-hrms
  - name: EGOV_ENC_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-enc-service
  - name: ORG_KAFKA_CREATE_TOPIC
    value: "save-org"
  - name: ORG_KAFKA_UPDATE_TOPIC
    value: "update-org"
  - name: KAFKA_TOPICS_NOTIFICATION_SMS
    value: "egov.core.notification.sms"
  {{- if index .Values "org-default-limit" }}
  - name: ORG_DEFAULT_LIMIT
    value: {{ index .Values "org-default-limit" | quote }} 
  {{- end }}
  {{- if index .Values "org-search-max-limit" }}
  - name: ORG_SEARCH_MAX_LIMIT
    value: {{ index .Values "org-search-max-limit" | quote }} 
  {{- end }}
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: "organisation"
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user 
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  {{- if index .Values "egov-location-hierarchy-type" }}
  - name: EGOV_LOCATION_HIERARCHY_TYPE
    value: {{ index .Values "egov-location-hierarchy-type" | quote }} 
  {{- end }}      
  {{- if index .Values "contract-cbo-url-host" }}
  - name: CONTRACT_CBO_URL_HOST
    value: {{ index .Values "contract-cbo-url-host" | quote }}
  {{- end }}
  {{- if index .Values "contract-cbo-url-endpoint" }}
  - name: CONTRACT_CBO_URL_ENDPOINT
    value: {{ index .Values "contract-cbo-url-endpoint" | quote }}
  {{- end }}
  {{- if index .Values "organisation-contact-details-update-topic" }}
  - name: ORGANISATION_CONTACT_DETAILS_UPDATE_TOPIC
    value: {{ index .Values "organisation-contact-details-update-topic" | quote }}
  {{- end }}
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
