# Common Labels
labels:
  app: "attendance"
  group: "digit-works"

namespace: works

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "attendance"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "attendance_schema"
    image:
      repository: "attendance-db"

# Container Configs
image:
  repository: "attendance"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/attendance/health"
  readinessProbePath: "/attendance/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: SERVER_CONTEXT_PATH
    value: /attendance
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /attendance 
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: WORKS_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: individual
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: ATTENDANCE_LOG_KAFKA_CREATE_TOPIC
    value: "save-attendance-log"
  - name: ATTENDANCE_LOG_KAFKA_UPDATE_TOPIC
    value: "update-attendance-log"
  - name: ATTENDANCE_REGISTER_KAFKA_CREATE_TOPIC
    value: "save-attendance"
  - name: ATTENDANCE_REGISTER_KAFKA_UPDATE_TOPIC
    value: "update-attendance"
  - name: ATTENDANCE_STAFF_KAFKA_CREATE_TOPIC
    value: "save-staff"
  - name: ATTENDANCE_STAFF_KAFKA_UPDATE_TOPIC
    value: "update-staff"
  - name: ATTENDANCE_ATTENDEE_KAFKA_CREATE_TOPIC
    value: "save-attendee"
  - name: ATTENDANCE_ATTENDEE_KAFKA_UPDATE_TOPIC
    value: "update-attendee"
  {{- if index .Values "contracts-time-extension-update-topic" }}
  - name: CONTRACTS_TIME_EXTENSION_UPDATE_TOPIC
    value: {{ index .Values "contracts-time-extension-update-topic" | quote }} 
  {{- end }}
  {{- if index .Values "attendance-register-default-offset" }}
  - name: ATTENDANCE_REGISTER_DEFAULT_OFFSET
    value: {{ index .Values "attendance-register-default-offset" | quote }} 
  {{- end }}
  {{- if index .Values "attendance-register-default-limit" }}
  - name: ATTENDANCE_REGISTER_DEFAULT_LIMIT
    value: {{ index .Values "attendance-register-default-limit" | quote }} 
  {{- end }}
  {{- if index .Values "attendance-register-search-max-limit" }}
  - name: ATTENDANCE_REGISTER_SEARCH_MAX_LIMIT
    value: {{ index .Values "attendance-register-search-max-limit" | quote }} 
  {{- end }}
  {{- if index .Values "attendance-individual-service-integration-required" }}
  - name: ATTENDANCE_INDIVIDUAL_SERVICE_INTEGRATION_REQUIRED
    value: {{ index .Values "attendance-individual-service-integration-required" | quote }} 
  {{- end }}
  {{- if index .Values "attendance-staff-service-integration-required" }}
  - name: ATTENDANCE_STAFF_SERVICE_INTEGRATION_REQUIRED
    value: {{ index .Values "attendance-staff-service-integration-required" | quote }} 
  {{- end }}
  {{- if index .Values "attendance-document-id-verification-required" }}
  - name: ATTENDANCE_DOCUMENT_ID_VERIFICATION_REQUIRED
    value: {{ index .Values "attendance-document-id-verification-required" | quote }} 
  {{- end }}
  {{- if index .Values "attendance-register-open-search-enabled-roles" }}
  - name: ATTENDANCE_REGISTER_OPEN_SEARCH_ENABLED_ROLES
    value: {{ index .Values "attendance-register-open-search-enabled-roles" | quote }} 
  {{- end }}
  {{- if index .Values "works-individual-search-endpoint" }}
  - name: WORKS_INDIVIDUAL_SEARCH_ENDPOINT
    value: {{ index .Values "works-individual-search-endpoint" | quote }}
  {{- end }}
  {{- if index .Values "organisation-contact-details-update-topic" }}
  - name: ORGANISATION_CONTACT_DETAILS_UPDATE_TOPIC
    value: {{ index .Values "organisation-contact-details-update-topic" | quote }}
  {{- end }}
  