# Common Labels
labels:
  app: "mailbot"
  group: "core"

ingress:
  enabled: false

# Init Containers Configs
initContainers:
  gitSync:
    enabled: true
    repo: "git@github.com:egovernments/configs"
    branch: "master"      

# Container Configs
image:
  repository: "mailbot"
replicas: "1"
tracing-enabled: true
healthChecks:
  enabled: true
  livenessProbePath: "/mailbot/actuator/health"
  readinessProbePath: "/mailbot/actuator/health"
heap: "-Xmx192m -Xms192m"
java-args: ""
config-paths: "file:///work-dir/configs/mailbot/case-management.yaml"
cache-expiry-email: "10"

# Additional Container Envs
env: |       
  - name: STORE_HOME_ISOLATION_USERNAME
    valueFrom:
      secretKeyRef:
        name: home-isolation-notification-mail
        key: mailsenderusername                   
  - name: STORE_HOME_ISOLATION_PASSWORD
    valueFrom:
      secretKeyRef:
        name: home-isolation-notification-mail
        key: mailsenderpassword        
  - name: SPRING_DATASOURCE_TOMCAT_INITIAL_SIZE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: spring-datasource-tomcat-initialSize
  - name: SERVER_TOMCAT_MAX_THREADS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: server-tomcat-max-threads
  - name: SERVER_TOMCAT_MAX_CONNECTIONS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: server-tomcat-max-connections
  - name: SPRING_DATASOURCE_TOMCAT_MAX_ACTIVE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: spring-datasource-tomcat-max-active  
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers 
  - name: DATA_UPLOAD_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: data-upload
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user-enc
  - name: MDMS_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: internal-gateway
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: "/mailbot"
  - name: EGOV_ROOT_TENANT_ID
    valueFrom:
      configMapKeyRef:
        key: egov-state-level-tenant-id
        name: egov-config          
  - name: CONFIG_REPO_PATH
    value: {{ index .Values "config-paths" | quote }}    
  - name: CACHE_EXPIRY_USER_EMAIL_ADDRESS
    value: {{ index .Values "cache-expiry-email" | quote }}        
  - name: APP_TIMEZONE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: timezone      
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}    
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}  
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: state-level-tenant-id