# Common Labels
labels:
  app: "pqm-anomaly-finder"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "pqm-anomaly-finder"
  
# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "pqm_anomaly_finder_schema"
    image:
      repository: "pqm-anomaly-finder-db"
      tag: "v1.1.0-856ca71376-64"
    env: |
        {{- if index .Values "pqm-anomaly-finder-ismultischema-enabled" }}        
        - name: SCHEMA_NAME
          value: {{ index .Values "pqm-anomaly-finder-schemas" | quote }}
        {{- end }}
        - name: "DB_URL"
          valueFrom: 
            configMapKeyRef: 
              name: egov-config
              key: db-url
        - name: "SCHEMA_TABLE"
          value: {{ .Values.initContainers.dbMigration.schemaTable | quote }}              
        - name: "FLYWAY_USER"
          valueFrom: 
            secretKeyRef: 
                name: db
                key: flyway-username
        - name: "FLYWAY_PASSWORD"
          valueFrom:
            secretKeyRef: 
                name: db
                key: flyway-password
        - name: "FLYWAY_LOCATIONS"
          valueFrom: 
            configMapKeyRef: 
                name: egov-config
                key: flyway-locations

# Container Configs
image:
  repository: "pqm-anomaly-finder"
  tag: "v1.1.0-856ca71376-64"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/pqm-anomaly-finder/health"
  readinessProbePath: "/pqm-anomaly-finder/health"
appType: "java-spring"
tracing-enabled: true
memory_limits: 512Mi
heap: "-Xmx384m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"

# Additional Container Envs
env: |
  - name: PQM_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: pqm-service
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: mdms-service-v2
  - name: EGOV_URL_SHORTNER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-url-shortening
  - name: EGOV_PDF_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: pdf-service
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_UI_APP_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-pqm-anomaly-finder
  - name: PERSISTER_SAVE_FSM_TOPIC
    value: save-pqm-anomaly-finder-application
  - name: PERSISTER_UPDATE_FSM_TOPIC
    value: update-pqm-anomaly-finder-application
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  {{- if index .Values "java-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-debug" | quote }}
  {{- else }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  {{- if index .Values "global" "is-environment-central-instance" }}        
  - name: IS_ENVIRONMENT_CENTRAL_INSTANCE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: is-environment-central-instance
  {{- end }}
  {{- if index .Values "global" "is-environment-central-instance" }}        
  - name: STATE_LEVEL_TENANTID_LENGTH
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: state-level-tenantid-length
  {{- end }}
