# Common Labels
labels:
  app: "egov-survey-services"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "egov-survey-services"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_survey_services_schema"
    image:
      repository: "egov-survey-services-db"

# Container Configs
image:
  repository: "egov-survey-services"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/egov-survey-services/health"
  readinessProbePath: "/egov-survey-services/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx128m -Xms128m"
java-args: "-Dspring.profiles.active=monitoring"

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-du-services
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: PERSISTER_SAVE_SURVEY_TOPIC
    value: save-ss-survey
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/egov-mdms-service/v1/_search"
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: SS_NOTIFICATION_UI_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"