{{- with index .Values "cluster-configs" "networkpolicy" }}
{{- range .namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
   name: {{ . }}-admin-role-binding
   namespace: {{ . }}
subjects:
  - kind: User
    name: {{ . }}-admin-user
    namespace: {{ . }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ . }}-admin-role
# ---
# apiVersion: rbac.authorization.k8s.io/v1beta1
# kind: RoleBinding
# metadata:
#   name: {{ . }}-user-role-binding
#   namespace: {{ . }}
# subjects:
#  - kind: User
#    name: {{ . }}-readonly-user
#    namespace: {{ . }}
# roleRef:
#    apiGroup: rbac.authorization.k8s.io
#    kind: Role
#    name: {{ . }}-user-role
{{- end }}
---
{{- end }}
