# Common Labels
labels:
  app: "egov-filestore"
  group: "core"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_filestore_schema"
    image:
      repository: "egovio/egov-filestore-db"

# Ingress Configs
ingress:
  zuul: true
  context: "filestore"      

# Container Configs
image:
  repository: "egovio/egov-filestore"
replicas: "1"
appType: "java-spring"
tracing-enabled: true
is-bucket-fixed: "true"
fixed-bucketname: "egov-rainmaker"
heap: "-Xmx192m -Xms192m"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: FILE_STORAGE_MOUNT_PATH
    value: "/filestore"
  - name: TEMP_FOLDER_PATH
    value: "/tmp"
  - name: SPRING_HTTP_MULTIPART_MAX_FILE_SIZE
    value: "6MB"
  {{- if index .Values "is-s3-enabled" }}
  - name: ISS3ENABLED
    value: "true"
  - name: AWS_KEY
    valueFrom:
      secretKeyRef:
        name: egov-filestore
        key: awskey
  - name: AWS_SECRETKEY
    valueFrom:
      secretKeyRef:
        name: egov-filestore
        key: awssecretkey
  {{- end }}
  {{- if index .Values "is-bucket-fixed" }}
  - name: IS_BUCKET_FIXED
    value: {{ index .Values "is-bucket-fixed" | quote }}
  {{- end }}
  {{- if index .Values "fixed-bucketname" }}
  - name: FIXED_BUCKETNAME
    value: {{ index .Values "fixed-bucketname" | quote }}
  {{- end }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
