# Common Labels
labels:
  app: "transformer"
  group: "health"

namespace: health

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "transformer"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: false
    schemaTable: "transformer_schema"
    image:
      repository: "transformer-db"

# Container Configs
image:
  repository: "transformer"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/transformer/health"
  readinessProbePath: "/transformer/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx1024m -Xms384m"
java-args: ""
memory_limits: "1Gi"
egov-mdms-service-host-key: "egov-mdms-service"

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: health-transformer
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: TRANSFORMER_CONSUMER_BULK_CREATE_PROJECT_TASK_TOPIC
    value: "save-project-task-health-topic"
  - name: TRANSFORMER_CONSUMER_BULK_UPDATE_PROJECT_TASK_TOPIC
    value: "update-project-task-health-topic"
  - name: TRANSFORMER_PRODUCER_BULK_PROJECT_TASK_INDEX_V1_TOPIC
    value: "transformer-producer-bulk-project-task-index-v1-topic"
  
  - name: TRANSFORMER_CONSUMER_BULK_CREATE_PROJECT_STAFF_TOPIC
    value: "save-project-staff-health-topic"
  - name: TRANSFORMER_CONSUMER_BULK_UPDATE_PROJECT_STAFF_TOPIC
    value: "update-project-staff-health-topic"
  - name: TRANSFORMER_PRODUCER_BULK_PROJECT_STAFF_INDEX_V1_TOPIC
    value: "transformer-producer-bulk-project-staff-index-v1-topic"
  
  - name: TRANSFORMER_PRODUCER_BULK_PROJECT_INDEX_V1_TOPIC
    value: "transformer-producer-bulk-project-index-v1-topic"
  
  - name: TRANSFORMER_CONSUMER_CREATE_HOUSEHOLD_TOPIC
    value: "save-household-health-topic"
  - name: TRANSFORMER_CONSUMER_UPDATE_HOUSEHOLD_TOPIC
    value: "update-household-health-topic"
  - name: TRANSFORMER_PRODUCER_BULK_HOUSEHOLD_INDEX_V1_TOPIC
    value: "transformer-producer-amp-household-index-v1-topic"
  
  - name: TRANSFORMER_CONSUMER_CREATE_PROJECT_TOPIC
    value: "save-project-health"

  - name: TRANSFORMER_CONSUMER_UPDATE_PROJECT_TOPIC
    value: "update-project-health"
  - name: EGOV_PROJECT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: health-project
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: EGOV_SEARCH_PROJECT_URL
    value: "/health-project/v1/_search"
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: {{ index .Values "egov-mdms-service-host-key" | quote }}
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/egov-mdms-service/v1/_search"
  - name: PROJECT_MDMS_MODULE
    value: "HCM-PROJECT-TYPES"
  
  - name: EGOV_LOCATION_ENDPOINT
    value: "/egov-location/location/v11/boundarys/_search"
  
  - name: TRANSFORMER_CONSUMER_BULK_CREATE_STOCK_TOPIC
    value: "save-stock-health-topic"
  - name: TRANSFORMER_CONSUMER_BULK_UPDATE_STOCK_TOPIC
    value: "update-stock-health-topic"
  - name: TRANSFORMER_PRODUCER_BULK_STOCK_INDEX_V1_TOPIC
    value: "transformer-producer-bulk-stock-index-v1-topic"
  - name: EGOV_FACILITY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: facility     
  - name: EGOV_SEARCH_FACILITY_URL
    value: "/facility/v1/_search"
  - name: TRANSFORMER_CONSUMER_CREATE_FACILITY_TOPIC
    value: "save-facility-health-topic"
  - name: TRANSFORMER_CONSUMER_UPDATE_FACILITY_TOPIC
    value: "update-facility-health-topic"
  - name: BOUNDARY_LABEL_NAME_PROVINCE
    value: "Provincia"
  - name: BOUNDARY_LABEL_NAME_DISTRICT
    value: "Distrito"
  - name: BOUNDARY_LABEL_NAME_ADMINISTRATIVEPROVINCE
    value: "Posto Administrativo"
  - name: BOUNDARY_LABEL_NAME_LOCALITY
    value: "Localidade"
  - name: BOUNDARY_LABEL_NAME_VILLAGE
    value: "Aldeia"
  - name: EGOV_SERVICEDEFINITION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: service-request
  - name: EGOV_SEARCH_SERVICEDEFINITION_URL
    value: "/service-request/service/definition/v1/_search"
  - name: TRANSFORMER_CONSUMER_CREATE_SERVICE_TOPIC
    value: "save-service"
  - name: TRANSFORMER_PRODUCER_SERVICE_TASK_INDEX_V1_TOPIC
    value: "transformer-producer-service-request-index-v1-topic"
  - name: EGOV_BOUNDARY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: boundary-service
  - name: EGOV_BOUNDARY_SEARCH_URL
    value: "/boundary-service/boundary/_search"
  - name: EGOV_BOUNDARY_RELATIONSHIP_SEARCH_URL
    value: "/boundary-service/boundary-relationships/_search"
  {{- if index .Values "egov-boundary-hierarchy-name" }}
  - name: EGOV_BOUNDARY_HIERARCHY_NAME
    value: {{ index .Values "egov-boundary-hierarchy-name" | quote }}
  {{- else }}
  {{- fail "The value for 'egov-boundary-hierarchy-name' is required." }}
  {{- end }}
  - name: SPRING_REDIS_HOST
    value: redis.backbone
  - name: SPRING_REDIS_PORT
    value: "6379"
  - name: SPRING_CACHE_TYPE
    value: "redis"
  - name: SPRING_CACHE_REDIS_TIME-TO-LIVE
    value: "60"
   - name: SAMPLE_ENV
    value: "test"
