# Common Labels
labels:
  app: "ifix-es-pipeline"
  group: "ifix"

namespace: ifix

# Container Configs
image:
  repository: "ifix-es-pipeline"
replicas: "1"

appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |  
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: "ifix-es-pipeline"
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
  - name: FISCAL_EVENT_KAFKA_PUSH_TOPIC
    value: {{ index .Values "fiscal-event-kafka-push-topic" | quote }}
  - name: FISCAL_EVENT_INDEX_TOPIC
    value: {{ index .Values "fiscal-event-index-topic" | quote }}
  - name: IFIX_DEPARTMENT_ENTITY_SEARCH_ENDPOINT
    value: {{ index .Values "ifix-department-entity-search-endpoint" | quote }}
  - name: COA_MAP
    value: {{ index .Values "coa-map" | quote }}
  - name: IFIX_DEPARTMENT_ENTITY_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: ifix-department-entity-service

  - name: IFIX_MASTER_DATA_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: ifix-master-data-service
  - name: IFIX_MASTER_DATA_SERVICE_SEARCH_ENDPOINT
    value: {{ index .Values "ifix-master-data-service-search-endpoint" | quote }}
