# Common Labels
labels:
  app: "egov-pdf"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "egov-pdf"

# Container Configs
image:
  repository: "egov-pdf"
replicas: "1"

# Additional Container Envs
env: |
  - name: KAFKA_BROKER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_TLSERVICES_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: tl-services
  - name: EGOV_PDF_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: pdf-service
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_SEARCHER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-searcher
  - name: EGOV_PAYMENTS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: collection-services
  - name: EGOV_PTSERVICES_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: property-services   
  - name: EGOV_TRADELICENSESERVICES_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: tl-services 
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2   
  - name: CONTEXT_PATH
    value: "/egov-pdf"  
  - name: EGOV_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
