# Common Labels
labels:
  app: "egov-custom-consumer"
  group: "core"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "egov-custom-consumer"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
erp-host: "https://jalandhar-dev.egovernments.org/"
erp-signout-url: "/services/EGF/rest/ClearToken"

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-api-gateway
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name:  EGOV_COEXISTENCE_HOSTNAME
    value: {{ index .Values "erp-host" | quote }}
  - name:  EGOV_COEXISTENCE_SINGOUT_URI
    value: {{ index .Values "erp-signout-url" | quote }}
  - name: EGOV_CUSTOM_ASYNC_FILTER_TOPIC
    value: res-custom-filter
