# Common Labels
labels:
  app: "sms-adapter"
  group: "works"

namespace: staging

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "sms"

# Container Configs
image:
  repository: "sms-adapter"
replicas: "1"
healthChecks:
  enabled: false
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_V2_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service-v2  
  - name: WORKS_ESTIMATE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: estimate-service
  - name: WORKS_CONTRACT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: contract-service
  - name: EGOV_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: individual
  - name: WORKS_ORGANISATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: organisation
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: WORKS_PROJECT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: project-management-system
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: EGOV_ATTENDANCE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: attendance-service
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: EGOV_HRMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-hrms
  - name: WORKS_EXPENSE_CALCULATOR_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: expense-calculator
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: "sms-adapter-service"
