# Common Labels
labels:
  app: "egov-searcher"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "egov-searcher"

# Init Containers Configs
initContainers:
  gitSync:
    enabled: true
    repo: "git@github.com:egovernments/configs"
    branch: "master"

# Container Configs
image:
  repository: "egov-searcher"
replicas: "1"
appType: "java-spring"
tracing-enabled: true
search-yaml-path: "file:///work-dir/configs/egov-searcher/rainmaker-pgr-v2.yml,file:///work-dir/configs/egov-searcher/weekly-impact-emailer-searcher.yml,file:///work-dir/configs/egov-searcher/PTDemandBasedSearcher.yml,file:///work-dir/configs/egov-searcher/bill-genie.yml,file:///work-dir/configs/egov-searcher/rainmaker-tl.yml,file:///work-dir/configs/egov-searcher/localitySearcher.yml"
heap: "-Xmx192m -Xms192m"

# Additional Container Envs
env: |
  - name: SEARCH_YAML_PATH
    value: {{ index .Values "search-yaml-path" | quote }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false" 
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: state-level-tenant-id
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: internal-gateway
