# Common Labels
labels:
  app: "digit-ui"
  group: "web"

namespace: works    

# Ingress Configs
ingress:
  enabled: true
  context: "digit-ui"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "digit-ui"
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/digit-ui/"
  readinessProbePath: "/digit-ui/"

extraVolumes: |
  - name: js-injection
    configMap:
      name: digit-ui-js-injection

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
