# Common Labels
labels:
  app: "contracts"
  group: "digit-works"

namespace: works

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "contract"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "contracts_schema"
    image:
      repository: "contracts-db"

# Container Configs
image:
  repository: "contracts"

healthChecks:
  enabled: true
  livenessProbePath: "/contract/health"
  readinessProbePath: "/contract/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: SERVER_CONTEXT_PATH
    value: /contract
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /contract
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: WORKS_ESTIMATE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: estimate-service
  - name: EGOV_HRMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-hrms
  - name: EGOV_ATTENDANCE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: attendance-service
  - name: EGOV_ORG_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: organisation
  - name: EGOV_URL_SHORTNER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-url-shortening
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: WORKS_PROJECT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: project-management-system
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: CONTRACT_KAFKA_CREATE_TOPIC
    value: "save-contract"
  - name: CONTRACT_KAFKA_UPDATE_TOPIC
    value: "update-contract"
  - name: KAFKA_TOPICS_NOTIFICATION_SMS
    value: "egov.core.notification.sms"
  {{- if index .Values "contract-default-offset" }}
  - name: CONTRACT_DEFAULT_OFFSET
    value: {{ index .Values "contract-default-offset" | quote }}
  {{- end }}
  {{- if index .Values "contract-default-limit" }}
  - name: CONTRACT_DEFAULT_LIMIT
    value: {{ index .Values "contract-default-limit" | quote }}
  {{- end }}
  {{- if index .Values "contract-search-max-limit" }}
  - name: CONTRACT_SEARCH_MAX_LIMIT
    value: {{ index .Values "contract-search-max-limit" | quote }}
  {{- end }}
  {{- if index .Values "works-contract-service-code" }}
  - name: WORKS_CONTRACT_SERVICE_CODE
    value: {{ index .Values "works-contract-service-code" | quote }}
  {{- end }}
  {{- if index .Values "contract-workflow-business-service" }}
  - name: CONTRACT_WORKFLOW_BUSINESS_SERVICE
    value: {{ index .Values "contract-workflow-business-service" | quote }}
  {{- end }}
  {{- if index .Values "contract-workflow-module-name" }}
  - name: CONTRACT_WORKFLOW_MODULE_NAME
    value: {{ index .Values "contract-workflow-module-name" | quote }}
  {{- end }}
  {{- if index .Values "contract-cbo-url-host" }}
  - name: CONTRACT_CBO_URL_HOST
    value: {{ index .Values "contract-cbo-url-host" | quote }}
  {{- end }}
  {{- if index .Values "contract-cbo-url-endpoint" }}
  - name: CONTRACT_CBO_URL_ENDPOINT
    value: {{ index .Values "contract-cbo-url-endpoint" | quote }}
  {{- end }}