# Common Labels
labels:
  app: "digit-ui-flutter"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "digit-ui-flutter"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "digit-ui-flutter"
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/digit-ui-flutter/health"
  readinessProbePath: "/digit-ui-flutter/health"

namespace: egov
extraVolumes: |
  - name: js-injection
    configMap:
      name: digit-ui-flutter-js-injection
extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
