# Common Labels
labels:
  app: "nlp-engine"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "nlp-engine"

# Container Configs
image:
  repository: "nlp-engine"
replicas: "1"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
memory_limits: 512Mi
# Additional Container Envs
env: |
  - name: DEFAULT_LOCALISATION_TENANT
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service