# Common Labels
labels:
  app: "health-mdms-v1"
  group: "core"

namespace: health

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "egov-mdms-service-legacy"

# Init Containers Configs
initContainers:
  gitSync:
    enabled: true
    repo: "git@github.com:egovernments/egov-mdms-data"
    branch: "master"

# Container Configs
image:
  repository: "health-mdms-v1"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/egov-mdms-service-legacy/health"
  readinessProbePath: "/egov-mdms-service-legacy/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: "-Dspring.profiles.active=monitoring"
mdms-path: "/work-dir/egov-mdms-data/data"
mdms-git-url: ""
mdms-folder: "egov-mdms-data"
masters-config-url: "file:///work-dir/egov-mdms-data/master-config.json"
branch: "master"

# Additional Container Envs
env: |
  - name: SERVER_CONTEXT_PATH
    value: /egov-mdms-service-legacy
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: /egov-mdms-service-legacy
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-mdms-service-consumer-group
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  {{- if index .Values "global" "serializers-timezone-in-ist" }}
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
  {{- end }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: EGOV_MDMS_CONF_PATH
    value: {{ index .Values "mdms-path" | quote }}
  - name: EGOV_MDMS_GIT_URL
    value: {{ index .Values "mdms-git-url" | quote }}
  - name: EGOV_MDMS_FOLDER
    value: {{ index .Values "mdms-folder" | quote }}
  - name: MASTERS_CONFIG_URL
    value: {{ index .Values "masters-config-url" | quote }}
  {{- if index .Values "branch" }}
  - name: BRANCH
    value: {{ index .Values "branch" | quote }}
  {{- end }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"           
