secrets:
    db:
        username: digitdevuser
        password: test1234
        flywayUsername: digitdevuser
        flywayPassword: test1234
    egov-filestore:
        awskey: nsbufjbasnvvnkjd
        awssecretkey: bxjcsncajsb
    user:
        username: admin
        password: eGov@123
    egov-enc-service:
        master_password: demo
        master_salt: q7.fr.cr
        master_initialvector: 9J&asfgrU-H2
    egov-notification-sms:
        username: demo
        password: demo
    egov-pg-service:
        axis_merchant_accesscode: demo
        axis_merchant_id: demo
        axis_merchant_pwd: demo
        axis_merchant_secretkey: demo
        axis_merchant_user: demo
        payu_merchant_key: demo
        payu_merchant_salt: demo
    egov-notification-mail:
        mailsenderusername: demo@demo
        mailsenderpassword: demo
    egov-location:
        gmapskey: jbsdbvxmbsmnx
    kafka:
        clusterID: HshRPdVrWoB4kuTdEbawtq
    elasticsearch:
        password: 8fwbD6HbJh6HU0oddsHm8TEI
    oauth2-proxy:
        cookieSecret: qwgethjymnbv
        clientSecret: 3a08079easd9d8055470475696fd3baad5292
        clientID: QVbnq0L8npoyfxZs96wtBg==
    git-sync:
        ssh: |-
            -----BEGIN RSA PRIVATE KEY-----
            MIIEpQIBAAKCAQEAs9uGzlbpzCqUJAI5I+iGvtU8GOq1VhbXfjrs11biGkOXxDKW
            odczbwVHvpolCnGe85MDWC8vfNAdzGfrZ9UW9Wnenor5wgNd3vF+lheH9IxXHAJ1
            ngYF8ivS9iToB8kJ98LTD9o7N1cwMh1956N+P0Zfi3rA8GMiLf88B6umUQIR68Ek
            8hufC983iCyDVXMXkvkfV0smYCZPRqsM7rguBA9m0AXBUnk9I/QZEpg48SqTYF+t
            2J1MjUNIbHVPCzvjtsMbbSwuHiS8Eh7oEIrP25jk96C9KTYawZu/KwNuazw7tH/2
            DKXA6+UfpwnF1IpW6OdE8ZJyfJBNqi1Qq1VZ8QIDAQABAoIBAGBKpLat44gSN7O7
            mPn3kMR0hzNT3XfUzNRhGdIESxMCoytAZlMJUxkaO5n5DuGziQUg7UZ2JLdu+LUp
            4ed6N0t2veAlyaesg8JLipkyyfAMfsqZKn1K/j30ZoKvqaYZZQPHw5YWIWP0gvIh
            xfmRF5MqyxZyxv8sI+16W5pDtMxjJuD1GeOL4WauJBUiA/a0HsNsBgKwbr7BCOP5
            E6VHWDBmxgkJ6eiIaxLDdSe5Xa9afUgSaIP9qBy2IC3pYuBtq+zThRH2KNbwRH2i
            i48aXsFTybgkn6UGyvEqi/uNWEFHCUzRJ+yuEibirhQpkzO0tJPEm8csD4zvU5xc
            HdKmxc0CgYEA8in2Rpz6mvXySr4eh2oLELrfg9Xlxb07JFqzh9S6scQFzVR0sGIk
            D7MGStk6lLyBlYxxyQ6hcalg8xx13BblKp2oCBeXsfTSFF0nQhfWmRIdL5WZJd0K
            Q1PE+gFJqrjnFs+Cwcmsux2EGf1VeHu0eCohqUDOwCq3qJDdEyuq2isCgYEAviI7
            rOV6SOQ8GOKc3SV9iigCTsRDEVzEi2B1GqIuIBgmVB6bVuuSwKlYny1cHRGHI9nt
            0QN2LJq3coENk3AxtuI6acpHvtyyq1dSL1EY6p/vXAUrRyx8+ZUngh4yAaLp6IyS
            LcbK1PzqQXLedOW7Z6dsQWq1PrKZ9a/ob8N42lMCgYEA0VzeAuas81Q3ic8c7c4M
            iwZFP+GpqW+UtjWEiaatUgs7SO3/hI8Uxk3s3sE4GGdxUS3/Ieh4Q6BApW6xpvpU
            Xqe3ImfjSoNzLQ/sZQPfEK/Mc9tOcKHNwa+m2M5MNkFt6Ra24XvOzmcSUrXnMycg
            O9ORDpdtKE7GQgIcX/qc18kCgYEAo3UexJdMN9ovaF156g1PDjUzNrA30HdmaUR1
            qH4BFYpteSgO9/zyXzu3erEuXbcx7Tpv358QO2yPhZs5JqXvt4BqI4TJhWaLHA6o
            ExGvUBZLW1r+R+QRVShLnOuEpi9+1HP1P/GFcvI0Giw831aZdJVU1jB8vPgisDuY
            omz0Ow0CgYEAkLwbQX2AUBPbt7ShaIpnwje1Bxt5hpnWjcHpI9U8BVK4oGYdue8H
            JLXMT9bJ08knYXkMqPvdctR4oo3QOv0gDcs4NNdOejLbLezRn4m5QYk4Py8j//0m
            qHogo7u2hkiseVLuU91516Da+ALEMkOryGNT+RHbvpAAiYF2734WJRc=
            -----END RSA PRIVATE KEY-----
        known_hosts: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=

