# Common Labels
labels:
  app: "egov-workflow-v2"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "egov-workflow-v2"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_workflow_v2_schema"
    image:
      repository: "egov-workflow-v2-db"

# Container Configs
image:
  repository: "egov-workflow-v2"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/egov-workflow-v2/health"
  readinessProbePath: "/egov-workflow-v2/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx64m -Xms64m"
java-args: "-Dspring.profiles.active=monitoring"
workflow-statelevel: "true"

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-tl-services
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: PERSISTER_SAVE_WF_TOPIC
    value: save-wf-transitions
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_STATELEVEL_TENANTID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/egov-mdms-service/v1/_search"
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_USER_SEARCH_ENDPOINT
    value: "/user/v1/_search"                            
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SERVER_PORT
    value: "8080"
  {{- if index .Values "java-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-debug" | quote }}
  {{- else }}
  - name: JAVA_ENABLE_DEBUG
    value: "false"
  {{- end }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"       
  - name: EGOV_WF_DEFAULT_LIMIT
    value: "100"
  - name: EGOV_WF_STATELEVEL
    value: {{ index .Values "workflow-statelevel" | quote }}
  {{- if index .Values "wf-max-limit" }}   
  - name: EGOV_WF_MAX_LIMIT     
    value: {{ index .Values "wf-max-limit" | quote }}   
  {{- end }}  
