# Common Labels
labels:
  app: "sunbirdrc-credential-service"
  group: "accelerator"

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "sunbirdrc-credential-service"

initContainers:
  dbMigration:
    enabled: true
    schemaTable: "sunbirdrc_credential_service_schema"
    image:
      repository: "sunbirdrc-credential-service-db"

image:
  repository: "sunbirdrc-credential-service"
replicas: "1"
healthChecks:
  enabled: false
  livenessProbePath: "/sunbirdrc-credential-service/health"
  readinessProbePath: "/sunbirdrc-credential-service/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx512m -Xms512m"
java-args: "-Dspring.profiles.active=monitoring"

env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SUNBIRD_CREDENTIAL_PATH
    value: /credentials/issue
  - name: SUNBIRD_CREDENTIAL_SCHEMA_PATH
    value: /credential-schema
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: mdms-service-v2
  - name: SUNBIRD_CREDENTIAL_SCHEMA_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: sunbird-credential-schema
  - name: SUNBIRD_CREDENTIAL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: sunbird-credential-service
      