namespace : sanitation
# Common Labels
labels:
  app: "pqm-service"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "pqm-service"
  namespace : egov

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "pqm_services_schema"
    image:
      repository: "pqm-service-db"

# Container Configs
image:
  repository: "pqm-service"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/pqm-service/health"
  readinessProbePath: "/pqm-service/health"
appType: "java-spring"
tracing-enabled: true
memory_limits: 512Mi
heap: "-Xmx384m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"
#egov.idgen.pqm.applicationNum.format: "[CITY.CODE]-FSM-[cy:yyyy-MM-dd]-[SEQ_EGOV_FSM]"

# Additional Container Envs
env: |
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_V2_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key:  mdms-service-v2
  - name: EGOV_URL_SHORTNER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-url-shortening
  - name: EGOV_PDF_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: pdf-service
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_UI_APP_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: WORKFLOW_CONTEXT_PATH
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: WORKFLOW_TRANSITION_PATH
    value: "egov-workflow-v2/egov-wf/process/_transition"
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-pqm-service
  - name: PERSISTER_SAVE_FSM_TOPIC
    value: save-pqm-application
  - name: PERSISTER_UPDATE_FSM_TOPIC
    value: update-pqm-application
  - name: PERSISTER_UPDATE_FSM_WORKFLOW_TOPIC
    value: update-pqm-workflow-application
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  {{- if index .Values "java-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-debug" | quote }}
  {{- else }}
  - name: JAVA_ENABLE_DEBUG
    value: "false"
  {{- end }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
