# Common Labels
labels:
  app: "works-management-service"
  group: "digit-works"

namespace: works

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "wms"

initContainers:
  dbMigration:
    enabled: true
    schemaTable: "wms_schema"
    image:
      repository: "works-management-service-db"

# Container Configs
image:
  repository: "works-management-service"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/wms/health"
  readinessProbePath: "/wms/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
memory_limits: 512Mi
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_CONTEXT_PATH
    value: /wms
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /wms
  {{- if index .Values "java-enable-debug" }}
  - name: SPRING_REDIS_HOST
    value: redis.backbone
  - name: SPRING_REDIS_PORT
    value: "6379"
  {{- end }} 
  - name: WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: WORKFLOW_PROCESS_SEARCH_PATH
    value: "egov-workflow-v2/egov-wf/process/_search"
  - name: WORKFLOW_BUSINESSSERVICE_SEARCH_PATH
    value: "egov-workflow-v2/egov-wf/businessservice/_search"
  - name: WORKFLOW_PROCESS_COUNT_PATH
    value: "egov-workflow-v2/egov-wf/process/_count"
  - name: WORKFLOW_PROCESS_STATUSCOUNT_PATH
    value: "egov-workflow-v2/egov-wf/process/_statuscount"   
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service-v2 
  - name: SERVICES_ESINDEXER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: es-indexer-host
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: PARENT_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: EGOV_ES_USERNAME
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: username
  - name: EGOV_ES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: password
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  {{- if index .Values "egov-idgen-report-id-name" }}
  - name: EGOV_IDGEN_REPORT_ID_NAME
    value: {{ index .Values "egov-idgen-report-id-name" | quote }} 
  {{- end }}
  {{- if index .Values "wms-kafka-report-create-topic" }}
  - name: WMS_KAFKA_REPORT_CREATE_TOPIC
    value: {{ index .Values "wms-kafka-report-create-topic" | quote }} 
  {{- end }}
  {{- if index .Values "wms-kafka-report-update-topic" }}
  - name: WMS_KAFKA_REPORT_UPDATE_TOPIC
    value: {{ index .Values "wms-kafka-report-update-topic" | quote }} 
  {{- end }}
  - name: EGOV_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  {{- if index .Values "report-search-pagination-default-limit" }}
  - name: REPORT_SEARCH_PAGINATION_DEFAULT_LIMIT
    value: {{ index .Values "report-search-pagination-default-limit" | quote }} 
  {{- end }}
  {{- if index .Values "report-search-pagination-default-offset" }}
  - name: REPORT_SEARCH_PAGINATION_DEFAULT_OFFSET
    value: {{ index .Values "report-search-pagination-default-offset" | quote }} 
  {{- end }}
  - name: SPRING_DATA_REDIS_HOST
    value: redis.backbone
  - name: SPRING_DATA_REDIS_PORT
    value: "6379"
  {{- if index .Values "wms-payment-tracker-module" }}
  - name: WMS_PAYMENT_TRACKER_MODULE
    value: {{ index .Values "wms-payment-tracker-module" | quote }} 
  {{- end }}
  {{- if index .Values "wms-estimate-module" }}
  - name: WMS_ESTIMATE_MODULE
    value: {{ index .Values "wms-estimate-module" | quote }} 
  {{- end }}
  
  
