# Common Labels
labels:
  app: "egov-enc-service"
  group: "core"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_enc_service_schema"
    image:
      repository: "egovio/egov-enc-service-db"

# Container Configs
image:
  repository: "egovio/egov-enc-service"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/egov-enc-service/health"
  readinessProbePath: "/egov-enc-service/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"
state-level-tenant-id: "pb"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_STATE_LEVEL_TENANT_ID
    value: {{ index .Values "state-level-tenant-id" | quote }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"         
  - name: SERVER_CONTEXT_PATH
    value: /egov-enc-service    
  - name: MASTER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: egov-enc-service
        key: master.password    
  - name: MASTER_SALT
    valueFrom:
      secretKeyRef:
        name: egov-enc-service
        key: master.salt
  - name: MASTER_INITIALVECTOR
    valueFrom:
      secretKeyRef:
        name: egov-enc-service
        key: master.initialvector                                                       

