# Default values for kuberhealthy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: monitoring

checks_namespace: mgramseva

prometheus:
  enabled: true
  name: "prometheus"
  enableScraping: false
  serviceMonitor: true
  enableAlerting: false

image:
  repository: quay.io/comcast/kuberhealthy
  tag: 2.1.0

resources:
  requests:
    cpu: 400m
    memory: 300Mi
  limits:
    cpu: 1
    memory: 1G1

tolerations:
  # change to true to tolerate and deploy to masters
  master: false

deployment:
  replicas: 1
  maxSurge: 0
  maxUnavailable: 1
  imagePullPolicy: IfNotPresent
  nodeSelector: {}
  podAnnotations: {}
  env: {}
  command:
  - /app/kuberhealthy
  # args:

securityContext:
  runAsNonRoot: true
  runAsUser: 999
  allowPrivilegeEscalation: false

# Please remember that changing the service type to LoadBalancer
# will expose Kuberhealthy to the internet, which could cause
# error messages shown by Kuberhealthy to be exposed to the
# public internet.  It is recommended to create the service
# with ClusterIP, then to manually edit the service in order to
# securely expose the port in an appropriate way for your
# specific environment.
service:
  externalPort: 80
  type: ClusterIP
  annotations: {}

check:
  daemonset:
    enabled: true
    image:
      repository: quay.io/comcast/kh-daemonset-check
      tag: 2.0.1
    extraEnvs:
    nodeSelector: {}
  deployment:
    enabled: true
    image:
      repository: quay.io/comcast/deployment-check
      tag: 1.1.1
    extraEnvs:
      CHECK_DEPLOYMENT_REPLICAS: "2"
      CHECK_DEPLOYMENT_ROLLING_UPDATE: "true"
    nodeSelector: {}
  dnsInternal:
    enabled: true
    image:
      repository: quay.io/comcast/dns-status-check
      tag: 1.0.0
    extraEnvs:
      HOSTNAME: "kubernetes.default"
    nodeSelector: {}
  egov:
    image:
      repository: egovio/kuberhealthy-checks
      tag: "1-master-ac7c528"
  essync:
    enabled: true
  db:
    enabled: true
    env: |
      - name: PG_USER
        valueFrom:
          secretKeyRef:
            name: db
            key: username
      - name: PG_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db
            key: password
      - name: PG_HOST
        valueFrom:
          configMapKeyRef:
            name: egov-config
            key: db-host
      - name: PG_DBNAME
        valueFrom:
          configMapKeyRef:
            name: egov-config
            key: db-name
  kafka:
    enabled: true
    env: |
        - name: BOOTSTRAP_SERVER
          valueFrom:
          configMapKeyRef:
            name: egov-config
            key: kafka-brokers

  podRestarts:
    enabled: false
    image:
      repository: quay.io/comcast/pod-restarts-check
      tag: 2.0.0
    extraEnvs:
      MAX_FAILURES_ALLOWED: "10"
    nodeSelector: {}
  podStatus:
    enabled: false
    image:
      repository: quay.io/comcast/pod-status-check
      tag: 1.0.1
    extraEnvs:
    nodeSelector: {}

checkReaper:
  image:
    repository: quay.io/comcast/check-reaper
    tag: 1.0.0
  nodeSelector: {}
