# Common Labels
labels:
  app: "rate-analysis"
  group: "digit-works"

namespace: works

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "rate-analysis"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "rate_analysis_schema"
    image:
      repository: "rate-analysis-db"

# Container Configs
image:
  repository: "rate-analysis"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/rate-analysis/health"
  readinessProbePath: "/rate-analysis/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
memory_limits: 512Mi
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: SERVER_CONTEXT_PATH
    value: /rate-analysis
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /rate-analysis
  
  - name: EGOV_MDMS_V2_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service-v2
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  {{- if index .Values "labour-cess-head-code" }}
  - name: LABOUR_CESS_HEAD_CODE
    value: {{ index .Values "labour-cess-head-code" | quote }}
  {{- end }}
  {{- if index .Values "labour-cess-rate" }}
  - name: LABOUR_CESS_RATE
    value: {{ index .Values "labour-cess-rate" | quote }}
  {{- end }}
  {{- if index .Values "works-sor-type" }}
  - name: WORKS_SOR_TYPE
    value: {{ index .Values "works-sor-type" | quote }}
  {{- end }}
  - name: SPRING_DATA_REDIS_HOST
    value: redis.backbone
  - name: SPRING_DATA_REDIS_PORT
    value: "6379"
  {{- if index .Values "rate-analysis-job-create-topic"}}
  - name: RATE_ANALYSIS_JOB_CREATE_TOPIC
    value: {{ index .Values "rate-analysis-job-create-topic" | quote }}
  {{- end }}
  {{- if index .Values "rate-analysis-job-update-topic"}}
  - name: RATE_ANALYSIS_JOB_UPDATE_TOPIC
    value: {{ index .Values "rate-analysis-job-update-topic" | quote }}
  {{- end }}
  {{- if index .Values "egov-mdms-data-save-topic" }}
  - name: EGOV_MDMS_DATA_SAVE_TOPIC
    value: {{ index .Values "egov-mdms-data-save-topic" | quote }}
  {{- end }}
  {{- if index .Values "works-mdms-data-rates-schema-code" }}
  - name: WORKS_MDMS_DATA_RATES_SCHEMA_CODE
    value: {{ index .Values "works-mdms-data-rates-schema-code" | quote }}
  {{- end }}
  {{- if index .Values "works-mdms-data-composition-schema-code" }}
  - name: WORKS_MDMS_DATA_COMPOSITION_SCHEMA_CODE
    value: {{ index .Values "works-mdms-data-composition-schema-code" | quote }}
  {{- end }}

