# Common Labels
labels:
  app: "muster-roll-service"
  group: "digit-works"

namespace: works

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "muster-roll"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "muster_roll_service_schema"
    image:
      repository: "muster-roll-service-db"

# Container Configs
image:
  repository: "muster-roll-service"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/muster-roll/health"
  readinessProbePath: "/muster-roll/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: SERVER_CONTEXT_PATH
    value: /muster-roll
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /muster-roll 
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: WORKS_ATTENDANCE_LOG_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: attendance-service
  - name: APP_TIMEZONE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: timezone
  - name: MUSTERROLL_KAFKA_CREATE_TOPIC
    value: "save-musterroll"
  - name: MUSTERROLL_KAFKA_UPDATE_TOPIC
    value: "update-musterroll"
  {{- if index .Values "musterroll-default-offset" }}
  - name: MUSTERROLL_DEFAULT_OFFSET
    value: {{ index .Values "musterroll-default-offset" | quote }}
  {{- end }}
  {{- if index .Values "musterroll-default-limit" }}
  - name: MUSTERROLL_DEFAULT_LIMIT
    value: {{ index .Values "musterroll-default-limit" | quote }}
  {{- end }}
  {{- if index .Values "musterroll-search-max-limit" }}
  - name: MUSTERROLL_SEARCH_MAX_LIMIT
    value: {{ index .Values "musterroll-search-max-limit" | quote }}
  {{- end }}
  {{- if index .Values "musterroll-workflow-business-service" }}
  - name: MUSTERROLL_WORKFLOW_BUSINESS_SERVICE
    value: {{ index .Values "musterroll-workflow-business-service" | quote }}
  {{- end }}
  {{- if index .Values "works-attendance-log-search-endpoint" }}
  - name: WORKS_ATTENDANCE_LOG_SEARCH_ENDPOINT
    value: {{ index .Values "works-attendance-log-search-endpoint" | quote }}
  {{- end }}

  
