# Common Labels
labels:
  app: "hcm-moz-impl"
  group: "core"

namespace: health

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "hcm-moz-impl"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "moz_health_schema"
    image:
      repository: "moz-health-db"

# Container Configs
image:
  repository: "hcm-moz-impl"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/hcm-moz-impl/health"
  readinessProbePath: "/hcm-moz-impl/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""
java-enable-debug: true
persist-yml-path: "file:///work-dir/configs/health/egov-persister/hcm-moz-impl-persister.yml"
startDate: "28/08/2023"
endDate: "02/09/2023"

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: hcm-moz-impl
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_HRMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-hrms
  - name: EGOV_LOCALISATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_IDGEN_PATH
    value: "egov-idgen/id/_generate"
  - name: EGOV_IDGEN_INTEGRATION_ENABLED
    value: "true"
  - name: SPRING_REDIS_HOST
    value: redis.backbone
  - name: SPRING_REDIS_PORT
    value: "6379"
  - name: SPRING_CACHE_TYPE
    value: "redis"
  - name: SPRING_CACHE_REDIS_TIME-TO-LIVE
    value: "60"
  - name: SPRING_CACHE_AUTOEXPIRY
    value: "true"
  - name: DHIS2_RECORD_KAFKA_CREATE_TOPIC
    value: create-dhis2-record
  - name: DHIS2_RECORD_KAFKA_UPDATE_TOPIC
    value: update-dhis2-record
  - name: DHIS2_DIGIT_MAPPING_KAFKA_CREATE_TOPIC
    value: create-dhis2-digit-mapping
  - name: DHIS2_DIGIT_MAPPING_KAFKA_UPDATE_TOPIC
    value: update-dhis2-digit-mapping
  - name: BOUNDARY_DATA_KAFKA_CREATE_TOPIC
    value: create-boundary-data
  - name: DHIS2_RECORD_DEFAULT_OFFSET
    value: "0"
  - name: DHIS2_RECORD_DEFAULT_LIMIT
    value: "10"
  - name: DHIS2_RECORD_SEARCH_MAX_LIMIT
    value: "50"
  - name: DHIS2_JOB_KAFKA_CREATE_TOPIC
    value: create-dhis2-job
  - name: DHIS2_JOB_KAFKA_UPDATE_TOPIC
    value: update-dhis2-job
  - name: DHIS2_JOB_DEFAULT_OFFSET
    value: "0"
  - name: DHIS2_JOB_DEFAULT_LIMIT
    value: "10"
  - name: DHIS2_JOB_SEARCH_MAX_LIMIT
    value: "50"
  - name: DHIS2_DIGIT_SEARCH_MAX_RETRY
    value: "100"
  - name: EGOV_DHIS2_HOST_URL
    valueFrom:
      configMapKeyRef:
        name: hcm-moz-impl
        key: dhis2-host
  - name: EGOV_DHIS2_HOST_USERNAME
    valueFrom:
      secretKeyRef:
        name: hcm-moz-impl
        key: dhis2user
  - name: EGOV_DHIS2_HOST_PASSWORD
    valueFrom:
      secretKeyRef:
        name: hcm-moz-impl
        key: dhis2pass
  - name: EGOV_DHIS2_PAGE_SIZE
    value: "1000"
  - name: EGOV_DIGIT_PAGE_SIZE
    value: "30"
  - name: EGOV_CAMPAIGN_STARTDATE
    value: {{ index .Values "startDate" | quote }}
  - name: EGOV_CAMPAIGN_ENDDATE
    value: {{ index .Values "endDate" | quote }}
  - name: EGOV_DIGIT_WAIT_TIMEOUT
    value: "15"
  - name: EGOV_KAFKA_PAGE_SIZE
    value: "100"
  - name: EGOV_DHIS2_USERS_ENDPOINT
    value: /api/users
  - name: EGOV_DHIS2_USERS_FIELDS
    value: id,name,displayName,surname,firstName,userCredentials%5Busername%5D,organisationUnits,userGroups,username
  - name: EGOV_DHIS2_ROLES_ENDPOINT
    value: /api/userRoles
  - name: EGOV_DHIS2_ROLES_FIELDS
    value: :all
  - name: EGOV_DHIS2_USER_GROUPS_ENDPOINT
    value: /api/userGroups
  - name: EGOV_DHIS2_USER_GROUPS_FIELDS
    value: :all
  - name: EGOV_DHIS2_PROGRAMS_ENDPOINT
    value: /api/programs
  - name: EGOV_DHIS2_EVENTS_ENDPOINT
    value: /api/tracker/events
  - name: EGOV_DHIS2_ORGANISATION_UNIT_ENDPOINT
    value: /api/organisationUnits
  - name: EGOV_DHIS2_ORGANISATION_UNIT_FIELDS
    value: id,name,parent,path,level,children
  - name: EGOV_DHIS2_ORGANISATION_UNIT_LEVEL_ENDPOINT
    value: /api/organisationUnitLevels
  - name: EGOV_DHIS2_ORGANISATION_UNIT_LEVEL_FIELDS
    value: id,name,level
  - name: EGOV_DHIS2_DATA_ELEMENT_ENDPOINT
    value: /api/dataElements
  - name: EGOV_DHIS2_DATA_ELEMENT_FIELDS
    value: id,name,code
  - name: EGOV_DHIS2_ORGANISATION_UNIT_LEVEL_ENDPOINT
    value: /api/organisationUnitLevels
  - name: EGOV_DHIS2_ORGANISATION_UNIT_LEVEL_FIELDS
    value: id,name,level
  - name: THREAD_CORE_POOL_SIZE
    value: "20"
  - name: THREAD_MAX_POOL_SIZE
    value: "200"
  - name: EGOV_DIGIT_HOST_AUTH_KEY
    value: ZWdvdi11c2VyLWNsaWVudDo=
  - name: EGOV_DIGIT_HOST_USERNAME
    value: khushali
  - name: EGOV_DIGIT_HOST_PASSWORD
    value: eGov@4321
  - name: EGOV_DIGIT_HOST_URL
    valueFrom:
        configMapKeyRef:
          name: egov-config
          key: egov-services-fqdn-name
  - name: FILE_STORE_SERVICE_END_POINT
    value: filestore/v1/files/url        
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-enable-debug" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: EGOV_DHIS2_ORGANISATION_UNIT_PROVINCES
    value: "SOFALA,NAMPULA"
  - name: EGOV_PROJECT_TYPE_ID
    value: dbd45c31-de9e-4e62-a9b6-abb818928fd1
  - name: EGOV_PROJECT_TYPE
    value: LLIN-Default
  - name: EGOV_FACILITY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: facility
  - name: EGOV_FACILITY_SEARCH_PATH
    value: /facility/v1/_search
  - name: EGOV_FACILITY_CREATE_PATH
    value: /facility/v1/bulk/_create
  - name: EGOV_FACILITY_UPDATE_PATH
    value: /facility/v1/bulk/_update
  - name: EGOV_PROJECT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: project
  - name: EGOV_PROJECT_SEARCH_PATH
    value: /project/v1/_search
  - name: EGOV_PROJECT_CREATE_PATH
    value: /project/v1/_create
  - name: EGOV_PROJECT_UPDATE_PATH
    value: /project/v1/_update
  - name: EGOV_PROJECT_STAFF_SEARCH_PATH
    value: /project/staff/v1/_search
  - name: EGOV_PROJECT_STAFF_CREATE_PATH
    value: /project/staff/v1/_create
  - name: EGOV_PROJECT_STAFF_UPDATE_PATH
    value: /project/staff/v1/_update
  - name: EGOV_PROJECT_FACILITY_SEARCH_PATH
    value: /project/facility/v1/_search
  - name: EGOV_PROJECT_FACILITY_CREATE_PATH
    value: /project/facility/v1/bulk/_create
  - name: EGOV_PROJECT_FACILITY_UPDATE_PATH
    value: /project/facility/v1/bulk/_update
  - name: EGOV_PROJECT_BENEFICIARY_SEARCH_PATH
    value: /project/beneficiary/v1/_search
  - name: EGOV_PROJECT_BENEFICIARY_CREATE_PATH
    value: /project/beneficiary/v1/bulk/_create
  - name: EGOV_PROJECT_BENEFICIARY_UPDATE_PATH
    value: /project/beneficiary/v1/bulk/_update
  - name: EGOV_PROJECT_TASK_SEARCH_PATH
    value: /project/task/v1/_search
  - name: EGOV_PROJECT_TASK_CREATE_PATH
    value: /project/task/v1/bulk/_create
  - name: EGOV_PROJECT_TASK_UPDATE_PATH
    value: /project/task/v1/bulk/_update
  - name: EGOV_PROJECT_RESOURCE_SEARCH_PATH
    value: /project/resource/v1/_search
  - name: EGOV_PROJECT_RESOURCE_CREATE_PATH
    value: /project/resource/v1/bulk/_create
  - name: EGOV_PROJECT_RESOURCE_UPDATE_PATH
    value: /project/resource/v1/bulk/_update
  - name: EGOV_SERVICE_REQUEST_PROJECTCODE
    value: LLINMozambique2
  - name: EGOV_HOUSEHOLD_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: household
  - name: EGOV_HOUSEHOLD_SEARCH_PATH
    value: /household/v1/_search
    value: /household/v1/_search
  - name: EGOV_HOUSEHOLD_CREATE_PATH
    value: /household/v1/bulk/_create
  - name: EGOV_HOUSEHOLD_UPDATE_PATH
    value: /household/v1/bulk/_update
  - name: EGOV_HOUSEHOLD_MEMBER_SEARCH_PATH
    value: /household/member/v1/_search
  - name: EGOV_HOUSEHOLD_MEMBER_CREATE_PATH
    value: /household/member/v1/bulk/_create
  - name: EGOV_HOUSEHOLD_MEMBER_UPDATE_PATH
    value: /household/member/v1/bulk/_update
  - name: EGOV_HCM_HOUSEHOLD_INDIVIDUAL_UPDATE_TOPIC
    value: update-individual-topic
  - name: EGOV_HCM_PROJECT_TASK_UPDATE_TOPIC
    value: update-project-task-topic
  - name: EGOV_HCM_PROJECT_TASK_CREATE_TOPIC
    value: save-project-task-topic
  - name: EGOV_HCM_PROJECT_BENEFICIARY_UPDATE_TOPIC
    value: update-project-beneficiary-topic
  - name: EGOV_HCM_PROJECT_BENEFICIARY_CREATE_TOPIC
    value: save-project-beneficiary-topic
  - name: EGOV_HCM_HOUSEHOLD_MEMBER_UPDATE_TOPIC
    value: update-household-member-topic
  - name: EGOV_HCM_HOUSEHOLD_MEMBER_CREATE_TOPIC
    value: save-household-member-topic
  - name: EGOV_HCM_HOUSEHOLD_UPDATE_TOPIC
    value: update-household-topic
  - name: EGOV_HCM_HOUSEHOLD_CREATE_TOPIC
    value: save-household-topic
  - name: EGOV_HCM_INDIVIDUAL_UPDATE_TOPIC
    value: update-individual-topic
  - name: EGOV_HCM_INDIVIDUAL_CREATE_TOPIC
    value: save-individual-topic
  - name: EGOV_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: individual
  - name: EGOV_INDIVIDUAL_SEARCH_PATH
    value: /individual/v1/_search
  - name: EGOV_INDIVIDUAL_CREATE_PATH
    value: /individual/v1/bulk/_create
  - name: EGOV_INDIVIDUAL_UPDATE_PATH
    value: /individual/v1/bulk/_update
  - name: EGOV_STOCK_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: stock
  - name: EGOV_SERVICE_REQUEST_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: service-request
  - name: EGOV_STOCK_SEARCH_PATH
    value: /stock/v1/_search
  - name: EGOV_STOCK_CREATE_PATH
    value: /stock/v1/bulk/_create
  - name: EGOV_STOCK_UPDATE_PATH
    value: /stock/v1/bulk/_update
  - name: EGOV_BOUNDARY_NAME
    value: MOZAMBIQUE
  - name: EGOV_BOUNDARY_CODE
    value: mz
  - name: EGOV_MDMS_CREATE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-create
  - name: EGOV_MDMS_CREATE_UPDATE_ENDPOINT
    value: /egov-mdms-create/v1/_update
  - name: EGOV_HRMS_CREATE_ENDPOINT
    value: /egov-hrms/employees/_create
  - name: EGOV_HRMS_UPDATE_ENDPOINT
    value: /egov-hrms/employees/_update
  - name: EGOV_HRMS_SEARCH_ENDPOINT
    value: /egov-hrms/employees/_search
  - name: EGOV_BOUNDARY_ROOT_LABEL
    value: Country
  - name: EGOV_BOUNDARY_MASTER_NAME
    value: TenantBoundary
  - name: EGOV_BOUNDARY_MODULE_NAME
    value: egov-location
  - name: EGOV_BOUNDARY_HIERARCHY_CODE
    value: ADMIN
  - name: EGOV_BOUNDARY_HIERARCHY_NAME
    value: ADMIN
  - name: EGOV_PRODUCT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: product
  - name: EGOV_KUBE_CONFIG
    valueFrom:
      secretKeyRef:
        name: hcm-moz-impl
        key: kubeconfig
  - name: EGOV_KUBE_NAMESPACE
    value: egov
  - name: EGOV_KUBE_MDMS_POD
    value: egov-mdms-service
  - name: EGOV_KUBE_IS_CLUSTER
    value: "true"
  - name: EGOV_KUBE_CLUSTER_NAME
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: aws-cluster-name
  - name: EGOV_AWS_REGION
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: aws-region
  - name: EGOV_AWS_CREDENTIALS_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: egov-filestore
        key: awskey
  - name: EGOV_AWS_CREDENTIALS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: egov-filestore
        key: awssecretkey
  - name: EGOV_CLUSTER_ENDPOINT_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: aws-cluster-ip
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  