# Common Labels
labels:
  app: "pgr-services"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  namespace: "upyog"
  context: "pgr-services"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "pgr_services_schema"
    image:
      repository: "pgr-services-db"

# Container Configs
image:
  repository: "pgr-services"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/pgr-services/health"
  readinessProbePath: "/pgr-services/health"
appType: "java-spring"
tracing-enabled: true
notification-sms-enabled: "true"
notification-email-enabled: "false"
new-complaint-enabled: "true"
reassign-complaint-enabled: "true"
reopen-complaint-enabled: "true"
comment-by-employee-notif-enabled: "false"
notification-allowed-status: "open,assigned,rejected,resolved"
heap: "-Xmx384m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-pgr-services
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  {{- if index .Values "global" "serializers-timezone-in-ist" }}
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_INFRA_SEARCHER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-searcher
  - name: EGOV_COMMON_MASTERS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-common-masters
  - name: EGOV_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  - name: EGOV_UI_APP_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: NOTIFICATION_SMS_ENABLED
    value: {{ index .Values "notification-sms-enabled" | quote }}
  - name: NOTIFICATION_EMAIL_ENABLED
    value: {{ index .Values "notification-email-enabled" | quote }}
  - name: NEW_COMPLAINT_ENABLED
    value: {{ index .Values "new-complaint-enabled" | quote }}
  - name: REASSIGN_COMPLAINT_ENABLED
    value: {{ index .Values "reassign-complaint-enabled" | quote }}
  - name: REOPEN_COMPLAINT_ENABLED
    value: {{ index .Values "reopen-complaint-enabled" | quote }}
  - name: COMMENT_BY_EMPLOYEE_NOTIF_ENABLED
    value: {{ index .Values "comment-by-employee-notif-enabled" | quote }}
  - name: EGOV_PGR_APP_PLAYSTORE_LINK
    value: "https://goo.gl/ArDyQ1"
  - name: NOTIFICATION_ALLOWED_ON_STATUS
    value: {{ index .Values "notification-allowed-status" | quote }}
  - name: EGOV_HRMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-hrms
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-enable-debug" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false" 
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: EGOV_USR_EVENTS_NOTIFICATION_ENABLED
    value: "true"
  - name: EGOV_USR_EVENTS_CREATE_TOPIC
    value: "persist-user-events-async"
  - name: EGOV_USR_EVENTS_RATE_LINK
    value: "/citizen/otpLogin?mobileNo=$mobile&redirectTo=feedback/$servicerequestid"
  - name: EGOV_USR_EVENTS_REOPEN_LINK
    value: "/citizen/otpLogin?mobileNo=$mobile&redirectTo=reopen-complaint/$servicerequestid"
  - name: EGOV_USR_EVENTS_RATE_CODE
    value: "RATE"
  - name: EGOV_USR_EVENTS_REOPEN_CODE
    value: "REOPEN" 
  - name: PGR_STATELEVEL_TENANTID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  {{- if index .Values "time-before-closing-complaint" }}
  - name: PGR_COMPLAIN_IDLE_TIME
    value: {{ index .Values "time-before-closing-complaint" | quote }} 
  {{- end }}


  
