environments:
  uat:
    values:
      - ../environments/env-secrets.yaml
      - ../environments/env.yaml
---
templates:
  default: &default
    chart: ./{{`{{ .Release.Name }}`}}
    version: 0.1.0
    namespace: egov
    # This prevents helmfile exiting when it encounters a missing file
    # Valid values are "Error", "Warn", "Info", "Debug". The default is "Error"
    # Use "Debug" to make missing files errors invisible at the default log level(--log-level=INFO)
    missingFileHandler: Warn
    values:
      - {{ .Values | toYaml | nindent 8 }}

releases:
  - name: birth-death-services # Replace with your desired namespace
    installed: true # Replace with the version of your chart, if needed
    <<: *default

  - name: bpa-calculator # Replace with your desired namespace
    installed: true # Replace with the version of your chart, if needed
    <<: *default

  - name: bpa-services # Replace with your desired namespace
    installed: true
    <<: *default

  - name: echallan-calculator # Replace with your desired namespace
    installed: true
    <<: *default

  - name: echallan-services # Replace with your desired namespace
    installed: true
    <<: *default

  - name: egov-edcr # Replace with your desired namespace
    installed: true
    <<: *default

  - name: firenoc-calculator # Replace with your desired namespace
    installed: true
    <<: *default

  - name: firenoc-services # Replace with your desired namespace
    installed: true
    <<: *default

  - name: land-services # Replace with your desired namespace
    installed: true
    <<: *default

  - name: noc-services # Replace with your desired namespace
    installed: true
    <<: *default

  - name: pgr-services # Replace with your desired namespace
    installed: true
    <<: *default

  - name: property-services # Replace with your desired namespace
    installed: true
    <<: *default

  - name: pt-calculator-v2 # Replace with your desired namespace
    installed: true
    <<: *default

  - name: pt-services-v2 # Replace with your desired namespace
    installed: true
    <<: *default

  - name: sw-calculator # Replace with your desired namespace
    installed: true
    <<: *default

  - name: sw-services # Replace with your desired namespace
    installed: true
    <<: *default

  - name: tl-calculator # Replace with your desired namespace
    installed: true
    <<: *default

  - name: tl-services # Replace with your desired namespace
    installed: true
    <<: *default

  - name: ws-calculator # Replace with your desired namespace
    installed: true
    <<: *default

  - name: ws-services # Replace with your desired namespace
    installed: true
    <<: *default
  
  - name: egov-finance # Replace with your desired namespace
    installed: true
    <<: *default

  #Utiliy services start
  - name: egov-survey-services # Replace with your desired namespace
    installed: true
    <<: *default

  - name: report # Replace with your desired namespace
    installed: true
    <<: *default
  #Utiliy services end

  # Frontend services start
  - name: citizen # Replace with your desired namespace
    installed: true
    <<: *default

  - name: digit-ui # Replace with your desired namespace
    installed: true
    <<: *default

  - name: employee # Replace with your desired namespace
    installed: true
    <<: *default
  # Frontend services end