# Common Labels
labels:
  app: "noc-services"
  group: "rainmaker"

namespace: urban

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "noc-services"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "noc_services_schema"
    image:
      repository: "noc-services-db"

# Container Configs
image:
  repository: "noc-services"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/noc-services/health"
  readinessProbePath: "/noc-services/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"
egov.idgen.bpa.applicationNum.format: "PB-BP-[cy:yyyy-MM-dd]-[SEQ_EG_BP_APN]"

# Additional Container Envs
env: |
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: WORKFLOW_CONTEXT_PATH
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2 
  - name: WORKFLOW_TRANSITION_PATH
    value: "egov-workflow-v2/egov-wf/process/_transition"
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-noc-services
  - name: PERSISTER_SAVE_NOC_TOPIC
    value: save-noc-application
  - name: PERSISTER_UPDATE_NOC_TOPIC
    value: update-noc-application
  - name: PERSISTER_UPDATE_NOC_WORKFLOW_TOPIC
    value: update-noc-workflow
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
