# Common Labels
labels:
  app: "mukta-expense-calculator"
  group: "mukta"

namespace: mukta

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "mukta-expense-calculator"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "expense_calculator_schema"
    image:
      repository: "mukta-expense-calculator-db"

# Container Configs
image:
  repository: "mukta-expense-calculator"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/mukta-expense-calculator/health"
  readinessProbePath: "/mukta-expense-calculator/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
  - name: SERVER_CONTEXT_PATH
    value: /mukta-expense-calculator
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /mukta-expense-calculator
  {{- if index .Values "java-enable-debug" }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  {{- end }}
  - name: EXPENSE_CALCULATOR_CREATE_TOPIC
    value: "mukta-save-calculator"
  - name: EXPENSE_CALCULATOR_ERROR_TOPIC
    value: "mukta-calculate-error"
  - name: EXPENSE_CALCULATOR_CREATE_BILL_TOPIC
    value: "mukta-calculate-billmeta"
  - name: EGOV_SMS_NOTIFICATION_TOPIC
    value: "mukta.egov.core.notification.sms"
  - name: EGOV_MUSTERROLL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: muster-roll-service
  - name: EGOV_BILL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: expense
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "egov-mdms-service/v1/_search"      
  - name: EGOV_IDGEN_HOST
    valueFrom: 
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_CONTRACT_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: contract-service
  - name: EGOV_ORGANISATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: organisation
  - name: EGOV_MDMS_V2_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service-v2
  {{- if index .Values "egov-contract-service-search-endpoint" }}
  - name: EGOV_CONTRACT_SERVICE_SEARCH_ENDPOINT
    value: {{ index .Values "egov-contract-service-search-endpoint" | quote }}
  {{- end }}
  {{- if index .Values "egov-expense-bill-service-search-endpoint" }}
  - name: EGOV_EXPENSE_BILL_SERVICE_SEARCH_ENDPOINT
    value: {{ index .Values "egov-expense-bill-service-search-endpoint" | quote }}
  {{- end }}
  {{- if index .Values "egov-bill-create-endpoint" }}
  - name: EGOV_BILL_CREATE_ENDPOINT
    value: {{ index .Values "egov-bill-create-endpoint" | quote }}
  {{- end }}
  {{- if index .Values "egov-bill-update-endpoint" }}
  - name: EGOV_BILL_UPDATE_ENDPOINT
    value: {{ index .Values "egov-bill-update-endpoint" | quote }}
  {{- end }}
