# Common Labels
labels:
  app: "egov-indexer"
  group: "core"

hpa:
  enabled: true

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "egov-indexer"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_indexer_schema"
    image:
      repository: "egov-indexer-db"
  gitSync:
    enabled: true
    repo: "git@github.com:egovernments/configs"
    branch: "master"

# Container Configs
image:
  repository: "egov-indexer"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/egov-indexer/health"
  readinessProbePath: "/egov-indexer/health"
appType: "java-spring"
tracing-enabled: true
egov-indexer-yaml-repo-path: "file:///work-dir/configs/staging/egov-indexer/billingservices-indexer.yml,file:///work-dir/configs/staging/egov-indexer/bpa-inbox-indexer.yml,file:///work-dir/configs/staging/egov-indexer/chatbot-telemetry-v2.yaml,file:///work-dir/configs/staging/egov-indexer/chatbot-telemetry.yaml,file:///work-dir/configs/staging/egov-indexer/citizen-feedback-indexer.yml,file:///work-dir/configs/staging/egov-indexer/collection-indexer.yml,file:///work-dir/configs/staging/egov-indexer/edcr-indexer.yml,file:///work-dir/configs/staging/egov-indexer/egov-bpa-indexer.yml,file:///work-dir/configs/staging/egov-indexer/egov-echallan.yml,file:///work-dir/configs/staging/egov-indexer/egov-error-queue-indexer.yml,file:///work-dir/configs/staging/egov-indexer/egov-fsm.yml,file:///work-dir/configs/staging/egov-indexer/egov-noc-services.yml,file:///work-dir/configs/staging/egov-indexer/egov-telemetry-indexer.yml,file:///work-dir/configs/staging/egov-indexer/egov-uploader-indexer.yml,file:///work-dir/configs/staging/egov-indexer/egov-url-shortening-indexer.yaml,file:///work-dir/configs/staging/egov-indexer/egov-vehicle.yaml,file:///work-dir/configs/staging/egov-indexer/error-queue.yml,file:///work-dir/configs/staging/egov-indexer/facility-indexer.yml,file:///work-dir/configs/staging/egov-indexer/finance-rolloutadotpion-indexer.yml,file:///work-dir/configs/staging/egov-indexer/fire-noc-service.yml,file:///work-dir/configs/staging/egov-indexer/household-indexer.yml,file:///work-dir/configs/staging/egov-indexer/individual-indexer.yml,file:///work-dir/configs/staging/egov-indexer/payment-indexer.yml,file:///work-dir/configs/staging/egov-indexer/pgr-migration-batch-indexer.yml,file:///work-dir/configs/staging/egov-indexer/pgr-services.yml,file:///work-dir/configs/staging/egov-indexer/privacy-audit.yaml,file:///work-dir/configs/staging/egov-indexer/product-indexer.yml,file:///work-dir/configs/staging/egov-indexer/project-indexer.yml,file:///work-dir/configs/staging/egov-indexer/project-staff-indexer.yml,file:///work-dir/configs/staging/egov-indexer/project-task-indexer.yml,file:///work-dir/configs/staging/egov-indexer/property-services.yml,file:///work-dir/configs/staging/egov-indexer/pt-inbox-indexer.yml,file:///work-dir/configs/staging/egov-indexer/rainmaker-birth-indexer.yml,file:///work-dir/configs/staging/egov-indexer/rainmaker-bpastakeholder-indexer.yml,file:///work-dir/configs/staging/egov-indexer/rainmaker-death-indexer.yml,file:///work-dir/configs/staging/egov-indexer/rainmaker-pgr-indexer.yml,file:///work-dir/configs/staging/egov-indexer/rainmaker-pt-indexer.yml,file:///work-dir/configs/staging/egov-indexer/rainmaker-tl-indexer.yml,file:///work-dir/configs/staging/egov-indexer/referral-management-indexer.yml,file:///work-dir/configs/staging/egov-indexer/sample.yml,file:///work-dir/configs/staging/egov-indexer/service-request-indexer.yml,file:///work-dir/configs/staging/egov-indexer/sewerage-service.yml,file:///work-dir/configs/staging/egov-indexer/stock-indexer.yml,file:///work-dir/configs/staging/egov-indexer/tl-inbox-indexer.yml,file:///work-dir/configs/staging/egov-indexer/tradelicense-indexer.yml,file:///work-dir/configs/staging/egov-indexer/water-service.yml,file:///work-dir/configs/staging/egov-indexer/water-services-meter.yml,file:///work-dir/configs/staging/egov-indexer/ws-event-indexer.yml,file:///work-dir/configs/staging/works/egov-indexer/project-indexer.yml,file:///work-dir/configs/staging/works/egov-indexer/contractservices-indexer.yml,file:///work-dir/configs/staging/works/egov-indexer/organisationservices-indexer.yml,file:///work-dir/configs/staging/works/egov-indexer/expensebill-indexer.yml,file:///work-dir/configs/staging/works/egov-indexer/ifms-pi-indexer.yml,file:///work-dir/configs/staging/works/egov-indexer/measurement-indexer.yml,file:///work-dir/configs/staging/works/egov-indexer/works-digit-exchange-indexer.yml,file:///work-dir/configs/staging/works/egov-indexer/ifms-digit-exchange-indexer.yml,file:///work-dir/configs/staging/works/egov-indexer/mukta-pi-indexer.yml,file:///work-dir/configs/staging/works/egov-indexer/transform-ifms-pi-index.yml,file:///work-dir/configs/staging/works/egov-indexer/projectmanagementsystem-indexer.yml"
heap: "-Xmx256m -Xms256m"
memory_limits: 512Mi
indexer-host: "egov-indexer"

# Additional Container Envs
env: |
  - name: EGOV_SERVICES_INFRA_INDEXER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: {{ index .Values "indexer-host" }}
  - name: EGOV_INFRA_INDEXER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: es-indexer-host
  - name: EGOV_INDEXER_YML_REPO_PATH
    value: {{ index .Values "egov-indexer-yaml-repo-path" | quote }}
  {{- if index .Values "global" "serializers-timezone-in-ist" }}
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
  {{- end }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: EGOV_STATELEVEL_TENANTID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: EGOV_INDEXER_ES_USERNAME
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: username
  - name: EGOV_INDEXER_ES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: password   
  - name: PROPERTY_ES_INDEX
    value: "pg-property-services"
  - name: EGOV_INDEXER_DSS_COLLECTIONINDEX_TOPIC
    value: {{ index .Values "dss-collectionindex-topic" | quote }}
