# Common Labels
labels:
  app: "pqm-scheduler"
  group: "rainmaker"

cron:
  schedule: "*/10 * * * *"
  
# Container Configs
image:
  repository: "pqm-scheduler"
  tag: "vNA-7201d5466b-13"

command: 
  - "python3"
  - "cronJobAPIConfig.py"
args: 
  - "daily"  


# Additional Container Envs
env: |
  - name: TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: USER_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user-egov
  - name: PQM_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: pqm-service
  {{- if index .Values "user-name" }}
  - name: USER_NAME
    value: {{ index .Values "user-name" | quote }}
  {{- end }}
resources: |
  requests: {}
  
    
